// ── CoachOS Bodyweight Bibliotheek — Fase 1 ──────────────────────────────────
// 30 oefeningen verdeeld over 5 coachDoelen.
// Architectuur: Coach bepaalt doel + duur + belasting →
// Route filtert op coachDoelen → Trainer AI krijgt lijst + maakt sessie.

export type CoachDoel =
  | 'kracht'
  | 'conditie'
  | 'herstel'
  | 'mobiliteit'
  | 'warmup'
  | 'core'

export type Lichaamsdeel =
  | 'benen'
  | 'bilspieren'
  | 'core'
  | 'borst'
  | 'rug'
  | 'schouders'
  | 'volledig'

export type Niveau = 'beginner' | 'gemiddeld' | 'gevorderd'

export interface BodyweightOefening {
  id: string
  naam: string
  categorie: string
  lichaamsdelen: Lichaamsdeel[]
  coachDoelen: CoachDoel[]
  niveau: Niveau
  duur?: number           // seconden (voor tijdgebaseerde oefeningen)
  herhalingen?: string    // bijv. "10-15" of "zoveel mogelijk"
  uitleg: string          // korte uitleg voor de prompt
  beschrijving: string    // volledige uitleg voor de uitlegpagina
  tips: string[]
  fouten: string[]
  primaireSpieren: string[]
  secundaireSpieren: string[]
  herstel: boolean        // geschikt als herstel-oefening
  mobiliteit: boolean     // heeft mobiliteitscomponent
}

export const BODYWEIGHT_OEFENINGEN: BodyweightOefening[] = [

  // ── RECOVERY (5) ──────────────────────────────────────────────────────────

  {
    id: 'box-breathing',
    naam: 'Box Breathing',
    categorie: 'Herstel',
    lichaamsdelen: ['volledig'],
    coachDoelen: ['herstel'],
    niveau: 'beginner',
    duur: 240,
    uitleg: 'Adem 4 seconden in, houd 4 seconden vast, adem 4 seconden uit, houd 4 seconden vast. Herhaal.',
    beschrijving: 'Ga zitten of liggen in een comfortabele positie. Adem langzaam in door de neus terwijl je tot 4 telt. Houd de adem vast terwijl je tot 4 telt. Adem langzaam uit terwijl je tot 4 telt. Houd opnieuw vast terwijl je tot 4 telt. Herhaal dit ritme gedurende de hele sessie.',
    tips: [
      'Houd je schouders ontspannen',
      'Adem vanuit je buik, niet je borst',
      'Sluit je ogen als dat helpt',
      'Forceer het ritme niet — pas aan als nodig',
    ],
    fouten: [
      'Te snel ademen',
      'Schouders optrekken bij inademen',
      'Spanning vasthouden in het lichaam',
    ],
    primaireSpieren: [],
    secundaireSpieren: [],
    herstel: true,
    mobiliteit: false,
  },

  {
    id: 'childs-pose',
    naam: 'Child\'s Pose',
    categorie: 'Herstel',
    lichaamsdelen: ['rug', 'schouders'],
    coachDoelen: ['herstel', 'mobiliteit'],
    niveau: 'beginner',
    duur: 60,
    uitleg: 'Kniel op de grond, strek je armen vooruit en laat je voorhoofd zakken naar de mat. Houd de positie vast.',
    beschrijving: 'Begin op handen en knieën. Duw je heupen naar achteren richting je hielen terwijl je armen gestrekt naar voren blijven. Laat je voorhoofd rusten op de mat. Adem diep in en voel hoe je rug zich bij elke uitademing iets meer ontspant. Houd de positie comfortabel vast.',
    tips: [
      'Laat je schouders zakken bij elke uitademing',
      'Duw je heupen actief naar je hielen',
      'Spreid je knieën iets uit als je heupen strak zijn',
      'Adem diep en langzaam',
    ],
    fouten: [
      'Schouders optrekken naar de oren',
      'Heupen omhoog houden van de hielen',
      'Adem inhouden',
    ],
    primaireSpieren: ['Rugspieren', 'Latissimus dorsi'],
    secundaireSpieren: ['Schouders', 'Heupen'],
    herstel: true,
    mobiliteit: true,
  },

  {
    id: 'cat-cow',
    naam: 'Cat-Cow',
    categorie: 'Herstel',
    lichaamsdelen: ['rug', 'core'],
    coachDoelen: ['herstel', 'mobiliteit', 'warmup'],
    niveau: 'beginner',
    herhalingen: '10-15',
    uitleg: 'Op handen en knieën: wissel tussen rug hol trekken (Cow) en rug ronden (Cat). Langzaam en gecontroleerd.',
    beschrijving: 'Begin op handen en knieën met polsen onder schouders en knieën onder heupen. Cow: adem in, laat je buik zakken, til je hoofd en staartbeen omhoog. Cat: adem uit, rond je rug omhoog, trek je navel naar de wervelkolom en laat je hoofd zakken. Beweeg vloeiend tussen de twee posities.',
    tips: [
      'Beweeg langzaam en bewust',
      'Synchroniseer de beweging met je ademhaling',
      'Voel elke wervel individueel bewegen',
      'Houd je armen recht',
    ],
    fouten: [
      'Te snel bewegen',
      'Ellebogen buigen',
      'Ademhaling loskoppelen van de beweging',
    ],
    primaireSpieren: ['Rugspieren', 'Core'],
    secundaireSpieren: ['Nek', 'Schouders'],
    herstel: true,
    mobiliteit: true,
  },

  {
    id: 'thoracic-rotation',
    naam: 'Thoracale Rotatie',
    categorie: 'Herstel',
    lichaamsdelen: ['rug'],
    coachDoelen: ['herstel', 'mobiliteit'],
    niveau: 'beginner',
    herhalingen: '8-10 per kant',
    uitleg: 'Lig op je zij met knieën gebogen. Strek je bovenste arm voor je uit en roteer langzaam naar de andere kant. Volg met je blik.',
    beschrijving: 'Ga op je zij liggen met heupen en knieën gebogen in een hoek van 90 graden. Leg beide armen gestrekt voor je. Til je bovenste arm op en roteer langzaam je bovenlichaam terwijl je de arm naar de andere kant beweegt. Volg de beweging met je blik. Laat je knieën op de grond liggen. Keer terug naar de startpositie en herhaal.',
    tips: [
      'Houd je knieën op de grond tijdens de rotatie',
      'Beweeg langzaam en gecontroleerd',
      'Adem uit tijdens de rotatie',
      'Forceer het bereik niet',
    ],
    fouten: [
      'Knieën optillen van de grond',
      'Te snel draaien',
      'Schouder niet volledig laten zakken',
    ],
    primaireSpieren: ['Thoracale wervelkolom', 'Rugspieren'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: true,
    mobiliteit: true,
  },

  {
    id: 'deep-squat-hold',
    naam: 'Deep Squat Hold',
    categorie: 'Herstel',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['herstel', 'mobiliteit'],
    niveau: 'beginner',
    duur: 60,
    uitleg: 'Sta met voeten op schouderbreedte. Zak zo diep mogelijk door de knieën en houd de positie vast. Gebruik een steun indien nodig.',
    beschrijving: 'Sta met voeten iets wijder dan schouderbreedte, tenen licht naar buiten gedraaid. Zak langzaam zo diep mogelijk door de knieën terwijl je borst rechtop blijft. Druk je knieën naar buiten met je ellebogen. Houd de positie vast. Als je hielen van de grond komen, sta dan een klein steuntje toe of rol een handdoek onder je hielen.',
    tips: [
      'Druk knieën naar buiten — gebruik ellebogen als hendel',
      'Borst rechtop houden',
      'Hielen op de grond houden',
      'Gebruik een steun als de positie te uitdagend is',
    ],
    fouten: [
      'Hielen van de grond',
      'Borst naar voren vallen',
      'Knieën naar binnen zakken',
    ],
    primaireSpieren: ['Heupen', 'Bilspieren', 'Quadriceps'],
    secundaireSpieren: ['Kuitspieren', 'Hamstrings'],
    herstel: true,
    mobiliteit: true,
  },

  // ── MOBILITEIT (5) ────────────────────────────────────────────────────────

  {
    id: 'worlds-greatest-stretch',
    naam: 'World\'s Greatest Stretch',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['volledig'],
    coachDoelen: ['mobiliteit', 'warmup'],
    niveau: 'beginner',
    herhalingen: '5 per kant',
    uitleg: 'Stap groot naar voren in een lunge, plaats je hand naast je voorvoet, roteer je bovenlichaam en strek je arm omhoog. Houd even vast.',
    beschrijving: 'Begin staand. Stap groot naar voren met je rechtervoet in een lunge. Plaats je linkerhand op de grond naast je rechtervoet. Roteer je bovenlichaam naar rechts en strek je rechterarm omhoog naar het plafond. Volg met je blik. Houd 2-3 seconden vast, keer terug en herhaal aan de andere kant.',
    tips: [
      'Houd je voorste knie boven je enkel',
      'Beweeg langzaam en bewust',
      'Strek de arm volledig omhoog',
      'Laat je heup zakken in de lunge',
    ],
    fouten: [
      'Voorste knie naar binnen zakken',
      'Arm niet volledig strekken',
      'Te snel bewegen',
    ],
    primaireSpieren: ['Heupen', 'Borstkas', 'Thoracale wervelkolom'],
    secundaireSpieren: ['Schouders', 'Hamstrings', 'Core'],
    herstel: false,
    mobiliteit: true,
  },

  {
    id: '90-90-stretch',
    naam: '90/90 Stretch',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['bilspieren', 'benen'],
    coachDoelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    duur: 60,
    uitleg: 'Zit op de grond met beide benen in een hoek van 90 graden — één been voor je, één been aan de zijkant. Leun licht naar voren over je voorste been.',
    beschrijving: 'Ga op de grond zitten. Buig je rechterbeeen voor je in een hoek van 90 graden (heup, knie en enkel allemaal op 90 graden). Buig je linker been naar de zijkant ook in een hoek van 90 graden. Blijf rechtop zitten of leun licht naar voren over je voorste been voor een diepere stretch. Houd de positie vast en wissel daarna van kant.',
    tips: [
      'Houd je rug recht',
      'Forceer de positie niet',
      'Adem diep in de stretch',
      'Begin met een kortere tijd als het oncomfortabel voelt',
    ],
    fouten: [
      'Rug bol trekken',
      'Te ver naar voren leunen',
      'Heup van de grond tillen',
    ],
    primaireSpieren: ['Piriformis', 'Bilspieren', 'Heupabductoren'],
    secundaireSpieren: ['Hamstrings', 'Heuprotatoren'],
    herstel: true,
    mobiliteit: true,
  },

  {
    id: 'hip-flexor-stretch',
    naam: 'Heupbuiger Stretch',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['mobiliteit', 'herstel', 'warmup'],
    niveau: 'beginner',
    duur: 45,
    uitleg: 'Kniel op één knie in een lunge-positie. Duw je heupen naar voren en omlaag. Houd de positie vast.',
    beschrijving: 'Kniel op je rechterknee met je linkervoet voor je op de grond in een lunge. Houd je romp rechtop. Duw je heupen langzaam naar voren en omlaag totdat je een stretch voelt aan de voorkant van je rechterdij. Houd de positie vast. Wissel daarna van kant.',
    tips: [
      'Houd je romp recht — niet naar voren leunen',
      'Span je bilspieren aan van het achterste been',
      'Duw actief naar voren, niet alleen zakken',
      'Adem diep in de stretch',
    ],
    fouten: [
      'Romp naar voren leunen',
      'Voorste knie over de teen laten komen',
      'Bilspieren niet aanspannen',
    ],
    primaireSpieren: ['Heupbuigers', 'Iliopsoas'],
    secundaireSpieren: ['Quadriceps', 'Bilspieren'],
    herstel: true,
    mobiliteit: true,
  },

  {
    id: 'shoulder-rolls',
    naam: 'Schouderrollen',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['schouders', 'rug'],
    coachDoelen: ['mobiliteit', 'herstel', 'warmup'],
    niveau: 'beginner',
    herhalingen: '10 voor, 10 achter',
    uitleg: 'Rol je schouders langzaam naar voren en achteren in grote cirkels. Houd je armen ontspannen.',
    beschrijving: 'Sta of zit rechtop met armen ontspannen langs je lichaam. Rol beide schouders tegelijk langzaam naar voren in grote cirkels — omhoog, naar voren, omlaag, naar achteren. Doe 10 herhalingen. Keer daarna de richting om en doe 10 herhalingen naar achteren.',
    tips: [
      'Maak grote, langzame cirkels',
      'Houd je nek ontspannen',
      'Adem rustig door',
      'Voel waar de spanning zit',
    ],
    fouten: [
      'Te kleine bewegingen maken',
      'Nek mee laten bewegen',
      'Te snel draaien',
    ],
    primaireSpieren: ['Trapezius', 'Schouderbladen'],
    secundaireSpieren: ['Nek', 'Bovenrug'],
    herstel: true,
    mobiliteit: true,
  },

  {
    id: 'inchworm',
    naam: 'Inchworm',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['volledig'],
    coachDoelen: ['mobiliteit', 'warmup'],
    niveau: 'beginner',
    herhalingen: '6-8',
    uitleg: 'Sta rechtop, buig naar voren, loop met je handen naar een plankpositie, loop terug en kom omhoog. Herhaal.',
    beschrijving: 'Sta rechtop met voeten op heupbreedte. Buig langzaam naar voren en raak de grond aan. Loop met je handen naar voren totdat je in een plankpositie bent. Houd kort vast. Loop dan met je voeten naar je handen. Kom langzaam omhoog en herhaal.',
    tips: [
      'Houd je benen zo recht mogelijk bij het naar voren buigen',
      'Beweeg langzaam en gecontroleerd',
      'Houd je core actief in de plankpositie',
      'Adem uit bij het naar voren lopen',
    ],
    fouten: [
      'Knieën te ver buigen',
      'Heupen te hoog in de plank',
      'Te snel bewegen',
    ],
    primaireSpieren: ['Hamstrings', 'Core', 'Schouders'],
    secundaireSpieren: ['Rugspieren', 'Borstkas'],
    herstel: false,
    mobiliteit: true,
  },

  // ── WARMUP (5) ────────────────────────────────────────────────────────────

  {
    id: 'jumping-jacks',
    naam: 'Jumping Jacks',
    categorie: 'Warmup',
    lichaamsdelen: ['volledig'],
    coachDoelen: ['warmup', 'conditie'],
    niveau: 'beginner',
    herhalingen: '20-30',
    uitleg: 'Spring met beide benen tegelijk naar buiten terwijl je armen omhoog gaan. Spring terug naar de startpositie. Herhaal in een regelmatig tempo.',
    beschrijving: 'Sta rechtop met voeten samen en armen langs je lichaam. Spring en beweeg je voeten naar buiten terwijl je armen zijwaarts omhoog gaan tot boven je hoofd. Spring terug naar de startpositie met voeten samen en armen omlaag. Herhaal in een consistent ritme.',
    tips: [
      'Land zacht op de ballen van je voeten',
      'Houd je knieën licht gebogen bij de landing',
      'Houd een regelmatig ritme',
      'Adem rustig door',
    ],
    fouten: [
      'Hard landen op je hielen',
      'Knieën naar binnen zakken',
      'Armen niet volledig strekken',
    ],
    primaireSpieren: ['Schouders', 'Heupen', 'Kuitspieren'],
    secundaireSpieren: ['Core', 'Quadriceps'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'arm-circles',
    naam: 'Armcirkels',
    categorie: 'Warmup',
    lichaamsdelen: ['schouders'],
    coachDoelen: ['warmup', 'mobiliteit'],
    niveau: 'beginner',
    herhalingen: '15 voor, 15 achter',
    uitleg: 'Strek beide armen zijwaarts en maak kleine tot grote cirkels. Wissel van richting.',
    beschrijving: 'Sta rechtop met voeten op heupbreedte. Strek beide armen horizontaal uit aan de zijkant. Begin met kleine cirkels naar voren en vergroot geleidelijk. Doe 15 herhalingen. Wissel daarna van richting voor nog 15 herhalingen.',
    tips: [
      'Houd je armen echt gestrekt',
      'Begin klein en vergroot de beweging',
      'Houd je schouders laag — niet optrekken',
      'Sta stabiel op beide voeten',
    ],
    fouten: [
      'Armen laten zakken',
      'Schouders optrekken',
      'Romp mee laten draaien',
    ],
    primaireSpieren: ['Schouders', 'Rotatorenmanchet'],
    secundaireSpieren: ['Trapezius', 'Bovenrug'],
    herstel: false,
    mobiliteit: true,
  },

  {
    id: 'air-squat',
    naam: 'Air Squat',
    categorie: 'Warmup',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['warmup', 'kracht'],
    niveau: 'beginner',
    herhalingen: '15-20',
    uitleg: 'Sta met voeten op schouderbreedte. Zak door de knieën totdat je dijen parallel zijn aan de grond. Drijf omhoog.',
    beschrijving: 'Sta met voeten op schouderbreedte, tenen licht naar buiten. Strek je armen voor je uit voor balans. Zak langzaam door de knieën terwijl je je borst omhoog houdt. Ga totdat je dijen parallel zijn aan de grond of dieper als mobiliteit het toelaat. Drijf omhoog via je hielen.',
    tips: [
      'Houd je borst omhoog en rug recht',
      'Knieën volgen de richting van de tenen',
      'Drijf omhoog via de hielen',
      'Houd je gewicht in het midden van je voeten',
    ],
    fouten: [
      'Borst naar voren vallen',
      'Knieën naar binnen zakken',
      'Hielen van de grond',
      'Onvoldoende diepte',
    ],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Kuitspieren', 'Core'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'walking-lunge',
    naam: 'Walking Lunge',
    categorie: 'Warmup',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['warmup', 'kracht'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Stap groot naar voren en zak door je voorste knie. Kom omhoog en stap direct met het andere been naar voren.',
    beschrijving: 'Sta rechtop. Stap groot naar voren met je rechtervoet. Laat je linkerknee zakken naar de grond (maar raak de grond niet). Houd je romp rechtop. Kom omhoog en stap direct door met je linkervoet naar voren. Wissel zo afwisselend van been terwijl je vooruitloopt.',
    tips: [
      'Houd je romp rechtop — niet naar voren leunen',
      'Voorste knie boven de enkel houden',
      'Stap breed genoeg voor een goede range',
      'Land zacht op je voorste voet',
    ],
    fouten: [
      'Romp naar voren leunen',
      'Voorste knie over de teen',
      'Te kleine stappen',
      'Achterste knie hard op de grond',
    ],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'high-knees',
    naam: 'High Knees',
    categorie: 'Warmup',
    lichaamsdelen: ['benen', 'core'],
    coachDoelen: ['warmup', 'conditie'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Loop op de plaats en breng je knieën zo hoog mogelijk terwijl je je armen mee swingt. Houd een snel tempo.',
    beschrijving: 'Sta rechtop. Begin te lopen op de plaats terwijl je je knieën abwisselend zo hoog mogelijk optilt — idealiter tot heupniveau. Swing je armen mee als bij het lopen. Houd een snel en consistent tempo gedurende de hele set.',
    tips: [
      'Til je knieën echt tot heupniveau',
      'Land op de bal van je voet',
      'Houd je romp rechtop',
      'Swing je armen actief mee',
    ],
    fouten: [
      'Knieën niet hoog genoeg brengen',
      'Landen op de hiel',
      'Romp naar voren leunen',
      'Armen niet meebewegen',
    ],
    primaireSpieren: ['Heupbuigers', 'Quadriceps', 'Kuitspieren'],
    secundaireSpieren: ['Core', 'Schouders'],
    herstel: false,
    mobiliteit: false,
  },

  // ── KRACHT (10) ───────────────────────────────────────────────────────────

  {
    id: 'push-up',
    naam: 'Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['borst', 'schouders'],
    coachDoelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '8-15',
    uitleg: 'Begin in plankpositie. Laat je lichaam zakken totdat je borst de grond bijna raakt. Druk omhoog. Houd je lichaam recht als een plank.',
    beschrijving: 'Begin in een hoge plankpositie met handen iets breder dan schouderbreedte. Houd je lichaam in een rechte lijn van hoofd tot hielen. Buig je ellebogen en laat je lichaam zakken totdat je borst de grond bijna raakt. Druk krachtig omhoog naar de startpositie.',
    tips: [
      'Houd je lichaam recht als een plank — geen hangende heupen',
      'Ellebogen op 45 graden ten opzichte van je lichaam',
      'Volledige range — borst bijna de grond',
      'Span je core en billen aan voor stabiliteit',
    ],
    fouten: [
      'Heupen omhoog of omlaag hangen',
      'Ellebogen te wijd — richting 90 graden',
      'Onvoldoende diepte',
      'Hoofd naar voren steken',
    ],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'incline-push-up',
    naam: 'Incline Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['borst', 'schouders'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '10-15',
    uitleg: 'Zelfde als een push-up maar met je handen op een verhoogd oppervlak (bank, muur). Makkelijker dan een gewone push-up.',
    beschrijving: 'Plaats je handen op een verhoogd oppervlak zoals een bank of stevig tafel, iets breder dan schouderbreedte. Houd je lichaam in een rechte lijn. Buig je ellebogen en laat je borst zakken naar het oppervlak. Druk omhoog. Hoe hoger het oppervlak, hoe makkelijker de oefening.',
    tips: [
      'Houd je lichaam recht — geen hangende heupen',
      'Borst raakt het oppervlak aan onderaan',
      'Ellebogen op 45 graden',
      'Span je core aan',
    ],
    fouten: [
      'Heupen zakken',
      'Ellebogen te wijd',
      'Onvoldoende diepte',
    ],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'pike-push-up',
    naam: 'Pike Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['schouders'],
    coachDoelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '8-12',
    uitleg: 'Begin in een omgekeerde V-positie (heupen hoog). Buig je ellebogen en laat je hoofd zakken naar de grond. Druk omhoog.',
    beschrijving: 'Begin in een plankpositie. Duw je heupen omhoog totdat je lichaam een omgekeerde V vormt met je hoofd tussen je armen. Buig je ellebogen en laat je hoofd zakken richting de grond tussen je handen. Druk krachtig omhoog. Dit traint primair je schouders.',
    tips: [
      'Houd je benen zo recht mogelijk',
      'Beweeg je hoofd recht omlaag — niet naar voren',
      'Heupen hoog houden tijdens de hele beweging',
      'Ellebogen richten naar buiten',
    ],
    fouten: [
      'Heupen zakken tijdens de beweging',
      'Hoofd naar voren steken',
      'Onvoldoende diepte',
    ],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Borstspieren', 'Core'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'split-squat',
    naam: 'Split Squat',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Sta in een gesplitste positie met één voet voor en één achter. Zak recht omlaag en omhoog zonder je voeten te verplaatsen.',
    beschrijving: 'Stap met je rechtervoet groot naar voren en houd je linkervoet achter je. Houd beide voeten in deze positie. Laat je lichaam recht omlaag zakken — je voorste knie buigt, je achterste knie daalt richting de grond. Drijf omhoog. Doe alle herhalingen op één been voor je wisselt.',
    tips: [
      'Houd je romp recht — niet naar voren leunen',
      'Voorste knie boven de enkel',
      'Zak recht omlaag — niet naar voren',
      'Bilspieren aanspannen bij het omhoog komen',
    ],
    fouten: [
      'Voorste knie over de teen',
      'Romp naar voren leunen',
      'Schouders optrekken',
    ],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'reverse-lunge',
    naam: 'Reverse Lunge',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht', 'warmup'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Stap achterwaarts in een lunge. Laat je achterste knie zakken naar de grond. Kom omhoog en breng je been terug.',
    beschrijving: 'Sta rechtop. Stap achterwaarts met je rechtervoet en laat je rechterknee zakken naar de grond. Houd je voorste knie boven je enkel. Je romp blijft rechtop. Drijf omhoog via je voorste been en breng je rechtervoet terug naar de startpositie. Wissel van been.',
    tips: [
      'Stap recht achterwaarts — niet naar de zijkant',
      'Voorste knie boven de enkel',
      'Houd je romp recht',
      'Land zacht op de bal van je achterste voet',
    ],
    fouten: [
      'Romp naar voren leunen',
      'Voorste knie over de teen',
      'Achterste knie hard op de grond',
    ],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'glute-bridge',
    naam: 'Glute Bridge',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren', 'benen'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '15-20',
    uitleg: 'Lig op je rug met knieën gebogen. Duw je heupen omhoog terwijl je je bilspieren aanspant. Houd even vast en laat zakken.',
    beschrijving: 'Lig op je rug met knieën gebogen en voeten plat op de grond, heupbreedte uit elkaar. Armen langs je lichaam. Span je bilspieren aan en duw je heupen omhoog totdat je lichaam een rechte lijn vormt van schouders tot knieën. Houd 1-2 seconden vast bovenin. Laat langzaam zakken.',
    tips: [
      'Span je bilspieren écht aan bovenin',
      'Duw via je hielen omhoog',
      'Houd je core actief — rug niet hol trekken',
      'Laat langzaam zakken — houd controle',
    ],
    fouten: [
      'Rug hol trekken bovenin',
      'Knieën naar binnen of buiten zakken',
      'Te snel zakken',
      'Bilspieren niet aanspannen',
    ],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: true,
    mobiliteit: false,
  },

  {
    id: 'superman',
    naam: 'Superman',
    categorie: 'Kracht',
    lichaamsdelen: ['rug'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '12-15',
    uitleg: 'Lig op je buik met armen gestrekt voor je. Til tegelijk je armen en benen van de grond. Houd even vast en laat zakken.',
    beschrijving: 'Lig op je buik met armen gestrekt voor je en benen gestrekt achter je. Span je rug- en bilspieren aan en til tegelijk je armen en benen van de grond — alsof je vliegt. Houd 2-3 seconden vast. Laat langzaam zakken en herhaal.',
    tips: [
      'Til armen en benen gelijktijdig op',
      'Houd je hoofd in lijn met je wervelkolom — niet te ver omhoog',
      'Span je bilspieren aan bij het optillen',
      'Beweeg gecontroleerd — geen schokken',
    ],
    fouten: [
      'Hoofd te ver achterover',
      'Armen en benen niet gelijktijdig',
      'Schokkerige beweging',
    ],
    primaireSpieren: ['Rugspieren', 'Erector spinae'],
    secundaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    herstel: true,
    mobiliteit: false,
  },

  {
    id: 'step-up',
    naam: 'Step-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht', 'conditie'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Stap met één voet op een verhoging (bank, trap). Duw jezelf omhoog. Stap terug en herhaal.',
    beschrijving: 'Sta voor een verhoging van 30-50 cm (bank, stevige stoel, trap). Zet je rechtervoet volledig op de verhoging. Duw jezelf omhoog via je rechtervoet totdat je staat. Stap terug met je rechtervoet als eerste. Doe alle herhalingen op één been voor je wisselt.',
    tips: [
      'Duw omhoog via je voorste been — niet afzetten met je achterste',
      'Zet je voet volledig op de verhoging',
      'Houd je romp rechtop',
      'Stap gecontroleerd terug',
    ],
    fouten: [
      'Afzetten met het achterste been',
      'Romp naar voren leunen',
      'Knie naar binnen zakken',
    ],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'calf-raise',
    naam: 'Kuitverheffen',
    categorie: 'Kracht',
    lichaamsdelen: ['benen'],
    coachDoelen: ['kracht', 'warmup'],
    niveau: 'beginner',
    herhalingen: '20-25',
    uitleg: 'Sta met voeten op heupbreedte. Kom op de ballen van je voeten omhoog. Laat langzaam zakken.',
    beschrijving: 'Sta rechtop met voeten op heupbreedte. Gebruik een muur of leuning voor balans indien nodig. Kom langzaam op de ballen van je voeten omhoog — zo hoog mogelijk. Houd 1 seconde vast bovenin. Laat langzaam zakken totdat je hielen bijna de grond raken.',
    tips: [
      'Ga zo hoog mogelijk op je ballen',
      'Beweeg langzaam — focus op controle',
      'Houd je knieën licht gebogen — niet op slot',
      'Beide voeten gelijk belasten',
    ],
    fouten: [
      'Te snel zakken',
      'Niet hoog genoeg komen',
      'Gewicht naar één kant verschuiven',
    ],
    primaireSpieren: ['Kuitspieren', 'Gastrocnemius'],
    secundaireSpieren: ['Soleus', 'Enkels'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'wall-sit',
    naam: 'Wall Sit',
    categorie: 'Kracht',
    lichaamsdelen: ['benen'],
    coachDoelen: ['kracht'],
    niveau: 'beginner',
    duur: 45,
    uitleg: 'Leun met je rug tegen een muur en zak door je knieën tot 90 graden. Houd de positie vast.',
    beschrijving: 'Leun met je rug plat tegen een muur. Schuif naar beneden totdat je knieën in een hoek van 90 graden zijn — alsof je op een onzichtbare stoel zit. Voeten op schouderbreedte, recht voor je. Houd de positie vast gedurende de ingestelde tijd.',
    tips: [
      'Houd je rug plat tegen de muur',
      'Knieën boven je enkels — niet verder naar voren',
      'Dijen parallel aan de grond',
      'Adem rustig door',
    ],
    fouten: [
      'Rug van de muur halen',
      'Knieën over de tenen',
      'Dijen niet parallel',
    ],
    primaireSpieren: ['Quadriceps'],
    secundaireSpieren: ['Bilspieren', 'Hamstrings', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },

  // ── CORE (5) ──────────────────────────────────────────────────────────────

  {
    id: 'plank',
    naam: 'Plank',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Houd een plankpositie op handen of onderarmen. Lichaam recht als een plank. Core actief.',
    beschrijving: 'Begin op handen en knieën. Strek je benen achter je uit zodat je op je handen en teentoppen rust. Houd je lichaam in een rechte lijn van hoofd tot hielen. Span je core aan, knijp je bilspieren en houd je heupen in lijn. Adem rustig door.',
    tips: [
      'Houd je heupen in lijn — niet omhoog of omlaag',
      'Span je core actief aan',
      'Kijk naar de grond — hoofd in lijn met ruggengraat',
      'Adem rustig en gecontroleerd',
    ],
    fouten: [
      'Heupen omhoog steken',
      'Heupen naar de grond zakken',
      'Hoofd omhoog steken',
      'Adem inhouden',
    ],
    primaireSpieren: ['Core', 'Transversus abdominis'],
    secundaireSpieren: ['Schouders', 'Bilspieren', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'side-plank',
    naam: 'Zijplank',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'beginner',
    duur: 20,
    uitleg: 'Lig op je zij op je onderarm. Til je heupen op zodat je lichaam een rechte lijn vormt. Houd vast.',
    beschrijving: 'Lig op je rechterzij met je rechteronderarm op de grond, elleboog onder je schouder. Stapel je voeten op elkaar of zet ze voor/achter elkaar. Til je heupen op zodat je lichaam een rechte diagonale lijn vormt. Houd de positie vast. Wissel daarna van kant.',
    tips: [
      'Elleboog direct onder de schouder',
      'Houd je heupen omhoog — niet laten zakken',
      'Houd je lichaam in één rechte lijn',
      'Span je core aan',
    ],
    fouten: [
      'Heupen zakken',
      'Heup naar voren of achteren roteren',
      'Elleboog niet onder schouder',
    ],
    primaireSpieren: ['Obliques', 'Core'],
    secundaireSpieren: ['Schouders', 'Bilspieren'],
    herstel: false,
    mobiliteit: false,
  },

  {
    id: 'dead-bug',
    naam: 'Dead Bug',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'herstel'],
    niveau: 'beginner',
    herhalingen: '8-10 per kant',
    uitleg: 'Lig op je rug met armen omhoog en knieën gebogen. Strek tegelijk de tegenovergestelde arm en het been terwijl je je rug plat houdt.',
    beschrijving: 'Lig op je rug met armen gestrekt omhoog en benen omhoog gebogen in een hoek van 90 graden. Druk je onderrug in de mat. Strek langzaam tegelijk je rechterarm achter je hoofd en je linkerbeen naar voren — zonder je rug van de mat te laten komen. Kom terug en wissel.',
    tips: [
      'Houd je onderrug plat op de mat gedurende de hele beweging',
      'Beweeg langzaam en gecontroleerd',
      'Adem uit bij het strekken',
      'Strek volledig — arm en been volledig gestrekt',
    ],
    fouten: [
      'Onderrug van de mat laten komen',
      'Te snel bewegen',
      'Niet volledig strekken',
    ],
    primaireSpieren: ['Core', 'Transversus abdominis'],
    secundaireSpieren: ['Heupbuigers', 'Schouders'],
    herstel: true,
    mobiliteit: false,
  },

  {
    id: 'bird-dog',
    naam: 'Bird Dog',
    categorie: 'Core',
    lichaamsdelen: ['core', 'rug'],
    coachDoelen: ['core', 'herstel'],
    niveau: 'beginner',
    herhalingen: '8-10 per kant',
    uitleg: 'Op handen en knieën: strek tegelijk de tegenovergestelde arm en het been. Houd even vast. Houd je rug recht.',
    beschrijving: 'Begin op handen en knieën met polsen onder schouders en knieën onder heupen. Span je core aan. Strek langzaam tegelijk je rechterarm naar voren en je linkerbeen naar achteren — houd ze parallel aan de grond. Houd 2-3 seconden vast. Breng terug en wissel.',
    tips: [
      'Houd je rug recht — niet laten zakken of ronden',
      'Arm en been op gelijke hoogte — parallel aan de grond',
      'Houd je heupen in lijn — niet roteren',
      'Beweeg langzaam en gecontroleerd',
    ],
    fouten: [
      'Rug hol trekken',
      'Heupen naar één kant roteren',
      'Arm of been te hoog heffen',
    ],
    primaireSpieren: ['Core', 'Rugspieren'],
    secundaireSpieren: ['Bilspieren', 'Schouders', 'Hamstrings'],
    herstel: true,
    mobiliteit: false,
  },

  {
    id: 'mountain-climber',
    naam: 'Mountain Climber',
    categorie: 'Core',
    lichaamsdelen: ['core', 'benen'],
    coachDoelen: ['core', 'conditie', 'warmup'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Begin in plankpositie. Breng afwisselend je knieën snel naar je borst. Houd je heupen laag.',
    beschrijving: 'Begin in een hoge plankpositie met handen onder je schouders. Span je core aan. Breng je rechterknee snel naar je borst terwijl je linkervoet op de grond blijft. Wissel snel van been. Houd een hoog tempo terwijl je je heupen laag en stabiel houdt.',
    tips: [
      'Houd je heupen laag — niet omhoog steken',
      'Handen stevig op de grond',
      'Span je core actief aan',
      'Houd een consistent hoog tempo',
    ],
    fouten: [
      'Heupen omhoog steken',
      'Armen buigen',
      'Rug hol trekken',
    ],
    primaireSpieren: ['Core', 'Heupbuigers'],
    secundaireSpieren: ['Schouders', 'Quadriceps', 'Borst'],
    herstel: false,
    mobiliteit: false,
  },
]

// ── Hulpfuncties voor de route ─────────────────────────────────────────────

/**
 * Filtert oefeningen op coachDoel.
 * Wordt gebruikt in training/today/route.ts om de juiste
 * oefeningen aan Trainer AI door te geven.
 */
export function filterOpCoachDoel(doel: CoachDoel): BodyweightOefening[] {
  return BODYWEIGHT_OEFENINGEN.filter(o => o.coachDoelen.includes(doel))
}

/**
 * Filtert oefeningen op niveau.
 */
export function filterOpNiveau(niveau: Niveau): BodyweightOefening[] {
  return BODYWEIGHT_OEFENINGEN.filter(o => o.niveau === niveau)
}

/**
 * Filtert oefeningen op lichaamsdeel.
 */
export function filterOpLichaamsdeel(deel: Lichaamsdeel): BodyweightOefening[] {
  return BODYWEIGHT_OEFENINGEN.filter(o => o.lichaamsdelen.includes(deel))
}

/**
 * Geeft een korte prompt-vriendelijke lijst van oefeningen terug.
 * Wordt direct in de Trainer AI prompt geplakt.
 */
export function formateerVoorPrompt(oefeningen: BodyweightOefening[]): string {
  return oefeningen.map(o =>
    `- ${o.naam} (${o.niveau}, ${o.lichaamsdelen.join('/')}): ${o.uitleg}`
  ).join('\n')
}

// ── FASE 2 — Extra oefeningen ─────────────────────────────────────────────

// ── BENEN UITBREIDING ─────────────────────────────────────────────────────

const fase2Oefeningen: BodyweightOefening[] = [
  {
    id: 'bulgarian-split-squat',
    naam: 'Bulgaarse Split Squat',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '8-10 per been',
    uitleg: 'Zet je achterste voet op een bank. Zak door je voorste knie. Uitdagender dan een gewone split squat.',
    beschrijving: 'Sta voor een bank of stoel. Zet je achterste voet op de bank, wreef naar beneden. Houd je voorste voet ver genoeg naar voren. Zak recht omlaag totdat je achterste knie bijna de grond raakt. Houd je romp rechtop. Drijf omhoog via je voorste been.',
    tips: ['Voorste voet ver genoeg naar voren', 'Romp rechtop houden', 'Controleer de afdaling', 'Bilspieren aanspannen omhoog'],
    fouten: ['Voorste knie over de teen', 'Romp naar voren leunen', 'Te snel zakken'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'jump-squat',
    naam: 'Jump Squat',
    categorie: 'Conditie',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['conditie', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10-15',
    uitleg: 'Voer een squat uit en spring explosief omhoog. Land zacht en zak direct terug in de squat.',
    beschrijving: 'Sta met voeten op schouderbreedte. Zak in een squat. Spring explosief omhoog en strek je volledig. Land zacht op de ballen van je voeten en zak direct terug in de squat. Houd een vloeiend ritme.',
    tips: ['Land zacht — absorbeer de landing', 'Spring volledig op', 'Houd je borst omhoog', 'Knieën naar buiten bij de landing'],
    fouten: ['Hard landen op de hielen', 'Knieën naar binnen bij landing', 'Onvoldoende diepte'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Kuitspieren'],
    secundaireSpieren: ['Core', 'Hamstrings'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'curtsy-lunge',
    naam: 'Curtsy Lunge',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10 per been',
    uitleg: 'Stap achterwaarts en kruis je been achter je voorste been. Zak omlaag als een reverence. Traint de buitenkant van je bilspieren.',
    beschrijving: 'Sta rechtop. Stap je rechtervoet achterwaarts en kruis hem achter je linkerbeen — alsof je een reverence maakt. Laat je rechterknee zakken richting de grond. Houd je heupen naar voren gericht. Kom omhoog en breng je been terug. Wissel van kant.',
    tips: ['Houd heupen naar voren gericht — niet draaien', 'Voorste knie boven de enkel', 'Kruis echt achter het andere been', 'Romp rechtop'],
    fouten: ['Heupen roteren', 'Voorste knie naar binnen zakken', 'Romp naar voren leunen'],
    primaireSpieren: ['Bilspieren', 'Heupabductoren', 'Quadriceps'],
    secundaireSpieren: ['Hamstrings', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'side-lunge',
    naam: 'Zijwaartse Lunge',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht', 'mobiliteit'],
    niveau: 'beginner',
    herhalingen: '10 per kant',
    uitleg: 'Stap breed opzij. Zak door het gebogen been terwijl het andere been gestrekt blijft. Traint je binnenkant dij.',
    beschrijving: 'Sta rechtop. Stap breed opzij met je rechtervoet. Zak door je rechterknie terwijl je linkerbeen gestrekt blijft en je linkervoet op de grond staat. Houd je borst omhoog. Drijf omhoog en breng je been terug. Wissel van kant.',
    tips: ['Stap breed genoeg', 'Gebogen knie boven de enkel', 'Borst omhoog', 'Gestrekt been volledig gestrekt houden'],
    fouten: ['Te kleine stap', 'Gebogen knie naar binnen', 'Romp naar voren leunen'],
    primaireSpieren: ['Quadriceps', 'Heupabductoren', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Binnenkant dij', 'Core'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'single-leg-glute-bridge',
    naam: 'Eénbeen Glute Bridge',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren', 'benen'],
    coachDoelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '12 per been',
    uitleg: 'Zelfde als een glute bridge maar met één been omhoog gestrekt. Meer belasting op het steunbeen.',
    beschrijving: 'Lig op je rug met knieën gebogen. Strek je rechterbeen omhoog. Span je bilspieren aan en duw je heupen omhoog via je linkerhiel. Houd je heupen level — niet laten kantelen. Laat langzaam zakken. Doe alle herhalingen op één been voor je wisselt.',
    tips: ['Houd heupen level — niet kantelen', 'Duw omhoog via de hiel', 'Span bilspieren écht aan bovenin', 'Gestrekt been parallel aan de grond'],
    fouten: ['Heupen kantelen naar de zijkant', 'Rug hol trekken', 'Te snel zakken'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'wall-sit-march',
    naam: 'Wall Sit March',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'core'],
    coachDoelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '10 per been',
    uitleg: 'Houd een wall sit positie en til afwisselend één knie op. Combineert quadriceps kracht met core stabiliteit.',
    beschrijving: 'Ga in een wall sit positie — rug tegen de muur, knieën op 90 graden. Til langzaam je rechtervoet van de grond en houd je knie in een hoek van 90 graden. Zet neer en wissel. Houd de wall sit positie actief tijdens de hele oefening.',
    tips: ['Houd de wall sit positie stabiel', 'Til de knie gecontroleerd op', 'Adem rustig door', 'Houd je rug plat tegen de muur'],
    fouten: ['Wall sit positie verlaten', 'Te snel bewegen', 'Rug van de muur halen'],
    primaireSpieren: ['Quadriceps', 'Heupbuigers', 'Core'],
    secundaireSpieren: ['Bilspieren', 'Hamstrings'],
    herstel: false,
    mobiliteit: false,
  },

  // ── BILSPIEREN UITBREIDING ────────────────────────────────────────────────

  {
    id: 'hip-thrust',
    naam: 'Hip Thrust',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren'],
    coachDoelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '12-15',
    uitleg: 'Leun met je schouders op een bank. Voeten op de grond. Duw je heupen omhoog en span je bilspieren aan. Zwaardere variant van glute bridge.',
    beschrijving: 'Ga zitten voor een bank met je rug er tegenaan. Leun achterover totdat je schouderbladen op de rand van de bank rusten. Voeten plat op de grond, heupbreedte. Duw je heupen omhoog totdat je lichaam een rechte lijn vormt. Span je bilspieren maximaal aan bovenin. Laat langzaam zakken.',
    tips: ['Kin naar je borst — niet achterover hangen', 'Bilspieren maximaal aanspannen bovenin', 'Voeten plat op de grond', 'Houd je core actief'],
    fouten: ['Hoofd achterover hangen', 'Rug hol trekken', 'Knieën naar binnen zakken', 'Bilspieren niet aanspannen'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Quadriceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'donkey-kick',
    naam: 'Donkey Kick',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '15 per been',
    uitleg: 'Op handen en knieën. Schop je been omhoog terwijl je knie gebogen blijft. Span bilspieren aan bovenin.',
    beschrijving: 'Begin op handen en knieën. Houd je knie gebogen in een hoek van 90 graden. Til je rechterbeen omhoog door je heup te strekken — schop je hiel richting het plafond. Span je bilspieren aan bovenin. Laat langzaam zakken zonder je knie op de grond te zetten. Doe alle herhalingen op één been.',
    tips: ['Knie blijft gebogen op 90 graden', 'Span bilspieren aan bovenin', 'Houd je rug recht — niet hol trekken', 'Heupen level houden — niet roteren'],
    fouten: ['Rug hol trekken bij het optillen', 'Heupen roteren', 'Been te laag brengen'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: true,
    mobiliteit: false,
  },
  {
    id: 'fire-hydrant',
    naam: 'Fire Hydrant',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '15 per been',
    uitleg: 'Op handen en knieën. Til je been zijwaarts omhoog met gebogen knie — als een hond bij een brandkraan.',
    beschrijving: 'Begin op handen en knieën. Houd je knie gebogen. Til je rechterbeen zijwaarts omhoog tot heupniveau — houd je knie gebogen en je voet parallel aan de grond. Span je heupabductoren en bilspieren aan. Laat langzaam zakken. Doe alle herhalingen op één been.',
    tips: ['Til tot heupniveau', 'Houd je rug recht', 'Beweeg langzaam en gecontroleerd', 'Heupen level houden'],
    fouten: ['Rug hol trekken', 'Heupen roteren', 'Te snel bewegen'],
    primaireSpieren: ['Heupabductoren', 'Bilspieren'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: true,
    mobiliteit: false,
  },
  {
    id: 'clamshell',
    naam: 'Clamshell',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '15 per kant',
    uitleg: 'Lig op je zij met knieën gebogen. Open je bovenste knie als een schelp terwijl je voeten bij elkaar blijven.',
    beschrijving: 'Ga op je rechterzij liggen met heupen en knieën gebogen in een hoek van 45 graden. Voeten op elkaar. Houd je heupen stabiel. Til je bovenste knie omhoog als een schelp die opengaat — voeten blijven bij elkaar. Span je bilspieren aan bovenin. Laat langzaam zakken.',
    tips: ['Voeten blijven op elkaar', 'Heupen bewegen niet mee', 'Span bilspieren aan bovenin', 'Beweeg langzaam'],
    fouten: ['Heupen naar achteren roteren', 'Voeten van elkaar bewegen', 'Te kleine beweging maken'],
    primaireSpieren: ['Heupabductoren', 'Bilspieren', 'Piriformis'],
    secundaireSpieren: ['Core'],
    herstel: true,
    mobiliteit: false,
  },
  {
    id: 'frog-pump',
    naam: 'Frog Pump',
    categorie: 'Kracht',
    lichaamsdelen: ['bilspieren'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '20-25',
    uitleg: 'Lig op je rug met voetzolen tegen elkaar gedrukt. Duw je heupen omhoog en span je bilspieren aan.',
    beschrijving: 'Lig op je rug. Breng je voetzolen tegen elkaar en laat je knieën naar de zijkanten zakken — als een kikker. Duw je heupen omhoog terwijl je je bilspieren maximalh aanspant. Houd 1 seconde vast bovenin. Laat langzaam zakken.',
    tips: ['Voetzolen blijven tegen elkaar', 'Bilspieren maximaal aanspannen bovenin', 'Kleine maar gecontroleerde beweging', 'Adem uit bij het omhoog gaan'],
    fouten: ['Bilspieren niet aanspannen', 'Te snel pompen', 'Rug hol trekken'],
    primaireSpieren: ['Bilspieren'],
    secundaireSpieren: ['Heupabductoren', 'Hamstrings'],
    herstel: true,
    mobiliteit: false,
  },

  // ── CORE UITBREIDING ──────────────────────────────────────────────────────

  {
    id: 'hollow-hold',
    naam: 'Hollow Hold',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'gemiddeld',
    duur: 20,
    uitleg: 'Lig op je rug. Til je schouders en benen licht van de grond. Druk je onderrug in de mat. Houd de positie vast.',
    beschrijving: 'Lig op je rug. Strek je armen boven je hoofd. Druk je onderrug actief in de mat. Til je schouders en benen tegelijk licht van de grond — zo laag mogelijk terwijl je onderrug op de mat blijft. Houd de positie vast.',
    tips: ['Onderrug blijft op de mat — dit is cruciaal', 'Benen zo laag mogelijk zonder de rug te verliezen', 'Span je core actief aan', 'Adem rustig door'],
    fouten: ['Onderrug van de mat laten komen', 'Benen te hoog', 'Adem inhouden'],
    primaireSpieren: ['Core', 'Transversus abdominis', 'Rectus abdominis'],
    secundaireSpieren: ['Heupbuigers', 'Schouders'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'leg-raise',
    naam: 'Beenheffen',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10-15',
    uitleg: 'Lig op je rug met benen gestrekt. Til je benen naar 90 graden. Laat langzaam zakken zonder de grond te raken.',
    beschrijving: 'Lig op je rug met gestrekte benen. Leg je handen onder je billen voor ondersteuning. Span je core aan en til beide benen tegelijk omhoog naar 90 graden. Laat langzaam zakken tot net boven de grond. Raak de grond niet en til weer op.',
    tips: ['Druk je onderrug in de mat bij het zakken', 'Beweeg langzaam en gecontroleerd', 'Handen onder billen voor steun', 'Raak de grond niet onderaan'],
    fouten: ['Onderrug optillen van de mat', 'Te snel zakken', 'Knieën buigen'],
    primaireSpieren: ['Heupbuigers', 'Rectus abdominis'],
    secundaireSpieren: ['Core', 'Quadriceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'v-up',
    naam: 'V-Up',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10-12',
    uitleg: 'Lig op je rug met armen en benen gestrekt. Kom tegelijk omhoog met armen en benen om een V te vormen. Raak je voeten aan.',
    beschrijving: 'Lig plat op je rug met armen gestrekt boven je hoofd en benen gestrekt. Kom tegelijk omhoog met je bovenlichaam en benen — zoek met je handen naar je voeten. Je lichaam vormt een V op het hoogste punt. Laat gecontroleerd zakken.',
    tips: ['Beweeg armen en benen tegelijk', 'Houd benen gestrekt', 'Beweeg explosief omhoog en gecontroleerd omlaag', 'Adem uit bij het omhoog komen'],
    fouten: ['Armen en benen niet tegelijk', 'Knieën buigen', 'Te snel zakken'],
    primaireSpieren: ['Rectus abdominis', 'Heupbuigers'],
    secundaireSpieren: ['Core', 'Quadriceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'bicycle-crunch',
    naam: 'Bicycle Crunch',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'beginner',
    herhalingen: '15 per kant',
    uitleg: 'Lig op je rug, handen achter je hoofd. Breng je elleboog naar de tegenovergestelde knie terwijl je dat been naar je toe trekt.',
    beschrijving: 'Lig op je rug met handen licht achter je hoofd. Til je schouders licht van de grond. Breng je rechterelleboog naar je linkerknie terwijl je je linker knie naar je toe trekt en je rechtervoet uitstrekt. Wissel vloeiend van kant als het trappen op een fiets.',
    tips: ['Beweeg langzaam en gecontroleerd — geen rukken', 'Roteer vanuit de romp — niet de nek', 'Houd je ellebogen wijd', 'Strek het andere been volledig uit'],
    fouten: ['Nek naar voren trekken', 'Te snel bewegen', 'Ellebogen naar voren drukken'],
    primaireSpieren: ['Obliques', 'Rectus abdominis'],
    secundaireSpieren: ['Heupbuigers', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'russian-twist',
    naam: 'Russian Twist',
    categorie: 'Core',
    lichaamsdelen: ['core'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'beginner',
    herhalingen: '15 per kant',
    uitleg: 'Zit met knieën gebogen en romp achterover. Roteer je romp van links naar rechts. Handen voor je borst.',
    beschrijving: 'Ga zitten met knieën gebogen en voeten licht van de grond. Leun je romp achterover tot ongeveer 45 graden. Houd je handen voor je borst of gestrekt. Roteer je romp naar rechts, terug naar het midden, dan naar links. Dat is één herhaling.',
    tips: ['Roteer vanuit je romp — niet alleen je armen', 'Houd je borst omhoog', 'Voeten kunnen op de grond blijven voor beginners', 'Adem uit bij elke rotatie'],
    fouten: ['Alleen armen bewegen', 'Romp te ver achterover', 'Schouders intrekken'],
    primaireSpieren: ['Obliques', 'Core'],
    secundaireSpieren: ['Heupbuigers', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },

  // ── BORST UITBREIDING ─────────────────────────────────────────────────────

  {
    id: 'wide-push-up',
    naam: 'Wide Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['borst', 'schouders'],
    coachDoelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '8-12',
    uitleg: 'Zelfde als een push-up maar met handen breder dan schouderbreedte. Meer nadruk op buitenkant borst.',
    beschrijving: 'Begin in een plankpositie met handen breder dan twee keer schouderbreedte. Houd je lichaam in een rechte lijn. Laat je borst zakken naar de grond terwijl je je ellebogen naar de zijkanten opent. Druk omhoog.',
    tips: ['Ellebogen gaan wijd naar de zijkanten', 'Lichaam recht als een plank', 'Borst raakt bijna de grond', 'Span core en billen aan'],
    fouten: ['Heupen zakken', 'Onvoldoende diepte', 'Ellebogen niet wijd genoeg'],
    primaireSpieren: ['Buitenkant borstspieren', 'Schouders'],
    secundaireSpieren: ['Triceps', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'diamond-push-up',
    naam: 'Diamond Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['borst', 'schouders'],
    coachDoelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '6-10',
    uitleg: 'Handen dicht bij elkaar in een diamantvorm. Push-up uitvoeren. Traint primair de triceps.',
    beschrijving: 'Begin in een plankpositie. Breng je handen dicht bij elkaar direct onder je borst — wijs- en duimvingers vormen een driehoek of diamant. Laat je borst zakken naar je handen. Druk omhoog. De ellebogen gaan recht naar achteren.',
    tips: ['Ellebogen gaan naar achteren — niet naar de zijkant', 'Houd het lichaam recht', 'Borst raakt bijna de handen', 'Moeilijker dan een normale push-up — maak het niet te zwaar'],
    fouten: ['Ellebogen naar de zijkant openen', 'Heupen zakken', 'Handen te ver van elkaar'],
    primaireSpieren: ['Triceps', 'Binnenkant borstspieren'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'decline-push-up',
    naam: 'Decline Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['borst', 'schouders'],
    coachDoelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '8-12',
    uitleg: 'Voeten op een verhoogd oppervlak. Push-up uitvoeren. Traint de bovenkant van de borstspieren en schouders.',
    beschrijving: 'Zet je voeten op een bank of stoel. Handen op de grond iets breder dan schouderbreedte. Houd je lichaam in een rechte lijn. Laat je borst zakken naar de grond. Druk omhoog. Hoe hoger je voeten, hoe meer nadruk op de bovenkant van je borst.',
    tips: ['Houd lichaam recht — niet hangende heupen', 'Borst raakt bijna de grond', 'Ellebogen op 45 graden', 'Houd je core actief'],
    fouten: ['Heupen zakken', 'Onvoldoende diepte', 'Voeten te hoog voor beginners'],
    primaireSpieren: ['Bovenkant borstspieren', 'Schouders'],
    secundaireSpieren: ['Triceps', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'knee-push-up',
    naam: 'Knie Push-Up',
    categorie: 'Kracht',
    lichaamsdelen: ['borst', 'schouders'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '10-15',
    uitleg: 'Push-up op de knieën in plaats van de tenen. Makkelijker dan een gewone push-up. Goed voor beginners.',
    beschrijving: 'Begin op handen en knieën. Handen iets breder dan schouderbreedte. Houd je lichaam in een rechte lijn van hoofd tot knieën. Laat je borst zakken naar de grond. Druk omhoog. Houd je heupen in lijn — niet omhoog steken.',
    tips: ['Houd je lichaam recht van hoofd tot knieën', 'Borst raakt bijna de grond', 'Ellebogen op 45 graden', 'Core actief houden'],
    fouten: ['Heupen omhoog steken', 'Onvoldoende diepte', 'Ellebogen te wijd'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: false,
    mobiliteit: false,
  },

  // ── RUG UITBREIDING ───────────────────────────────────────────────────────

  {
    id: 'swimmer',
    naam: 'Swimmer',
    categorie: 'Kracht',
    lichaamsdelen: ['rug', 'bilspieren'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '20 totaal',
    uitleg: 'Lig op je buik. Beweeg afwisselend je rechterarm en linkerbeen omhoog, dan links en rechts. Als een zwemmer.',
    beschrijving: 'Lig op je buik met armen gestrekt voor je. Til tegelijk je rechterarm en linkerbeen van de grond. Laat zakken en wissel direct naar je linkerarm en rechterbeen. Beweeg vloeiend en snel — als een crawlbeweging. Houd je hoofd in lijn met je wervelkolom.',
    tips: ['Beweeg vloeiend en ritmisch', 'Houd hoofd in lijn — niet omhoog steken', 'Span je rug en bilspieren aan', 'Til zo hoog als comfortabel is'],
    fouten: ['Hoofd te ver omhoog', 'Schokkerige bewegingen', 'Niet afwisselen'],
    primaireSpieren: ['Rugspieren', 'Bilspieren'],
    secundaireSpieren: ['Schouders', 'Hamstrings'],
    herstel: true,
    mobiliteit: false,
  },
  {
    id: 'cobra-hold',
    naam: 'Cobra Hold',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['rug'],
    coachDoelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Lig op je buik. Duw je bovenlichaam omhoog met je handen terwijl je heupen op de grond blijven. Houd de positie vast.',
    beschrijving: 'Lig op je buik met handen naast je schouders. Duw je bovenlichaam langzaam omhoog door je armen te strekken. Houd je heupen op de grond. Kijk naar voren of licht omhoog. Span je rugspieren aan. Houd de positie vast en voel de stretch in je buik en onderrug.',
    tips: ['Heupen blijven op de grond', 'Spanning in de rugspieren — niet alleen armen', 'Schouders omlaag en achteren', 'Adem diep in de stretch'],
    fouten: ['Heupen van de grond tillen', 'Schouders optrekken', 'Nek te ver achterover'],
    primaireSpieren: ['Rugspieren', 'Erector spinae'],
    secundaireSpieren: ['Buikspieren (stretch)', 'Schouders'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'reverse-snow-angel',
    naam: 'Reverse Snow Angel',
    categorie: 'Kracht',
    lichaamsdelen: ['rug', 'schouders'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '10-12',
    uitleg: 'Lig op je buik met armen langs je lichaam. Beweeg je armen van je zij naar boven je hoofd terwijl je ze van de grond houdt.',
    beschrijving: 'Lig op je buik met armen langs je lichaam, handpalmen naar de grond. Til je armen licht van de grond. Beweeg je armen langzaam in een grote boog omhoog richting je hoofd — als een sneeuwengel maar op je buik. Beweeg terug. Houd je armen de hele tijd boven de grond.',
    tips: ['Houd armen van de grond gedurende de hele beweging', 'Beweeg langzaam en gecontroleerd', 'Span je schouderbladen samen', 'Houd hoofd in lijn'],
    fouten: ['Armen op de grond laten rusten', 'Te snel bewegen', 'Schouders optrekken'],
    primaireSpieren: ['Rug', 'Trapezius', 'Rhomboids'],
    secundaireSpieren: ['Schouders', 'Bilspieren'],
    herstel: true,
    mobiliteit: false,
  },

  // ── MOBILITEIT UITBREIDING ────────────────────────────────────────────────

  {
    id: 'pigeon-stretch',
    naam: 'Pigeon Stretch',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['bilspieren', 'benen'],
    coachDoelen: ['mobiliteit', 'herstel'],
    niveau: 'gemiddeld',
    duur: 60,
    uitleg: 'Vanuit een plank: breng je voorste knie naar buiten. Leg het been diagonaal neer. Leun naar voren over het gebogen been.',
    beschrijving: 'Begin in een plankpositie. Breng je rechterknie naar je rechterhand. Leg je onderbeen diagonaal op de grond. Strek je linkerbeen achter je. Laat je heupen zakken naar de grond. Leun naar voren over je rechterbeen en rust op je onderarmen of voorhoofd. Houd de stretch vast.',
    tips: ['Houd je heupen zo level mogelijk', 'Gebruik een kussen onder je heup als nodig', 'Leun verder naar voren voor een diepere stretch', 'Adem diep in de stretch'],
    fouten: ['Heupen roteren naar één kant', 'Te ver naar voren leunen voor het bereik', 'Spanning vasthouden'],
    primaireSpieren: ['Bilspieren', 'Piriformis', 'Heuprotatoren'],
    secundaireSpieren: ['Heupbuigers', 'Hamstrings'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'thread-the-needle',
    naam: 'Thread the Needle',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['rug', 'schouders'],
    coachDoelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    herhalingen: '8 per kant',
    uitleg: 'Op handen en knieën. Schuif één arm onder je lichaam door terwijl je roteert. Volg met je blik. Roteer de borstwervelkolom.',
    beschrijving: 'Begin op handen en knieën. Til je rechterarm op. Schuif hem onder je lichaam door naar links — alsof je een naald inrijgt. Laat je rechterschouder en rechterwang op de grond rusten. Voel de rotatie in je borstwervelkolom. Kom terug en wissel.',
    tips: ['Beweeg langzaam en voel de rotatie', 'Ondersteunende arm blijft gestrekt', 'Laat de schouder echt zakken', 'Adem diep in de rotatie'],
    fouten: ['Te snel bewegen', 'Ondersteunende arm niet gestrekt', 'Heupen mee laten draaien'],
    primaireSpieren: ['Thoracale wervelkolom', 'Rug'],
    secundaireSpieren: ['Schouders', 'Nekspieren'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'hamstring-stretch',
    naam: 'Hamstring Stretch',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['benen'],
    coachDoelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    duur: 45,
    uitleg: 'Lig op je rug. Trek één been naar je toe met je handen of een handdoek. Houd het been zo gestrekt mogelijk.',
    beschrijving: 'Lig op je rug. Buig je rechterknie en omvat je dijbeen of kuit met beide handen. Strek je been langzaam zo recht mogelijk omhoog. Houd de stretch vast. Je linkervoet kan plat op de grond blijven. Wissel van been.',
    tips: ['Houd het andere been ontspannen op de grond', 'Strek het been zo ver als comfortabel is', 'Adem diep in de stretch', 'Gebruik een handdoek of riem als je been niet ver genoeg reikt'],
    fouten: ['Onderrug van de grond tillen', 'Te hard trekken', 'Nek aanspannen'],
    primaireSpieren: ['Hamstrings'],
    secundaireSpieren: ['Kuitspieren', 'Rugspieren'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'quad-stretch',
    naam: 'Quadriceps Stretch',
    categorie: 'Mobiliteit',
    lichaamsdelen: ['benen'],
    coachDoelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    duur: 45,
    uitleg: 'Sta op één been. Trek je andere been achterwaarts omhoog. Houd je enkel vast. Voel de stretch aan de voorkant van je dij.',
    beschrijving: 'Sta rechtop, gebruik een muur voor balans indien nodig. Buig je rechterknie en trek je rechtervoet omhoog naar je billen. Houd je enkel vast met je rechterhand. Houd je knieën dicht bij elkaar. Voel de stretch aan de voorkant van je rechterdij. Wissel van been.',
    tips: ['Houd knieën bij elkaar', 'Sta rechtop — niet naar voren leunen', 'Duw je enkel actief naar je billen', 'Gebruik een muur voor balans'],
    fouten: ['Knieën uit elkaar laten gaan', 'Naar voren leunen', 'Enkel niet ver genoeg omhoog'],
    primaireSpieren: ['Quadriceps', 'Heupbuigers'],
    secundaireSpieren: ['Knie'],
    herstel: true,
    mobiliteit: true,
  },

  // ── CONDITIE UITBREIDING ──────────────────────────────────────────────────

  {
    id: 'burpee',
    naam: 'Burpee',
    categorie: 'Conditie',
    lichaamsdelen: ['volledig'],
    coachDoelen: ['conditie'],
    niveau: 'gemiddeld',
    herhalingen: '8-12',
    uitleg: 'Zak naar een squat, spring je benen naar een plank, doe een push-up, spring terug, spring omhoog. Volledig lichaam.',
    beschrijving: 'Begin staand. Zak naar een squat en plaats je handen op de grond. Spring je benen naar achteren naar een plankpositie. Doe een push-up (optioneel). Spring je benen terug naar je handen. Spring omhoog met je armen boven je hoofd. Land zacht en herhaal.',
    tips: ['Houd een consistent tempo', 'Land zacht bij de terugsprong', 'Houd je core actief in de plank', 'Pas aan op je niveau — laat de push-up weg als nodig'],
    fouten: ['Heupen zakken in de plank', 'Hard landen', 'Te snel worden waardoor techniek lijdt'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Schouders', 'Benen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'butt-kicks',
    naam: 'Butt Kicks',
    categorie: 'Warmup',
    lichaamsdelen: ['benen'],
    coachDoelen: ['warmup', 'conditie'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Loop op de plaats en breng je hielen afwisselend naar je billen. Houd een snel tempo.',
    beschrijving: 'Sta rechtop. Beweeg alsof je op de plaats loopt maar breng je hielen omhoog naar je billen bij elke stap. Houd je knieën naar beneden gericht. Swing je armen mee als bij het lopen. Houd een snel en consistent tempo.',
    tips: ['Breng hielen echt naar je billen', 'Houd je knieën laag — naar beneden', 'Swing armen actief mee', 'Land op de bal van je voet'],
    fouten: ['Knieën omhoog brengen in plaats van hielen naar achteren', 'Te langzaam', 'Armen niet meebewegen'],
    primaireSpieren: ['Hamstrings', 'Kuitspieren'],
    secundaireSpieren: ['Heupbuigers', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'skater-jump',
    naam: 'Skater Jump',
    categorie: 'Conditie',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['conditie'],
    niveau: 'gemiddeld',
    herhalingen: '10 per kant',
    uitleg: 'Spring zijwaarts van één been naar het andere. Land op één been en zwaai het andere been achter je. Als een schaatser.',
    beschrijving: 'Begin op je rechterbeen. Spring zijwaarts naar links en land op je linkerbeen. Zwaai je rechterbeen achter je linkerbeen terwijl je balanceert. Spring terug naar rechts. Houd een vloeiend, ritmisch patroon. Buig je knie bij de landing.',
    tips: ['Land zacht op één been', 'Zwaai het andere been achter je', 'Gebruik je armen voor balans en momentum', 'Houd je borst omhoog'],
    fouten: ['Te hard landen', 'Knie naar binnen bij landing', 'Niet ver genoeg springen'],
    primaireSpieren: ['Bilspieren', 'Quadriceps', 'Heupabductoren'],
    secundaireSpieren: ['Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'lateral-shuffle',
    naam: 'Zijwaartse Shuffle',
    categorie: 'Conditie',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['conditie', 'warmup'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Sta in een atletische houding. Shuffle snel zijwaarts naar rechts en dan naar links. Houd je heupen laag.',
    beschrijving: 'Sta met voeten op schouderbreedte in een lichte squat-positie. Shuffle snel 3-4 stappen naar rechts door je voeten samen te brengen en dan te spreiden. Shuffle terug naar links. Houd je heupen laag en je gewicht op de ballen van je voeten.',
    tips: ['Houd heupen laag — blijf in een athletische houding', 'Land op de ballen van je voeten', 'Houd een snel tempo', 'Kruis je voeten niet'],
    fouten: ['Rechtop staan', 'Voeten kruisen', 'Hielen hard neerzetten'],
    primaireSpieren: ['Bilspieren', 'Heupabductoren', 'Quadriceps'],
    secundaireSpieren: ['Kuitspieren', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'plank-jack',
    naam: 'Plank Jack',
    categorie: 'Conditie',
    lichaamsdelen: ['core', 'benen'],
    coachDoelen: ['conditie', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '15-20',
    uitleg: 'Begin in een plankpositie. Spring je benen tegelijk wijd uit en terug. Houd je heupen stabiel.',
    beschrijving: 'Begin in een hoge plankpositie met voeten samen. Spring beide benen tegelijk wijd uit naar de zijkant. Spring ze terug samen. Houd je heupen laag en je core actief gedurende de hele beweging.',
    tips: ['Houd heupen laag en stabiel', 'Handen stevig op de grond', 'Span je core aan', 'Houd een consistent tempo'],
    fouten: ['Heupen omhoog steken bij het springen', 'Armen buigen', 'Core niet actief'],
    primaireSpieren: ['Core', 'Heupabductoren', 'Schouders'],
    secundaireSpieren: ['Borst', 'Benen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'squat-hold',
    naam: 'Squat Hold',
    categorie: 'Kracht',
    lichaamsdelen: ['benen', 'bilspieren'],
    coachDoelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    duur: 45,
    uitleg: 'Zak in een squat en houd de positie vast. Minder intensief dan een wall sit maar traint mobiliteit en kracht tegelijk.',
    beschrijving: 'Sta met voeten op schouderbreedte, tenen licht naar buiten. Zak in een squat totdat je dijen parallel zijn aan de grond. Houd je borst omhoog en je gewicht in je hielen. Houd de positie vast gedurende de ingestelde tijd.',
    tips: ['Borst omhoog houden', 'Knieën volgen de richting van de tenen', 'Adem rustig door', 'Houd het gewicht verdeeld over de hele voet'],
    fouten: ['Borst naar voren vallen', 'Knieën naar binnen zakken', 'Hielen optillen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'good-morning',
    naam: 'Good Morning',
    categorie: 'Kracht',
    lichaamsdelen: ['rug', 'benen'],
    coachDoelen: ['kracht', 'mobiliteit'],
    niveau: 'beginner',
    herhalingen: '12-15',
    uitleg: 'Sta rechtop. Handen achter je hoofd. Buig naar voren vanuit je heupen terwijl je rug recht blijft. Kom omhoog.',
    beschrijving: 'Sta met voeten op schouderbreedte. Leg je handen achter je hoofd. Buig langzaam naar voren vanuit je heupen — niet vanuit je rug. Houd je rug recht en je knieën licht gebogen. Ga totdat je romp bijna parallel is aan de grond. Kom omhoog.',
    tips: ['Beweeg vanuit de heupen — niet de rug', 'Houd je rug recht gedurende de hele beweging', 'Knieën licht gebogen', 'Beweeg langzaam en gecontroleerd'],
    fouten: ['Rug bol trekken', 'Knieën te ver buigen', 'Te snel bewegen'],
    primaireSpieren: ['Hamstrings', 'Rugspieren', 'Bilspieren'],
    secundaireSpieren: ['Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'shoulder-tap',
    naam: 'Shoulder Tap',
    categorie: 'Core',
    lichaamsdelen: ['core', 'schouders'],
    coachDoelen: ['core', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10 per kant',
    uitleg: 'In een plankpositie: tik afwisselend je tegenovergestelde schouder aan. Houd je heupen stabiel en draai niet.',
    beschrijving: 'Begin in een hoge plankpositie. Til je rechterhand op en tik je linkerschouder aan. Zet je hand terug. Wissel naar links. Houd je heupen zo stabiel mogelijk — minimale rotatie. Span je core actief aan bij elke tik.',
    tips: ['Houd heupen stabiel — minimale rotatie', 'Span core actief aan bij elke tik', 'Beweeg langzaam voor meer stabiliteit', 'Voeten iets wijder dan normaal voor meer stabiliteit'],
    fouten: ['Heupen sterk roteren bij elke tik', 'Te snel bewegen', 'Core niet actief'],
    primaireSpieren: ['Core', 'Obliques', 'Schouders'],
    secundaireSpieren: ['Borst', 'Triceps'],
    herstel: false,
    mobiliteit: false,
  },
]

// Voeg fase 2 toe aan de hoofdlijst
BODYWEIGHT_OEFENINGEN.push(...fase2Oefeningen)
