// ── CoachOS Kettlebell Bibliotheek — Volledig (100 oefeningen) ───────────────
// Architectuur identiek aan bodyweight-exercises.ts en strength-exercises.ts:
// Coach bepaalt doel + niveau → route filtert → Trainer AI assembleert.
// Trainer AI mag GEEN nieuwe oefeningen verzinnen buiten de gefilterde lijst.

export type KettlebellDoel =
  | 'kracht'
  | 'conditie'
  | 'herstel'
  | 'mobiliteit'
  | 'warmup'
  | 'ballistisch'
  | 'core'

export type KettlebellNiveau = 'beginner' | 'gemiddeld' | 'gevorderd'

export type KettlebellCategorie =
  | 'hinge'
  | 'squat'
  | 'push'
  | 'pull'
  | 'ballistisch'
  | 'carry'
  | 'core'
  | 'mobiliteit'
  | 'conditie'
  | 'complex'

export type KettlebellLichaamsdeel =
  | 'benen'
  | 'billen'
  | 'rug'
  | 'borst'
  | 'schouders'
  | 'armen'
  | 'core'
  | 'fullbody'

export interface KettlebellOefening {
  id: string
  naam: string
  categorie: KettlebellCategorie
  lichaamsdelen: KettlebellLichaamsdeel[]
  doelen: KettlebellDoel[]
  niveau: KettlebellNiveau
  herhalingen?: string
  duur?: number
  uitleg: string
  beschrijving: string
  tips: string[]
  fouten: string[]
  primaireSpieren: string[]
  secundaireSpieren: string[]
  herstel: boolean
  mobiliteit: boolean
  illustratie?: string
}

export const KETTLEBELL_OEFENINGEN: KettlebellOefening[] = [

  // ── HINGE (12) ────────────────────────────────────────────────────────────

  {
    id: 'kb-deadlift',
    naam: 'Kettlebell Deadlift',
    illustratie: 'kettlebell-deadlift.png',
    categorie: 'hinge',
    lichaamsdelen: ['benen', 'billen', 'rug'],
    doelen: ['kracht', 'warmup'],
    niveau: 'beginner',
    herhalingen: '8-12',
    uitleg: 'Kettlebell op de grond. Hinge vanuit de heupen, rug recht. Trek omhoog via bilspieren. Basis van alle kettlebell oefeningen.',
    beschrijving: 'Sta met voeten op heupbreedte, kettlebell tussen je voeten. Hinge naar voren vanuit je heupen — rug recht, lichte knibuiging. Pak de kettlebell met beide handen. Span je core en bilspieren aan en sta rechtop. Zet de kettlebell terug via dezelfde hinge beweging.',
    tips: ['Rug recht gedurende de hele beweging', 'Hinge vanuit de heupen — niet de rug', 'Bilspieren aanspannen bovenin', 'Kettlebell dicht bij het lichaam'],
    fouten: ['Rug afronden', 'Squat beweging in plaats van hinge', 'Kettlebell te ver voor de voeten'],
    primaireSpieren: ['Hamstrings', 'Bilspieren', 'Rugspieren'],
    secundaireSpieren: ['Core', 'Quadriceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-sumo-deadlift',
    naam: 'Sumo Deadlift',
    illustratie: 'sumo-deadlift.png',
    categorie: 'hinge',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '8-12',
    uitleg: 'Brede stand, tenen naar buiten, kettlebell tussen de benen. Zak dieper dan bij een normale deadlift. Meer bilspieren en binnenkant dij.',
    beschrijving: 'Sta met voeten twee keer schouderbreedte uit elkaar, tenen naar buiten. Kettlebell tussen je voeten. Zak dieper dan bij een normale deadlift — heupen lager. Trek omhoog terwijl je knieën naar buiten duwt. Bilspieren aanspannen bovenin.',
    tips: ['Knieën volgen de richting van de tenen', 'Rug recht', 'Bilspieren aanspannen bovenin', 'Kettlebell tussen de benen'],
    fouten: ['Knieën naar binnen zakken', 'Rug afronden', 'Te smal beginnen'],
    primaireSpieren: ['Bilspieren', 'Binnenkant dij', 'Hamstrings'],
    secundaireSpieren: ['Quadriceps', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-single-arm-deadlift',
    naam: 'Single Arm Deadlift',
    illustratie: 'single-arm-deadlift.png',
    categorie: 'hinge',
    lichaamsdelen: ['benen', 'billen', 'rug', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '8-10 per arm',
    uitleg: 'Eénarmige deadlift met kettlebell. Heupen blijven level — geen rotatie. Traint core stabiliteit extra.',
    beschrijving: 'Kettlebell naast je rechtervoet. Hinge naar voren en pak de kettlebell met je rechterhand. Houd je heupen level — niet laten roteren. Trek omhoog terwijl je core actief houdt. Doe alle herhalingen op één arm voor je wisselt.',
    tips: ['Heupen level houden — geen rotatie', 'Core actief aanspannen', 'Rug recht', 'Vrijehand kan voor balans gebruikt worden'],
    fouten: ['Heupen roteren naar de kettlebell kant', 'Rug afronden', 'Te snel'],
    primaireSpieren: ['Hamstrings', 'Bilspieren', 'Core', 'Obliques'],
    secundaireSpieren: ['Rugspieren', 'Quadriceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-romanian-deadlift',
    naam: 'Romanian Deadlift',
    illustratie: 'romanian-deadlift.png',
    categorie: 'hinge',
    lichaamsdelen: ['benen', 'billen', 'rug'],
    doelen: ['kracht', 'herstel'],
    niveau: 'beginner',
    herhalingen: '10-12',
    uitleg: 'Kettlebell(s) voor de dijen. Buig vanuit de heupen, laat zakken langs de benen. Voel de hamstring stretch. Traint de hele achterkant.',
    beschrijving: 'Houd een of twee kettlebells voor je dijen. Buig naar voren vanuit de heupen — rug recht. Laat de kettlebells langs je benen zakken. Voel de stretch in de hamstrings. Stop als de rug wil afronden. Kom omhoog via bilspieren.',
    tips: ['Kettlebells dicht langs de benen', 'Rug recht — lichte curve', 'Bilspieren aanspannen bij omhoog', 'Stop bij maximale stretch'],
    fouten: ['Rug afronden onderaan', 'Knieën te veel buigen', 'Kettlebells te ver van het lichaam'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core'],
    herstel: true,
    mobiliteit: false,
  },
  {
    id: 'kb-staggered-deadlift',
    naam: 'Staggered Stance Deadlift',
    illustratie: 'staggered-stance-deadlift.png',
    categorie: 'hinge',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10 per kant',
    uitleg: 'Eén voet voor, één achter. Meeste gewicht op het voorste been. Eenzijdige hinge oefening voor balans en kracht.',
    beschrijving: 'Zet je rechtervoet voor je en je linkervoet licht naar achteren. Hinge naar voren met het meeste gewicht op het rechterlichaam. Kettlebell naast het rechtervoet. Trek omhoog via het rechterlichaam. Wissel na alle herhalingen.',
    tips: ['Meeste gewicht op het voorste been', 'Heupen level houden', 'Rug recht', 'Achterste been is alleen een steun'],
    fouten: ['Gewicht gelijk verdelen', 'Heupen roteren', 'Rug afronden'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-swing',
    naam: 'Kettlebell Swing',
    categorie: 'hinge',
    illustratie: 'kettlebell-swing.png',
    lichaamsdelen: ['billen', 'rug', 'fullbody'],
    doelen: ['kracht', 'conditie', 'ballistisch'],
    niveau: 'beginner',
    herhalingen: '15-20',
    uitleg: 'De fundamentele kettlebell oefening. Explosieve hinge — bilspieren drijven de swing. Traint kracht, conditie en explosiviteit tegelijk.',
    beschrijving: 'Sta met voeten iets breder dan schouderbreedte. Hinge naar voren en pak de kettlebell met beide handen. Trek de kettlebell terug tussen je benen. Drijf explosief via je bilspieren — de kettlebell zweeft tot borst/schouderhoogte. Laat terugzwaaien en herhaal.',
    tips: ['Bilspieren zijn de motor — niet de armen', 'Hinge — geen squat', 'Knijp je bilspieren bij de top', 'Laat de zwaartekracht helpen bij het terugzwaaien'],
    fouten: ['Squat beweging maken', 'Armen gebruiken om te liften', 'Rug afronden', 'Kettlebell te hoog bij Russian of te laag bij American'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Schouders', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-russian-swing',
    naam: 'Russian Swing',
    illustratie: 'russian-swing.png',
    categorie: 'hinge',
    lichaamsdelen: ['billen', 'rug'],
    doelen: ['kracht', 'conditie'],
    niveau: 'beginner',
    herhalingen: '15-20',
    uitleg: 'Swing waarbij de kettlebell tot schouderhoogte zweeft. Veiliger voor de schouders dan een American swing. Standaard in Europa.',
    beschrijving: 'Zelfde als de kettlebell swing maar de kettlebell zweeft maximaal tot schouderhoogte. De armen blijven parallel aan de grond op het hoogste punt. Bilspieren knijpen hard samen bij de top.',
    tips: ['Stop bij schouderhoogte', 'Armen parallel aan de grond bovenin', 'Bilspieren maximaal aanspannen', 'Adem uit bij de top'],
    fouten: ['Kettlebell hoger dan de schouders forceren', 'Squat beweging', 'Armen gebruiken als lift'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-american-swing',
    naam: 'American Swing',
    illustratie: 'american-swing.png',
    categorie: 'hinge',
    lichaamsdelen: ['billen', 'rug', 'schouders'],
    doelen: ['kracht', 'conditie', 'ballistisch'],
    niveau: 'gemiddeld',
    herhalingen: '12-15',
    uitleg: 'Swing waarbij de kettlebell volledig overhead zweeft. Meer schouderactivatie. Vereist goede schoudermobiliteit.',
    beschrijving: 'Zelfde als de Russian swing maar de kettlebell wordt explosief overhead gestuurd. De armen strekken volledig overhead op het hoogste punt. Vereist meer explosiviteit en goede schoudermobiliteit.',
    tips: ['Gebruik je bilspieren explosief voor de overhead positie', 'Goede schoudermobiliteit vereist', 'Strek volledig overhead', 'Begin met Russian swing als je minder ervaren bent'],
    fouten: ['Schouders optrekken overhead', 'Rug hol trekken bij overhead', 'Onvoldoende explosiviteit'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    secundaireSpieren: ['Core', 'Triceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-one-arm-swing',
    naam: 'One Arm Swing',
    illustratie: 'one-arm-swing.png',
    categorie: 'hinge',
    lichaamsdelen: ['billen', 'rug', 'core'],
    doelen: ['kracht', 'conditie', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '12-15 per arm',
    uitleg: 'Swing met één arm. Vereist meer core stabiliteit om rotatie te voorkomen. Traint eenzijdige kracht.',
    beschrijving: 'Zelfde beweging als de two-hand swing maar met één hand. De vrije hand kan langs het lichaam hangen of licht zijwaarts worden gehouden voor balans. Core actief aanspannen om heuprotatie te voorkomen.',
    tips: ['Core actief om rotatie te voorkomen', 'Vrije arm helpt met balans', 'Heupen blijven level', 'Wissel hands vlot'],
    fouten: ['Heupen roteren bij de swing', 'Core laten zakken', 'Arm gebruiken voor de lift'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Core', 'Obliques'],
    secundaireSpieren: ['Rugspieren', 'Schouders'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-hand-to-hand-swing',
    naam: 'Hand-to-Hand Swing',
    illustratie: 'hand-to-hand-swing.png',
    categorie: 'hinge',
    lichaamsdelen: ['billen', 'rug', 'core'],
    doelen: ['kracht', 'conditie', 'ballistisch'],
    niveau: 'gemiddeld',
    herhalingen: '10-15 per kant',
    uitleg: 'Swing waarbij je de kettlebell op het hoogste punt overpakt van de ene naar de andere hand. Coördinatie en grip.',
    beschrijving: 'Begin met een normale swing. Op het hoogste punt laat je de kettlebell los met de ene hand en pak je hem met de andere. Wissel elke swing of elke paar swings. Vereist goede timing en coördinatie.',
    tips: ['Pak de kettlebell op het hoogste punt — het lichtste moment', 'Houd een consistent swing ritme', 'Begin langzaam', 'Houd je ogen op de kettlebell'],
    fouten: ['Te vroeg of te laat wisselen', 'Inconsistent ritme', 'Te snel beginnen'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Core'],
    secundaireSpieren: ['Onderarmen', 'Schouders'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-double-swing',
    naam: 'Double Swing',
    illustratie: 'double-swing.png',
    categorie: 'hinge',
    lichaamsdelen: ['billen', 'rug'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gevorderd',
    herhalingen: '10-15',
    uitleg: 'Swing met twee kettlebells tegelijk. Dubbele belasting. Vereist goede techniek en twee kettlebells van gelijk gewicht.',
    beschrijving: 'Twee kettlebells tussen de voeten. Pak beide kettlebells. Swing beide tegelijk op — zelfde beweging als een normale swing maar met dubbele belasting. Vereist meer core stabiliteit.',
    tips: ['Gebruik gelijk gewicht kettlebells', 'Meer core activatie nodig', 'Bilspieren extra aanspannen', 'Begin met lichtere gewichten dan je normale swing'],
    fouten: ['Ongelijke swing hoogte', 'Core laten zakken', 'Te zwaar beginnen'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-alternating-swing',
    naam: 'Alternating Swing',
    illustratie: 'alternating-swing.png',
    categorie: 'hinge',
    lichaamsdelen: ['billen', 'rug', 'core'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '20 totaal',
    uitleg: 'Wissel elke swing van hand. Rechts, links, rechts, links. Vloeiende hand-to-hand wisseling in elk swingritme.',
    beschrijving: 'Begin met een normale swing met de rechterhand. Bij de top laat je de kettlebell los en pak je hem met de linkerhand. Swing terug en wissel weer. Houd een consistent, vloeiend ritme.',
    tips: ['Vloeiende, consistente wissel', 'Houd het ritme stabiel', 'Pak de kettlebell vroeg genoeg', 'Core actief voor stabiliteit'],
    fouten: ['Ritme verliezen bij het wisselen', 'Te laat pakken', 'Core laten zakken'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Core'],
    secundaireSpieren: ['Schouders', 'Onderarmen'],
    herstel: false,
    mobiliteit: false,
  },

  // ── SQUAT (14) ────────────────────────────────────────────────────────────

  {
    id: 'kb-goblet-squat',
    naam: 'Goblet Squat',
    illustratie: 'goblet-squat.png',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'warmup'],
    niveau: 'beginner',
    herhalingen: '10-15',
    uitleg: 'Kettlebell voor de borst houden. Diep squatten. Uitstekende squat voor beginners — de kettlebell helpt met het rechtop houden.',
    beschrijving: 'Houd de kettlebell bij de horns (zijkanten van de handel) voor je borst. Voeten op schouderbreedte, tenen licht naar buiten. Zak diep door de knieën. Gebruik je ellebogen om de knieën naar buiten te duwen in de bodem. Drijf omhoog via de hielen.',
    tips: ['Ellebogen duwen knieën naar buiten in de bodem', 'Borst omhoog houden', 'Zo diep mogelijk zakken', 'Kettlebell dicht bij het lichaam'],
    fouten: ['Borst naar voren vallen', 'Knieën naar binnen zakken', 'Onvoldoende diepte'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Bovenrug'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-front-squat',
    naam: 'Front Squat',
    illustratie: 'front-squat.png',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen', 'schouders'],
    doelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '8-10',
    uitleg: 'Kettlebell in rack positie op de schouder. Squat omlaag. Elleboog hoog. Traint quadriceps en vereist schouderstabiliteit.',
    beschrijving: 'Breng de kettlebell naar de rack positie — ruht op de onderarm, close bij het lichaam, elleboog omhoog. Squat omlaag terwijl je de rack positie behoudt. Elleboog blijft omhoog om de kettlebell stabiel te houden.',
    tips: ['Elleboog hoog houden', 'Kettlebell ruht op de onderarm — niet de hand', 'Borst omhoog', 'Core actief voor de rack positie'],
    fouten: ['Elleboog zakken', 'Kettlebell op de hand balanceren', 'Borst naar voren vallen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Schouders', 'Core', 'Bovenrug'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-double-front-squat',
    naam: 'Double Front Squat',
    illustratie: 'double-front-squat.png',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen', 'schouders'],
    doelen: ['kracht'],
    niveau: 'gevorderd',
    herhalingen: '5-8',
    uitleg: 'Twee kettlebells in rack positie. Zware squatvariant. Vereist goede rack positie techniek met beide armen.',
    beschrijving: 'Breng twee kettlebells naar de rack positie — één op elke schouder. Houd beide ellebogen hoog. Squat diep omlaag. Drijf omhoog via de hielen. De dubbele belasting maakt dit significant zwaarder.',
    tips: ['Beide ellebogen hoog', 'Bilspieren aanspannen bovenin', 'Adem in voor de squat', 'Begin met lichtere kettlebells dan verwacht'],
    fouten: ['Één elleboog laten zakken', 'Borst naar voren vallen', 'Te zwaar beginnen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-box-squat',
    naam: 'Box Squat',
    illustratie: 'box-squat.webp',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'warmup'],
    niveau: 'beginner',
    herhalingen: '10-12',
    uitleg: 'Squat naar een bank of doos. Raak licht aan en kom direct omhoog. Leert correcte diepte en techniek.',
    beschrijving: 'Zet een bank achter je. Houd de kettlebell voor je borst (goblet positie). Squat terug tot je billen de bank raken. Raak licht aan — ga niet volledig zitten. Drijf direct omhoog.',
    tips: ['Raak alleen licht aan', 'Houd spanning in de spieren', 'Borst omhoog', 'Gebruik als techniektraining'],
    fouten: ['Echt gaan zitten en ontspannen', 'Voorover vallen', 'Momentum gebruiken bij omhoog komen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-tempo-goblet-squat',
    naam: 'Tempo Goblet Squat',
    illustratie: 'tempo-goblet-squat.webp',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'mobiliteit', 'herstel'],
    niveau: 'beginner',
    herhalingen: '6-8',
    uitleg: 'Goblet squat met een langzaam tempo — 5 seconden omlaag. Traint mobiliteit en lichaamsbewustzijn.',
    beschrijving: 'Goblet squat waarbij je 5 seconden neemt om omlaag te zakken. Houd 2 seconden vast in de bodem. Kom in 1 seconde omhoog. Focus op positie en mobiliteit, niet op belasting.',
    tips: ['Tel de 5 seconden omlaag', 'Voel elke positie', 'Gebruik een lichte kettlebell', 'Focus op mobiliteit'],
    fouten: ['Te snel bewegen', 'Te zwaar gewicht', 'Positie niet bewust houden'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Enkels'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-pause-squat',
    naam: 'Pause Squat',
    illustratie: 'pause-squat.webp',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '5-8',
    uitleg: 'Squat met 2-3 seconden pauze in de bodem. Elimineert het stretch-reflex voordeel. Bouwt meer kracht.',
    beschrijving: 'Goblet of front squat waarbij je 2-3 seconden vasthoudt in de diepste positie. Houd spanning in de spieren — ga niet slap. Drijf daarna explosief omhoog.',
    tips: ['Houd spanning in de bodem — niet slap zakken', 'Adem niet uit in de bodem', 'Gebruik minder gewicht dan normaal', 'Tel de pauze bewust'],
    fouten: ['Ontspannen in de bodem', 'Te zwaar gewicht', 'Te korte pauze'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Core', 'Hamstrings'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-split-squat',
    naam: 'Split Squat',
    illustratie: 'split-squat.webp',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Gesplitste positie. Zak recht omlaag zonder voeten te verplaatsen. Eenzijdige beentraining.',
    beschrijving: 'Houd een kettlebell voor je borst of aan één zijde. Stap groot naar voren en houd die positie. Zak recht omlaag — achterste knie daalt richting de grond. Drijf omhoog. Doe alle herhalingen op één been.',
    tips: ['Romp recht — niet naar voren leunen', 'Voorste knie boven de enkel', 'Zak recht omlaag — niet naar voren', 'Bilspieren aanspannen bij omhoog'],
    fouten: ['Romp naar voren leunen', 'Voorste knie over de teen', 'Schouders optrekken'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-bulgarian-split-squat',
    naam: 'Bulgaarse Split Squat',
    illustratie: 'bulgaarse-split-squat.webp',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '8-10 per been',
    uitleg: 'Achterste voet op een bank. Zak door het voorste been. Intensieve eenzijdige beentraining.',
    beschrijving: 'Houd een of twee kettlebells. Zet je achterste voet op een bank. Voorste voet ver genoeg naar voren. Zak omlaag totdat je achterste knie bijna de grond raakt. Drijf omhoog via het voorste been.',
    tips: ['Voorste voet ver genoeg naar voren', 'Romp rechtop', 'Controleer de afdaling', 'Bilspieren aanspannen bovenin'],
    fouten: ['Voorste knie over de teen', 'Romp naar voren leunen', 'Te snel zakken'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-reverse-lunge',
    naam: 'Reverse Lunge',
    illustratie: 'reverse-lunge.webp',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'warmup'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Stap achterwaarts in een lunge. Minder kniebelasting dan een forward lunge. Goed voor beginners.',
    beschrijving: 'Houd een kettlebell in rack positie of voor de borst. Stap achterwaarts met je rechterbeen. Laat je rechterknee zakken naar de grond. Houd je romp recht. Drijf omhoog via het voorste been. Breng je been terug en wissel.',
    tips: ['Stap recht achterwaarts', 'Voorste knie boven de enkel', 'Romp rechtop', 'Bilspieren aanspannen bij omhoog'],
    fouten: ['Romp naar voren leunen', 'Voorste knie over de teen', 'Te kleine stap'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-forward-lunge',
    naam: 'Forward Lunge',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'conditie'],
    niveau: 'beginner',
    herhalingen: '10 per been',
    uitleg: 'Stap naar voren in een lunge. Meer uitdaging voor het evenwicht dan een reverse lunge.',
    beschrijving: 'Houd een kettlebell voor je borst of aan je zij. Stap groot naar voren met je rechterbeen. Laat je linkerknee zakken naar de grond. Drijf terug naar de startpositie. Wissel van been.',
    tips: ['Stap breed genoeg', 'Voorste knie boven de enkel', 'Land zacht op je voorste voet', 'Romp recht'],
    fouten: ['Te kleine stap', 'Romp naar voren', 'Knie naar binnen bij landing'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-walking-lunge',
    naam: 'Walking Lunge',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '10 per been',
    uitleg: 'Lunge waarbij je vooruit loopt — het achterste been stap direct naar voren voor de volgende lunge.',
    beschrijving: 'Houd kettlebells aan je zijkant. Stap groot naar voren in een lunge. Kom omhoog en stap direct door met het andere been naar voren. Wissel zo afwisselend terwijl je vooruit loopt.',
    tips: ['Breed genoeg stappen', 'Romp rechtop houden', 'Land zacht', 'Bilspieren aanspannen bij omhoog'],
    fouten: ['Te kleine stappen', 'Romp naar voren', 'Knieën naar binnen bij landing'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Kuitspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-lateral-lunge',
    naam: 'Lateral Lunge',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'mobiliteit'],
    niveau: 'beginner',
    herhalingen: '10 per kant',
    uitleg: 'Stap zijwaarts in een lunge. Traint binnenkant dij en bilspieren. Kettlebell voor de borst.',
    beschrijving: 'Houd de kettlebell voor je borst. Stap breed opzij met je rechterbeen. Zak door je rechterknie terwijl je linkervoet op de grond blijft en je linkerbeen gestrekt is. Drijf omhoog en breng je been terug. Wissel.',
    tips: ['Stap breed genoeg', 'Gebogen knie boven de enkel', 'Gestrekt been volledig gestrekt', 'Borst omhoog'],
    fouten: ['Te kleine stap', 'Knie naar binnen zakken', 'Romp naar voren'],
    primaireSpieren: ['Bilspieren', 'Binnenkant dij', 'Quadriceps'],
    secundaireSpieren: ['Hamstrings', 'Core'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-cossack-squat',
    naam: 'Cossack Squat',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['kracht', 'mobiliteit'],
    niveau: 'gemiddeld',
    herhalingen: '8 per kant',
    uitleg: 'Brede stand. Zak op één been terwijl het andere gestrekt blijft. Schuif van kant naar kant. Traint mobiliteit en kracht.',
    beschrijving: 'Sta breed met voeten wijd uit elkaar. Houd de kettlebell voor je borst. Zak naar rechts — buig je rechterknie en zak zo diep mogelijk. Je linkerbeen blijft gestrekt. Schuif naar links. Gebruik de kettlebell als tegengewicht.',
    tips: ['Houd borst omhoog', 'Gestrekt been zo recht mogelijk', 'Gebruik kettlebell als counterbalance', 'Beweeg vloeiend van kant naar kant'],
    fouten: ['Borst naar voren vallen', 'Gestrekte been buigen', 'Te snel'],
    primaireSpieren: ['Bilspieren', 'Quadriceps', 'Heupabductoren'],
    secundaireSpieren: ['Binnenkant dij', 'Core', 'Hamstrings'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-thruster',
    naam: 'Thruster',
    categorie: 'squat',
    lichaamsdelen: ['benen', 'billen', 'schouders'],
    doelen: ['kracht', 'conditie', 'ballistisch'],
    niveau: 'gemiddeld',
    herhalingen: '8-10',
    uitleg: 'Front squat direct gevolgd door een overhead press. Één vloeiende beweging. Conditionele full body oefening.',
    beschrijving: 'Begin met kettlebell in rack positie. Squat omlaag. Drijf explosief omhoog en gebruik de energie om de kettlebell overhead te drukken. Laat zakken terug naar rack. Herhaal vloeiend.',
    tips: ['Gebruik de squat energie voor de press', 'Één vloeiende beweging', 'Houd een consistent ritme', 'Gebruik lichtere gewichten'],
    fouten: ['Squat en press als aparte bewegingen', 'Te zwaar gewicht', 'Core laten zakken'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Hamstrings'],
    herstel: false,
    mobiliteit: false,
  },

  // ── PUSH (11) ─────────────────────────────────────────────────────────────

  {
    id: 'kb-strict-press',
    naam: 'Strict Press',
    illustratie: 'kettlebell-press.png',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '8-10',
    uitleg: 'Kettlebell vanuit rack positie recht omhoog drukken. Geen beenimpuls. Pure schouderkracht.',
    beschrijving: 'Breng de kettlebell naar de rack positie. Voeten op schouderbreedte. Druk de kettlebell recht omhoog door te strekken vanuit de schouder en triceps. Geen knie buiging. Laat gecontroleerd zakken naar rack.',
    tips: ['Core strak — geen rug hol trekken', 'Druk recht omhoog', 'Elleboog naar voren in de rack', 'Volledig strekken bovenin'],
    fouten: ['Rug hol trekken', 'Kettlebell naar voren drukken', 'Knieën buigen voor impuls'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-push-press',
    naam: 'Push Press',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen', 'benen'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gemiddeld',
    herhalingen: '8-10',
    uitleg: 'Press met een korte knieimpuls. Meer gewicht mogelijk dan een strict press. Traint explosieve kracht.',
    beschrijving: 'Kettlebell in rack positie. Maak een korte, snelle kniebewering — dip. Strek explosief en gebruik de energie om de kettlebell overhead te drukken. Strek volledig overhead. Laat zakken naar rack.',
    tips: ['Dip is kort en snel — geen diepe squat', 'Gebruik de beenimpuls, geen arm kracht', 'Strek volledig overhead', 'Houd het tempo consistent'],
    fouten: ['Te diepe dip', 'Armen te vroeg strekken', 'Onvoldoende overhead strekking'],
    primaireSpieren: ['Schouders', 'Triceps', 'Quadriceps'],
    secundaireSpieren: ['Core', 'Bilspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-jerk',
    naam: 'Jerk',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen', 'benen'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '5-6',
    uitleg: 'Twee-fase press: eerste dip drijft de kettlebell omhoog, tweede dip vangt hem overhead. Meest efficiënte kettlebell press technisch.',
    beschrijving: 'Kettlebell in rack. Eerste dip — explosief omhoog. De kettlebell stijgt. Tweede dip — zak snel onder de kettlebell en vang hem overhead met gestrekte arm. Sta op. Laat zakken naar rack. Complexe technische oefening.',
    tips: ['Twee aparte dips leren', 'Tweede dip is snel en diep', 'Strek de arm volledig in de vangpositie', 'Leer eerst de techniek goed'],
    fouten: ['Één continue beweging maken in plaats van twee dips', 'Arm niet strekken in de vang', 'Te zwaar beginnen'],
    primaireSpieren: ['Schouders', 'Triceps', 'Quadriceps'],
    secundaireSpieren: ['Core', 'Bilspieren', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-half-kneeling-press',
    naam: 'Half Kneeling Press',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'beginner',
    herhalingen: '8-10 per arm',
    uitleg: 'Press in een kniepositie. Traint schouders terwijl je core en heupstabiliteit uitdaagt.',
    beschrijving: 'Kniel op je rechterknie. Linkervoet voor je op de grond. Kettlebell in rack op de rechterarm. Druk recht omhoog. Houd je romp stabiel — niet naar de zijkant leunen. Laat zakken en herhaal.',
    tips: ['Houd romp recht — niet naar de zijkant leunen', 'Core actief aanspannen', 'Bilspier van het achterste been aanspannen', 'Beweeg alleen de arm'],
    fouten: ['Romp naar de drukzijde leunen', 'Core laten zakken', 'Heup van het knieënde been naar voren steken'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Obliques', 'Heupstabilisatoren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-seated-press',
    naam: 'Seated Press',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '10-12',
    uitleg: 'Press terwijl je op de grond zit. Elimineert beenimpuls volledig. Pure schouderisolatie.',
    beschrijving: 'Zit op de grond met benen voor je. Kettlebell in rack positie. Druk recht omhoog. Houd je rug recht — geen steuning. Laat zakken. Meer uitdagend voor de core dan staand.',
    tips: ['Zit recht — geen leunpunt', 'Core actief voor stabiliteit', 'Druk recht omhoog', 'Begin met een lichtere kettlebell dan normaal'],
    fouten: ['Achterover leunen', 'Core laten zakken', 'Te zwaar gewicht'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-arnold-press',
    naam: 'Arnold Press',
    categorie: 'push',
    lichaamsdelen: ['schouders'],
    doelen: ['kracht', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10-12',
    uitleg: 'Press met rotatie — begin met kettlebell voor het gezicht, roteer en druk omhoog. Traint alle koppen van de schouder.',
    beschrijving: 'Houd de kettlebell voor je gezicht met de handpal naar je toe. Roteer terwijl je omhoog drukt — eindig met handpalm naar voren en arm gestrekt overhead. Keer terug via dezelfde rotatie.',
    tips: ['Roteer vloeiend tijdens de beweging', 'Houd core actief', 'Volledig strekken bovenin', 'Controleer de neerwaartse rotatie'],
    fouten: ['Te snel bewegen', 'Rug hol trekken', 'Rotatie vergeten'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-bottom-up-press',
    naam: 'Bottom-Up Press',
    beschrijving: 'Houd de kettlebell ondersteboven — de bol omhoog. Druk omhoog terwijl je de kettlebell in balans houdt. Vereist intensieve grip en schouderstabiliteit.',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht', 'core'],
    niveau: 'gevorderd',
    herhalingen: '5-8 per arm',
    uitleg: 'Press met kettlebell ondersteboven. Extreme grip en schouderstabiliteit vereist.',
    tips: ['Grip zo sterk mogelijk', 'Beweeg langzaam en gecontroleerd', 'Begin met een lichtere kettlebell', 'Schouder actief stabiliseren'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Grip te los'],
    primaireSpieren: ['Schouders', 'Triceps', 'Onderarmen'],
    secundaireSpieren: ['Core', 'Rotatorenmanchet'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-floor-press',
    naam: 'Floor Press',
    categorie: 'push',
    lichaamsdelen: ['borst', 'schouders', 'armen'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '10-12',
    uitleg: 'Press liggend op de grond. Beperkte range door de grond. Minder schouderbelasting. Traint borst en triceps.',
    beschrijving: 'Lig op de grond. Houd kettlebells naast je borst. Druk omhoog totdat je armen gestrekt zijn. Laat langzaam zakken — ellebogen raken de grond. Houd de spanning en druk opnieuw omhoog.',
    tips: ['Ellebogen raken de grond bij elke herhaling', 'Schouderbladen ingetrokken', 'Voeten plat op de grond', 'Goed zonder bank'],
    fouten: ['Ellebogen hard op de grond', 'Geen volledige stop onderaan', 'Schouders optrekken'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-alternating-press',
    naam: 'Alternating Press',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '10 per arm',
    uitleg: 'Wissel afwisselend van arm bij de press. Terwijl de ene arm drukt, houdt de andere de rack positie. Traint core anti-rotatie.',
    beschrijving: 'Begin met beide kettlebells in rack positie. Druk de rechter kettlebell omhoog terwijl de linker in rack blijft. Laat zakken. Wissel naar links. Houd romp stabiel — niet naar de drukzijde leunen.',
    tips: ['Houd de niet-drukkende arm stabiel in rack', 'Core actief voor anti-rotatie', 'Houd romp recht', 'Beweeg bewust'],
    fouten: ['Romp roteren naar de drukzijde', 'Niet-drukkende arm laten zakken', 'Core laten zakken'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Obliques'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-double-press',
    naam: 'Double Press',
    categorie: 'push',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht'],
    niveau: 'gevorderd',
    herhalingen: '5-8',
    uitleg: 'Twee kettlebells tegelijk omhoog drukken. Dubbele belasting. Symmetrische kracht vereist.',
    beschrijving: 'Begin met twee kettlebells in rack positie. Druk beide tegelijk recht omhoog. Strek volledig overhead. Laat samen zakken naar rack. Vereist goede techniek en gelijke kracht aan beide zijden.',
    tips: ['Beide kettlebells gelijktijdig', 'Core extra strak', 'Begin met lichtere gewichten dan verwacht', 'Houd symmetrie in de beweging'],
    fouten: ['Ongelijke hoogte', 'Rug hol trekken', 'Te zwaar beginnen'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-incline-floor-press',
    naam: 'Incline Floor Press',
    categorie: 'push',
    lichaamsdelen: ['borst', 'schouders'],
    doelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10-12',
    uitleg: 'Floor press op een licht schuine ondergrond of met heupen omhoog. Verschuift de belasting naar de bovenkant van de borst.',
    beschrijving: 'Lig op de grond met je heupen op een kleine verhoging (opgerolde mat of kussen) zodat je licht schuiner ligt. Voer een floor press uit. De hoek verschuift de nadruk naar de bovenkant van de borst.',
    tips: ['Verhoging hoeft niet groot te zijn', 'Dezelfde techniek als floor press', 'Schouderbladen ingetrokken', 'Ellebogen raken de grond'],
    fouten: ['Te hoge verhoging — wordt een schouderpress', 'Ellebogen niet op de grond', 'Schouders optrekken'],
    primaireSpieren: ['Bovenkant borst', 'Schouders'],
    secundaireSpieren: ['Triceps'],
    herstel: false,
    mobiliteit: false,
  },

  // ── PULL (7) ──────────────────────────────────────────────────────────────

  {
    id: 'kb-single-arm-row',
    naam: 'Single Arm Row',
    categorie: 'pull',
    lichaamsdelen: ['rug'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '10-12 per arm',
    uitleg: 'Eénarmige row. Knie en hand op een bank voor steun. Trek de kettlebell naar de heup. Rugtraining.',
    beschrijving: 'Knie en hand op een bank voor steun. Houd de kettlebell in de andere hand. Trek de kettlebell omhoog naar je heup — elleboog gaat recht langs het lichaam. Schouderblad samentrekken bovenin. Laat gecontroleerd zakken.',
    tips: ['Elleboog recht langs het lichaam', 'Rug recht — geen rotatie', 'Trek naar de heup', 'Schouderblad samentrekken bovenin'],
    fouten: ['Romp roteren', 'Elleboog te ver naar buiten', 'Momentum gebruiken'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Achterste schouder', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-bent-over-row',
    naam: 'Bent Over Row',
    categorie: 'pull',
    lichaamsdelen: ['rug'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '10-12',
    uitleg: 'Voorovergebogen bilaterale row. Beide kettlebells optrekken naar de buik. Rugtraining.',
    beschrijving: 'Leun voorover met rechte rug — romp op 45-60 graden. Houd kettlebells naar beneden hangend. Trek beide kettlebells tegelijk naar je buik. Schouderbladen samentrekken. Laat gecontroleerd zakken.',
    tips: ['Rug recht', 'Trek naar de buik — niet de borst', 'Schouderbladen samentrekken', 'Ellebogen dicht langs het lichaam'],
    fouten: ['Rug afronden', 'Romp omhoog bewegen', 'Trek naar de borst'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Core', 'Achterste schouder'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-gorilla-row',
    naam: 'Gorilla Row',
    categorie: 'pull',
    lichaamsdelen: ['rug', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '10 per arm',
    uitleg: 'Twee kettlebells op de grond. Alterneer rows terwijl de andere kettlebell op de grond rust. Core stabiliteit vereist.',
    beschrijving: 'Twee kettlebells op de grond. Sta gestrekt over de kettlebells in hinge positie. Trek de rechter kettlebell omhoog terwijl de linker op de grond rust. Zet neer en wissel. Houd romp stabiel.',
    tips: ['Heupen stabiel — geen rotatie', 'Elleboog hoog bij de row', 'Zet de kettlebell gecontroleerd neer', 'Core actief'],
    fouten: ['Heupen roteren bij het optrekken', 'Te snel wisselen', 'Rug afronden'],
    primaireSpieren: ['Latissimus dorsi', 'Core', 'Obliques'],
    secundaireSpieren: ['Biceps', 'Rhomboids'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-renegade-row',
    naam: 'Renegade Row',
    categorie: 'pull',
    lichaamsdelen: ['rug', 'core', 'borst'],
    doelen: ['kracht', 'core', 'conditie'],
    niveau: 'gevorderd',
    herhalingen: '8-10 per arm',
    uitleg: 'Plank op kettlebells. Trek één kettlebell omhoog terwijl de andere steunt. Combineert plank en row.',
    beschrijving: 'Plankpositie met handen op kettlebells. Trek rechter kettlebell omhoog naar je heup. Houd heupen stabiel — minimale rotatie. Zet neer en wissel. Core maximaal aanspannen.',
    tips: ['Heupen zo stabiel mogelijk', 'Voeten wijder voor meer stabiliteit', 'Core maximaal aanspannen', 'Beweging is klein en gecontroleerd'],
    fouten: ['Heupen roteren bij het optrekken', 'Core laten zakken', 'Te snel bewegen'],
    primaireSpieren: ['Latissimus dorsi', 'Core', 'Obliques'],
    secundaireSpieren: ['Borst', 'Schouders', 'Biceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-high-pull',
    naam: 'High Pull',
    categorie: 'pull',
    lichaamsdelen: ['rug', 'schouders', 'billen'],
    doelen: ['kracht', 'ballistisch', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '10-12',
    uitleg: 'Explosieve swing die overgaat in een hoge row. Trek de kettlebell omhoog tot kin hoogte met elleboog hoog.',
    beschrijving: 'Begin als een swing. Op het hoogste punt van de swing trek je de kettlebell explosief omhoog naar kin hoogte — elleboog gaat hoger dan de hand. Laat zakken en herhaal. Combineert hip explosiviteit met bovenlichaam trekken.',
    tips: ['Ellebogen hoger dan de kettlebell bovenin', 'Gebruik bilspieren voor de explosiviteit', 'Trek actief naar de kin', 'Vloeiende overgang van swing naar pull'],
    fouten: ['Ellebogen te laag', 'Alleen arm gebruiken zonder bilspieren', 'Te zwaar beginnen'],
    primaireSpieren: ['Bilspieren', 'Trapezius', 'Schouders'],
    secundaireSpieren: ['Hamstrings', 'Biceps', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-upright-row',
    naam: 'Upright Row',
    categorie: 'pull',
    lichaamsdelen: ['schouders', 'rug'],
    doelen: ['kracht'],
    niveau: 'beginner',
    herhalingen: '12-15',
    uitleg: 'Trek kettlebell(s) omhoog langs het lichaam tot kin hoogte. Ellebogen gaan hoger dan de handen. Schouders en trapezius.',
    beschrijving: 'Houd de kettlebell voor je met beide handen aan de handel. Trek omhoog langs het lichaam tot kin hoogte — ellebogen gaan hoger dan de kettlebell. Laat langzaam zakken.',
    tips: ['Ellebogen hoger dan de handen', 'Kettlebell dicht langs het lichaam', 'Stop bij kin hoogte', 'Beweeg langzaam'],
    fouten: ['Ellebogen te laag', 'Kettlebell te ver van het lichaam', 'Momentum gebruiken'],
    primaireSpieren: ['Trapezius', 'Zijkant schouder'],
    secundaireSpieren: ['Biceps', 'Voorste schouder'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-meadows-row',
    naam: 'Meadows Row Variatie',
    categorie: 'pull',
    lichaamsdelen: ['rug'],
    doelen: ['kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10-12 per arm',
    uitleg: 'Eénarmige row met unieke hoek. Trek schuin omhoog en naar buiten voor maximale lat activatie.',
    beschrijving: 'Sta naast de kettlebell. Stap met één been achteruit. Pak de kettlebell. Trek schuin omhoog en naar buiten — anders dan een normale row. Voel de lat maximaal werken.',
    tips: ['Trek schuin naar buiten — niet recht omhoog', 'Houd romp stabiel', 'Voel de lat werken', 'Experimenteer met de hoek'],
    fouten: ['Te recht omhoog trekken', 'Romp roteren', 'Elleboog te ver naar buiten'],
    primaireSpieren: ['Latissimus dorsi'],
    secundaireSpieren: ['Teres major', 'Biceps', 'Core'],
    herstel: false,
    mobiliteit: false,
  },

  // ── BALLISTISCH / OLYMPIC (10) ────────────────────────────────────────────

  {
    id: 'kb-clean',
    naam: 'Clean',
    illustratie: 'kettlebell-clean.png',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '5-8 per arm',
    uitleg: 'Breng de kettlebell van de grond of een swing naar de rack positie. Fundamentele kettlebell techniek.',
    beschrijving: 'Begin als een swing of deadlift. Trek de kettlebell omhoog langs het lichaam. Bij kin hoogte roteer je je hand en vang je de kettlebell in rack positie. Elleboog naar voren, kettlebell ruht op de onderarm. Zet terug via een gecontroleerde swing.',
    tips: ['Trek de kettlebell dicht langs het lichaam', 'Roteer de hand vroeg genoeg', 'Vang in rack — niet op de hand', 'Houd elleboog naar voren in rack'],
    fouten: ['Kettlebell slaat op de onderarm bij de vangst', 'Elleboog niet naar voren in rack', 'Te ver van het lichaam trekken'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    secundaireSpieren: ['Core', 'Rugspieren', 'Biceps'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-double-clean',
    naam: 'Double Clean',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '5-6',
    uitleg: 'Clean met twee kettlebells tegelijk. Dubbele belasting. Vereist goede clean techniek met beide armen.',
    beschrijving: 'Zelfde als een single clean maar met twee kettlebells tegelijk. Breng beide kettlebells tegelijk naar de dubbele rack positie. Vereist meer kracht en coördinatie.',
    tips: ['Houd beide kettlebells dicht bij het lichaam', 'Gelijktijdige beweging', 'Begin met lichtere gewichten', 'Goede single clean techniek vereist'],
    fouten: ['Ongelijke hoogte', 'Kettlebells te ver van het lichaam', 'Slechte single clean techniek'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-clean-press',
    naam: 'Clean & Press',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '5-6 per arm',
    uitleg: 'Clean gevolgd direct door een press. Twee fundamentele kettlebell bewegingen gecombineerd.',
    beschrijving: 'Voer een clean uit om de kettlebell naar rack te brengen. Voer direct daarna een strict press of push press uit. Laat zakken naar rack of via een gecontroleerde swing terug naar de startpositie.',
    tips: ['Clean en press kunnen in één vloeiende beweging', 'Gebruik push press voor meer gewicht', 'Consistente techniek in beide bewegingen', 'Houd een stabiel ritme'],
    fouten: ['Slechte rack positie voor de press', 'Press te snel na de clean', 'Techniek verslechteren door vermoeidheid'],
    primaireSpieren: ['Bilspieren', 'Schouders', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Triceps', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-clean-jerk',
    naam: 'Clean & Jerk',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '3-5 per arm',
    uitleg: 'Clean gevolgd door een jerk. Maximale kracht en techniek. Olympisch geïnspireerde kettlebell oefening.',
    beschrijving: 'Voer een clean uit. Daarna een jerk met twee dips. Complexe technische oefening die training en ervaring vereist. Maximale belasting mogelijk door de efficiënte jerktechniek.',
    tips: ['Leer clean en jerk apart voor je combineert', 'Jerk techniek is de uitdaging', 'Begin licht', 'Focus op techniek boven gewicht'],
    fouten: ['Slechte jerk techniek', 'Te zwaar voor het niveau', 'Vermoeidheid die techniek beïnvloedt'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Neuraal systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-snatch',
    naam: 'Snatch',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch', 'conditie'],
    niveau: 'gevorderd',
    herhalingen: '5-8 per arm',
    uitleg: 'Trek de kettlebell in één beweging van swing naar overhead. De meest uitdagende kettlebell oefening technisch.',
    beschrijving: 'Begin als een swing. Trek de kettlebell in één vloeiende beweging via de zijkant van het lichaam omhoog. Roteer de hand en vang overhead — arm volledig gestrekt. Houd even vast. Laat zakken via dezelfde weg.',
    tips: ['Trek via de zijkant — niet recht omhoog', 'Roteer de hand vroeg', 'Vang met gestrekte arm — geen sloeg', 'Leer de techniek stap voor stap'],
    fouten: ['Kettlebell slaat op de onderarm bij de vangst', 'Te ver van het lichaam', 'Arm niet volledig strekken overhead'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    secundaireSpieren: ['Core', 'Rugspieren', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-long-cycle',
    naam: 'Long Cycle',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '5-10 minuten',
    uitleg: 'Clean & Jerk herhaald voor langere tijd. De sport van kettlebell sport. Maximale conditionele uitdaging.',
    beschrijving: 'Clean & Jerk cyclisch uitgevoerd voor 5-10 minuten. Minimale stops. Gebruikt in kettlebell sport competities. Vereist goede techniek, conditie en mentale kracht.',
    tips: ['Efficiënte ademhaling is cruciaal', 'Pacing is alles', 'Techniek boven tempo', 'Train eerst de techniek grondig'],
    fouten: ['Te hard van start gaan', 'Techniek laten verslechteren', 'Geen ademhalingsritme'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Cardiovasculair systeem', 'Neuraal systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-half-snatch',
    naam: 'Half Snatch',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gemiddeld',
    herhalingen: '8-10 per arm',
    uitleg: 'Snatch waarbij je de kettlebell laat zakken naar rack (niet naar de grond). Minder intensief dan een volledige snatch.',
    beschrijving: 'Voer een snatch uit. In plaats van de kettlebell terug te laten zakken naar de grond, laat je hem zakken naar de rack positie. Dan een swing vanuit rack en opnieuw. Een goede overgang naar de volledige snatch.',
    tips: ['Vang gecontroleerd in rack', 'Houd de hinge bij de swing vanuit rack', 'Goede tussenstap naar volledige snatch', 'Houd consistent ritme'],
    fouten: ['Kettlebell niet goed vangen in rack', 'Rug afronden bij de swing vanuit rack', 'Te snel'],
    primaireSpieren: ['Bilspieren', 'Schouders', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-swing-clean',
    naam: 'Swing Clean',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '8-10 per arm',
    uitleg: 'Swing die overgaat in een clean. Wissel elke herhaling tussen swing en clean. Rhythmisch en conditioneel.',
    beschrijving: 'Doe een swing, dan een clean. Swing, clean, swing, clean. Of meerdere swings gevolgd door een clean. Creëert een ritmisch patroon dat zowel kracht als conditie traint.',
    tips: ['Houd een consistent ritme', 'Clean techniek blijft hetzelfde als bij een normale clean', 'Adem bewust', 'Plan het patroon van tevoren'],
    fouten: ['Ritme verliezen', 'Slechte clean techniek door vermoeidheid', 'Geen bewuste ademhaling'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-high-pull-snatch',
    naam: 'High Pull to Snatch',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '5-6 per arm',
    uitleg: 'High pull die overgaat in een snatch. Leert de bovenste fase van de snatch. Technische oefening.',
    beschrijving: 'Begin als een high pull. Op het hoogste punt van de pull roteer je de hand en strek je de arm volledig overhead — zoals bij een snatch. Laat zakken. Goede oefening voor het leren van de snatchtechniek.',
    tips: ['High pull en snatch-finish in één beweging', 'Roteer de hand op het hoogste punt', 'Arm strekken na de rotatie', 'Gebruik als snatch leeroefening'],
    fouten: ['High pull en snatch als twee aparte bewegingen', 'Arm niet volledig strekken', 'Te zwaar beginnen'],
    primaireSpieren: ['Bilspieren', 'Schouders', 'Trapezius'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-double-snatch',
    naam: 'Double Snatch',
    categorie: 'ballistisch',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '3-5',
    uitleg: 'Snatch met twee kettlebells tegelijk. Extreme uitdaging. Vereist perfecte snatchtechniek met beide armen.',
    beschrijving: 'Twee kettlebells. Voer een snatch uit met beide armen tegelijk. Beide armen strekken overhead gelijktijdig. Uiterst technisch en krachtig. Alleen voor gevorderden met perfecte single snatch techniek.',
    tips: ['Perfecte single snatch techniek vereist', 'Begin met lichtere kettlebells', 'Gelijktijdige beweging', 'Goede schoudermobiliteit noodzakelijk'],
    fouten: ['Slechte single snatch techniek', 'Ongelijke beweging', 'Te zwaar voor het niveau'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Schouders'],
    secundaireSpieren: ['Core', 'Rugspieren', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },

  // ── CARRY (9) ─────────────────────────────────────────────────────────────

  {
    id: 'kb-farmer-carry',
    naam: 'Farmer Carry',
    illustratie: 'farmer-carry.png',
    categorie: 'carry',
    lichaamsdelen: ['core', 'fullbody'],
    doelen: ['kracht', 'conditie'],
    niveau: 'beginner',
    herhalingen: '30-40 meter',
    uitleg: 'Lopen met kettlebells in beide handen langs het lichaam. Grip, core en conditie. Eenvoudig maar effectief.',
    beschrijving: 'Pak een kettlebell in elke hand. Houd je schouders naar achteren en omlaag. Borst omhoog. Loop een bepaalde afstand met kleine, snelle stappen. Houd de kettlebells stil — niet laten slingeren.',
    tips: ['Schouders naar achteren en omlaag', 'Borst omhoog', 'Kleine, snelle stappen', 'Kettlebells stabiel houden'],
    fouten: ['Schouders optrekken', 'Naar één kant leunen', 'Te langzame stappen'],
    primaireSpieren: ['Onderarmen', 'Core', 'Trapezius'],
    secundaireSpieren: ['Schouders', 'Benen', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-suitcase-carry',
    naam: 'Suitcase Carry',
    categorie: 'carry',
    lichaamsdelen: ['core'],
    doelen: ['kracht', 'core'],
    niveau: 'beginner',
    herhalingen: '20-30 meter per kant',
    uitleg: 'Lopen met één kettlebell. Traint core anti-laterale buiging. Zwaarder voor de core dan de farmer carry.',
    beschrijving: 'Pak één kettlebell in één hand. Loop een bepaalde afstand. Houd je romp recht — weersta de neiging om naar de kettlebell kant te leunen. Wissel van hand na de afstand.',
    tips: ['Houd romp recht — niet naar de kettlebell kant leunen', 'Core actief aanspannen', 'Schouder aan de kettlebell kant omlaag houden', 'Bewust de core werken'],
    fouten: ['Naar de kettlebell kant leunen', 'Schouder optrekken', 'Core niet actief'],
    primaireSpieren: ['Obliques', 'Core', 'Quadratus lumborum'],
    secundaireSpieren: ['Onderarmen', 'Schouders'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-rack-carry',
    naam: 'Rack Carry',
    categorie: 'carry',
    lichaamsdelen: ['core', 'schouders'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '20-30 meter per kant',
    uitleg: 'Lopen met kettlebell in rack positie. Traint core en schouderstabiliteit. Zwaarder dan farmer carry.',
    beschrijving: 'Breng een kettlebell naar de rack positie. Loop terwijl je de rack positie behoudt — elleboog omhoog, kettlebell op de onderarm. Houd je romp recht.',
    tips: ['Elleboog hoog houden', 'Romp recht — niet naar de rack kant leunen', 'Core actief', 'Schouder stabiliseren'],
    fouten: ['Elleboog laten zakken', 'Romp laten leunen', 'Core niet actief'],
    primaireSpieren: ['Core', 'Schouders', 'Obliques'],
    secundaireSpieren: ['Trapezius', 'Benen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-overhead-carry',
    naam: 'Overhead Carry',
    categorie: 'carry',
    lichaamsdelen: ['schouders', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '20 meter per kant',
    uitleg: 'Lopen met kettlebell overhead. Maximale schouderstabiliteit en core activatie. Technisch uitdagend.',
    beschrijving: 'Breng de kettlebell overhead met gestrekte arm. Loop een bepaalde afstand. Arm volledig gestrekt, schouder actief. Houd je blik naar voren. Wissel van arm.',
    tips: ['Arm volledig gestrekt', 'Schouder actief — niet laten hangen', 'Kern strak voor stabiliteit', 'Kijk naar voren'],
    fouten: ['Arm niet volledig strekken', 'Schouder hangen', 'Core laten zakken'],
    primaireSpieren: ['Schouders', 'Core', 'Trapezius'],
    secundaireSpieren: ['Triceps', 'Obliques', 'Benen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-waiter-carry',
    naam: 'Waiter Carry',
    categorie: 'carry',
    lichaamsdelen: ['schouders', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '20 meter per kant',
    uitleg: 'Overhead carry waarbij de kettlebell ondersteboven wordt gehouden. Extreme grip en schouderstabiliteit.',
    beschrijving: 'Houd de kettlebell ondersteboven overhead — bol omhoog. Loop een bepaalde afstand. Arm gestrekt. De instabiele positie vereist maximale grip en schouderstabiliteit.',
    tips: ['Grip zo sterk mogelijk', 'Arm volledig gestrekt', 'Schouder actief stabiliseren', 'Begin met een lichtere kettlebell'],
    fouten: ['Grip te los', 'Arm niet volledig strekken', 'Te zwaar beginnen'],
    primaireSpieren: ['Onderarmen', 'Schouders', 'Core'],
    secundaireSpieren: ['Rotatorenmanchet', 'Trapezius'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-bottom-up-carry',
    naam: 'Bottom-Up Carry',
    categorie: 'carry',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht', 'core'],
    niveau: 'gevorderd',
    herhalingen: '15 meter per kant',
    uitleg: 'Lopen met kettlebell ondersteboven in rack positie. Extreem voor de grip en schouderstabiliteit.',
    beschrijving: 'Houd de kettlebell ondersteboven in rack positie — bol omhoog, elleboog naar voren. Loop een afstand. De instabiele positie in rack vereist maximale grip en stabiliteit.',
    tips: ['Maximale grip', 'Elleboog naar voren', 'Romp recht', 'Begin met een zeer lichte kettlebell'],
    fouten: ['Te zwaar gewicht', 'Grip te los', 'Elleboog niet naar voren'],
    primaireSpieren: ['Onderarmen', 'Schouders'],
    secundaireSpieren: ['Core', 'Rotatorenmanchet'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-offset-carry',
    naam: 'Offset Carry',
    categorie: 'carry',
    lichaamsdelen: ['core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '20-30 meter',
    uitleg: 'Twee kettlebells op verschillende hoogtes tegelijk. Bijv. één overhead, één in rack. Maximale core uitdaging.',
    beschrijving: 'Houd één kettlebell overhead en één in rack positie of farmer positie. Loop een afstand. De asymmetrische belasting daagt de core extreem uit. Wissel posities na de afstand.',
    tips: ['Plan de posities van tevoren', 'Core maximaal aanspannen', 'Bewuste ademhaling', 'Begin met lichtere kettlebells'],
    fouten: ['Romp laten leunen', 'Core niet actief', 'Te zwaar voor de combinatie'],
    primaireSpieren: ['Core', 'Obliques', 'Schouders'],
    secundaireSpieren: ['Trapezius', 'Benen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-march-carry',
    naam: 'March Carry',
    categorie: 'carry',
    lichaamsdelen: ['core', 'benen'],
    doelen: ['kracht', 'core', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '20 stappen per kant',
    uitleg: 'Carry waarbij je hoog marcheert — knie tot heupniveau bij elke stap. Traint core stabiliteit extra.',
    beschrijving: 'Houd kettlebells in farm, rack of overhead positie. Loop terwijl je elke knie hoog optilt bij elke stap — tot heupniveau. Houd romp stabiel terwijl je marcheert.',
    tips: ['Hoog marcheren — knie tot heupniveau', 'Houd romp stabiel bij elke stap', 'Core actief bij het optillen van de knie', 'Houd een rustig tempo'],
    fouten: ['Te lage knieheffing', 'Romp bewegen bij elke stap', 'Core niet actief'],
    primaireSpieren: ['Core', 'Heupbuigers', 'Obliques'],
    secundaireSpieren: ['Schouders', 'Benen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-front-rack-carry',
    naam: 'Front Rack Carry',
    categorie: 'carry',
    lichaamsdelen: ['schouders', 'core'],
    doelen: ['kracht', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '20-30 meter',
    uitleg: 'Lopen met twee kettlebells in dubbele rack positie. Beide ellebogen hoog. Traint core en schouderstabiliteit.',
    beschrijving: 'Breng twee kettlebells naar de dubbele rack positie. Loop een afstand met beide kettlebells in rack. Ellebogen hoog houden. Houd romp recht.',
    tips: ['Beide ellebogen hoog houden', 'Romp recht', 'Core actief', 'Begin met lichtere kettlebells dan verwacht'],
    fouten: ['Ellebogen laten zakken', 'Naar voren leunen door het gewicht', 'Core laten zakken'],
    primaireSpieren: ['Core', 'Schouders'],
    secundaireSpieren: ['Trapezius', 'Benen', 'Biceps'],
    herstel: false,
    mobiliteit: false,
  },

  // ── CORE & STABILITY (11) ─────────────────────────────────────────────────

  {
    id: 'kb-halo',
    naam: 'Halo',
    categorie: 'core',
    lichaamsdelen: ['schouders', 'core'],
    doelen: ['warmup', 'mobiliteit'],
    niveau: 'beginner',
    herhalingen: '10 per richting',
    uitleg: 'Kettlebell cirkelvormig rond het hoofd bewegen. Warming-up voor schouders en bovenrug.',
    beschrijving: 'Houd de kettlebell bij de horns voor je borst. Beweeg de kettlebell in een cirkel rond je hoofd — rechts, achter, links, voor. Houd je romp stabiel. Wissel van richting.',
    tips: ['Houd de kern stabiel — niet meedraaien', 'Bewuste, gecontroleerde beweging', 'Houd de kettlebell dicht bij het hoofd', 'Wissel van richting na elke ronde'],
    fouten: ['Romp meedraaien', 'Te snel bewegen', 'Kettlebell te ver van het hoofd'],
    primaireSpieren: ['Schouders', 'Trapezius'],
    secundaireSpieren: ['Core', 'Bovenrug'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-around-the-world',
    naam: 'Around the World',
    categorie: 'core',
    lichaamsdelen: ['core', 'schouders'],
    doelen: ['warmup', 'core'],
    niveau: 'beginner',
    herhalingen: '10 per richting',
    uitleg: 'Kettlebell cirkelvormig rond het lichaam doorgeven van de ene naar de andere hand. Core activatie en coördinatie.',
    beschrijving: 'Houd de kettlebell voor je. Geef de kettlebell door van de ene hand naar de andere in een cirkel rond je lichaam. Wissel van richting.',
    tips: ['Houd de kern actief', 'Vloeiende beweging', 'Houd de kettlebell dicht bij het lichaam', 'Wissel van richting'],
    fouten: ['Core niet actief', 'Te snel bewegen', 'Kettlebell te ver van het lichaam'],
    primaireSpieren: ['Core', 'Obliques'],
    secundaireSpieren: ['Schouders', 'Onderarmen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-around-the-body',
    naam: 'Around the Body Pass',
    categorie: 'core',
    lichaamsdelen: ['core'],
    doelen: ['warmup', 'core'],
    niveau: 'beginner',
    herhalingen: '10 per richting',
    uitleg: 'Kettlebell rondom de romp doorgeven. Vergelijkbaar met around the world maar andere bewegingsrichting.',
    beschrijving: 'Houd de kettlebell voor je romp. Geef de kettlebell achterlangs door van de ene hand naar de andere. Maak een cirkel rond je romp. Wissel van richting.',
    tips: ['Stabiele basis', 'Houd de kern actief', 'Vloeiende overgang van hand naar hand', 'Kijk niet naar de kettlebell — voel'],
    fouten: ['Romp bewegen', 'Core niet actief', 'Kettlebell te ver van het lichaam'],
    primaireSpieren: ['Core', 'Obliques'],
    secundaireSpieren: ['Schouders', 'Onderarmen'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-russian-twist',
    naam: 'Russian Twist',
    categorie: 'core',
    lichaamsdelen: ['core'],
    doelen: ['core', 'kracht'],
    niveau: 'beginner',
    herhalingen: '15 per kant',
    uitleg: 'Zit met knieën gebogen en romp achterover. Roteer met de kettlebell van links naar rechts. Traint de obliques.',
    beschrijving: 'Zit op de grond met knieën gebogen. Houd de kettlebell voor je. Leun achterover tot 45 graden. Roteer van links naar rechts met de kettlebell. Voeten op de grond of omhoog voor meer uitdaging.',
    tips: ['Roteer vanuit de romp', 'Houd de borst omhoog', 'Adem uit bij elke rotatie', 'Voeten omhoog voor meer uitdaging'],
    fouten: ['Alleen armen bewegen', 'Romp te ver achterover', 'Te snel'],
    primaireSpieren: ['Obliques', 'Core'],
    secundaireSpieren: ['Heupbuigers', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-plank-drag',
    naam: 'Plank Drag',
    categorie: 'core',
    lichaamsdelen: ['core'],
    doelen: ['core', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '10 per kant',
    uitleg: 'Plank op de grond. Trek de kettlebell met één hand onder het lichaam door naar de andere kant. Core stabiliteit.',
    beschrijving: 'Ga in een plankpositie. Kettlebell naast je. Trek de kettlebell met je rechterhand onder je lichaam door naar de rechterkant. Dan met de linkerhand terug. Houd heupen zo stabiel mogelijk.',
    tips: ['Heupen zo stabiel mogelijk', 'Core maximaal aanspannen', 'Voeten iets breder voor stabiliteit', 'Bewuste, gecontroleerde beweging'],
    fouten: ['Heupen roteren bij het trekken', 'Core laten zakken', 'Te snel bewegen'],
    primaireSpieren: ['Core', 'Obliques'],
    secundaireSpieren: ['Schouders', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-dead-bug',
    naam: 'Dead Bug met Kettlebell',
    categorie: 'core',
    lichaamsdelen: ['core'],
    doelen: ['core', 'herstel'],
    niveau: 'beginner',
    herhalingen: '8-10 per kant',
    uitleg: 'Dead bug met kettlebell overhead. Strek arm en been terwijl je de kettlebell in positie houdt. Verhoogde core uitdaging.',
    beschrijving: 'Lig op de rug. Houd de kettlebell overhead met gestrekte arm. Breng knieën omhoog in 90 graden. Strek tegengestelde arm en been terwijl je de kettlebell stabiel houdt. Onderrug op de mat.',
    tips: ['Onderrug blijft op de mat', 'Kettlebell stabiel houden', 'Beweeg langzaam', 'Adem uit bij het strekken'],
    fouten: ['Onderrug van de mat', 'Kettlebell bewegen', 'Te snel'],
    primaireSpieren: ['Core', 'Transversus abdominis'],
    secundaireSpieren: ['Schouders', 'Heupbuigers'],
    herstel: true,
    mobiliteit: false,
  },
  {
    id: 'kb-weighted-situp',
    naam: 'Weighted Sit-Up',
    categorie: 'core',
    lichaamsdelen: ['core'],
    doelen: ['kracht', 'core'],
    niveau: 'beginner',
    herhalingen: '12-15',
    uitleg: 'Sit-up met kettlebell voor de borst of overhead. Extra weerstand voor de buikspieren.',
    beschrijving: 'Lig op de rug. Houd de kettlebell voor de borst of strek hem overhead. Kom omhoog in een sit-up beweging. Beweeg gecontroleerd omlaag.',
    tips: ['Beweeg gecontroleerd omlaag', 'Voeten kunnen vast of vrij zijn', 'Kettlebell dicht bij het lichaam', 'Adem uit bij omhoog komen'],
    fouten: ['Te snel naar beneden', 'Nek aanspannen', 'Te zwaar gewicht'],
    primaireSpieren: ['Rectus abdominis', 'Heupbuigers'],
    secundaireSpieren: ['Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-windmill',
    naam: 'Windmill',
    categorie: 'core',
    lichaamsdelen: ['core', 'schouders'],
    doelen: ['kracht', 'mobiliteit', 'core'],
    niveau: 'gevorderd',
    herhalingen: '5-8 per kant',
    uitleg: 'Kettlebell overhead. Buig naar de tegenovergestelde kant en raak je voet aan. Houd de kettlebell boven. Mobiliteit en kracht.',
    beschrijving: 'Houd de kettlebell overhead met de rechterarm. Voeten wijder dan schouderbreedte, rechtervoet naar buiten gedraaid. Buig naar links langs je linkerbeen — raak je linkerknie of enkel aan. Houd de rechterarm gestrekt omhoog. Kom omhoog.',
    tips: ['Houd de overhead arm gestrekt', 'Kijk naar de kettlebell overhead', 'Buig langs het been — niet naar voren', 'Beweeg langzaam'],
    fouten: ['Overhead arm buigen', 'Naar voren buigen in plaats van naar de zijkant', 'Knieën buigen'],
    primaireSpieren: ['Core', 'Obliques', 'Schouders'],
    secundaireSpieren: ['Hamstrings', 'Bilspieren', 'Heupabductoren'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-bent-press',
    naam: 'Bent Press',
    categorie: 'core',
    lichaamsdelen: ['core', 'schouders'],
    doelen: ['kracht', 'mobiliteit'],
    niveau: 'gevorderd',
    herhalingen: '3-5 per kant',
    uitleg: 'Buig weg van de kettlebell terwijl je hem boven de schouder houdt. Roteer omhoog. Historische krachtsoefening — maximale technische uitdaging.',
    beschrijving: 'Begin met kettlebell op de schouder. Buig weg van de kettlebell terwijl je hem boven je schouder houdt. Roteer je lichaam onder de kettlebell. Sta recht op met de kettlebell overhead. Keer terug. Een van de meest technische kettlebell oefeningen.',
    tips: ['Leer de windmill eerst goed', 'Beweeg extreem langzaam', 'Kijk naar de kettlebell', 'Begin met een heel licht gewicht'],
    fouten: ['Te snel bewegen', 'Kettlebell laten bewegen', 'Te zwaar voor het niveau'],
    primaireSpieren: ['Core', 'Obliques', 'Schouders'],
    secundaireSpieren: ['Rugspieren', 'Triceps', 'Heupabductoren'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-turkish-getup',
    naam: 'Turkish Get-Up',
    categorie: 'core',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'mobiliteit', 'core'],
    niveau: 'gevorderd',
    herhalingen: '3-5 per kant',
    uitleg: 'Kom van liggen naar staan met kettlebell overhead. Meervoudige stappen. De complete kettlebell oefening voor kracht en mobiliteit.',
    beschrijving: 'Lig op de rug met kettlebell overhead. Stap voor stap kom je omhoog: rol naar de zijkant, ondersteun op de hand, til de heup op, breng het been door, knie op de grond, sta op. Alles terwijl de kettlebell overhead blijft. Keer terug via dezelfde stappen.',
    tips: ['Leer elke stap apart', 'Kijk altijd naar de kettlebell', 'Beweeg langzaam', 'Begin zonder gewicht of met een schoen op de hand'],
    fouten: ['Te snel bewegen', 'Arm buigen', 'Stappen overslaan'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Neuraal systeem', 'Proprioceptie'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-half-turkish-getup',
    naam: 'Half Turkish Get-Up',
    categorie: 'core',
    lichaamsdelen: ['core', 'schouders'],
    doelen: ['kracht', 'mobiliteit', 'core'],
    niveau: 'gemiddeld',
    herhalingen: '5-6 per kant',
    uitleg: 'Eerste helft van de Turkish Get-Up. Kom van liggen naar kniepositie. Goede introductie voor de volledige TGU.',
    beschrijving: 'Lig op de rug. Rol naar de zijkant. Ondersteun op je hand. Til je heup op. Breng het been door. Stop bij de kniepositie. Keer terug via dezelfde weg. Geen volledig opstaan.',
    tips: ['Kijk naar de kettlebell', 'Elk stap bewust uitvoeren', 'Houd de arm gestrekt', 'Goede voorbereiding voor de volledige TGU'],
    fouten: ['Arm buigen', 'Te snel', 'Stappen overslaan'],
    primaireSpieren: ['Core', 'Schouders', 'Obliques'],
    secundaireSpieren: ['Bilspieren', 'Heupbuigers'],
    herstel: false,
    mobiliteit: true,
  },

  // ── MOBILITEIT & HERSTEL (10) ─────────────────────────────────────────────

  {
    id: 'kb-goblet-hold',
    naam: 'Goblet Hold Squat',
    categorie: 'mobiliteit',
    lichaamsdelen: ['benen', 'billen'],
    doelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    duur: 60,
    uitleg: 'Houd een goblet squat positie vast. Gebruik je ellebogen om knieën naar buiten te drukken. Heup mobiliteit.',
    beschrijving: 'Ga in een diepe goblet squat positie en houd die vast. Gebruik je ellebogen om je knieën actief naar buiten te duwen. Adem diep en laat je heupen bij elke uitademing iets meer ontspannen.',
    tips: ['Ellebogen duwen knieën naar buiten', 'Adem diep in de positie', 'Laat je heupen ontspannen', 'Gebruik de kettlebell als counterbalance'],
    fouten: ['Hielen optillen', 'Borst naar voren vallen', 'Spanning vasthouden'],
    primaireSpieren: ['Heupen', 'Bilspieren'],
    secundaireSpieren: ['Quadriceps', 'Ankels', 'Rugspieren'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-arm-bar',
    naam: 'Arm Bar',
    categorie: 'mobiliteit',
    lichaamsdelen: ['schouders', 'rug'],
    doelen: ['mobiliteit', 'herstel'],
    niveau: 'gemiddeld',
    duur: 60,
    uitleg: 'Lig op de rug. Kettlebell overhead. Rol langzaam naar de zijkant terwijl de arm omhoog blijft. Schoudermobiliteit.',
    beschrijving: 'Lig op de rug. Houd de kettlebell overhead met gestrekte arm. Rol langzaam naar de zijkant van de kettlebell — heup gaat omhoog, bovenbeen wijst omhoog. Houd de arm gestrekt gedurende de hele beweging. Houd de positie vast.',
    tips: ['Houd de arm gestrekt', 'Beweeg langzaam', 'Voel de schoudermobiliteit', 'Adem diep in de positie'],
    fouten: ['Arm buigen', 'Te snel bewegen', 'Schouder van de grond optillen'],
    primaireSpieren: ['Rotatorenmanchet', 'Schouders'],
    secundaireSpieren: ['Thoracale wervelkolom', 'Rug'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-hip-hinge-drill',
    naam: 'Hip Hinge Drill',
    categorie: 'mobiliteit',
    lichaamsdelen: ['benen', 'rug'],
    doelen: ['mobiliteit', 'warmup', 'herstel'],
    niveau: 'beginner',
    herhalingen: '10-15',
    uitleg: 'Leer en oefen de hinge beweging met een lichte kettlebell. Fundamenteel voor alle kettlebell oefeningen.',
    beschrijving: 'Houd een lichte kettlebell voor je dijen. Duw je heupen naar achteren — hinge vanuit de heupen. Rug recht. Ga totdat je hamstrings een lichte stretch voelen. Kom omhoog via de bilspieren. Langzaam en bewust.',
    tips: ['Hinge vanuit de heupen — niet de rug', 'Rug recht houden', 'Voel de hamstring stretch', 'Bilspieren aanspannen bij omhoog'],
    fouten: ['Rug afronden', 'Knieën te veel buigen', 'Te snel'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-bottom-up-hold',
    naam: 'Bottom-Up Hold',
    categorie: 'mobiliteit',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht', 'mobiliteit'],
    niveau: 'gemiddeld',
    duur: 20,
    uitleg: 'Houd de kettlebell ondersteboven in rack positie. Extremale grip en schouderstabiliteit. Statische oefening.',
    beschrijving: 'Breng de kettlebell naar de rack positie ondersteboven. Houd de positie vast gedurende de ingestelde tijd. Maximale grip aanspanning. Schouder actief stabiliseren.',
    tips: ['Maximale grip', 'Elleboog naar voren', 'Schouder actief', 'Begin met een licht gewicht'],
    fouten: ['Grip te los', 'Elleboog niet naar voren', 'Te zwaar'],
    primaireSpieren: ['Onderarmen', 'Rotatorenmanchet'],
    secundaireSpieren: ['Schouders', 'Core'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-overhead-hold',
    naam: 'Overhead Hold',
    categorie: 'mobiliteit',
    lichaamsdelen: ['schouders'],
    doelen: ['kracht', 'mobiliteit'],
    niveau: 'beginner',
    duur: 20,
    uitleg: 'Houd de kettlebell overhead met gestrekte arm. Statische schouderoefening. Stabiliteit en kracht.',
    beschrijving: 'Breng de kettlebell overhead. Arm volledig gestrekt. Houd de positie. Schouder actief stabiliseren — niet passief hangen. Houd stabiel.',
    tips: ['Arm volledig gestrekt', 'Schouder actief — niet laten hangen', 'Core actief', 'Kijk naar de kettlebell'],
    fouten: ['Arm buigen', 'Schouder passief hangen', 'Core laten zakken'],
    primaireSpieren: ['Schouders', 'Trapezius'],
    secundaireSpieren: ['Triceps', 'Core'],
    herstel: false,
    mobiliteit: true,
  },
  {
    id: 'kb-rack-hold',
    naam: 'Rack Hold',
    categorie: 'mobiliteit',
    lichaamsdelen: ['schouders', 'core'],
    doelen: ['kracht', 'mobiliteit'],
    niveau: 'beginner',
    duur: 30,
    uitleg: 'Houd de kettlebell in rack positie. Statische oefening voor rack techniek en schouderstabiliteit.',
    beschrijving: 'Breng de kettlebell naar rack positie. Elleboog omhoog, kettlebell op de onderarm. Houd de positie. Gebruik voor het oefenen van de rack positie voor press en squat.',
    tips: ['Elleboog hoog houden', 'Kettlebell ruht op de onderarm', 'Core actief', 'Schouder ontspannen maar stabiel'],
    fouten: ['Elleboog laten zakken', 'Kettlebell op de hand balanceren', 'Core laten zakken'],
    primaireSpieren: ['Schouders', 'Core'],
    secundaireSpieren: ['Trapezius', 'Biceps'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-shoulder-mobility-press',
    naam: 'Shoulder Mobility Press',
    beschrijving: 'Zeer lichte kettlebell. Langzame press in alle richtingen — voor, naar de zijkant, overhead. Mobiliseer de schoudergewrichten in het volledige bewegingsbereik.',
    categorie: 'mobiliteit',
    lichaamsdelen: ['schouders'],
    doelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    herhalingen: '10 per richting',
    uitleg: 'Lichte kettlebell press in meerdere richtingen. Schoudermobiliteit en activatie.',
    tips: ['Gebruik een heel licht gewicht', 'Beweeg langzaam en bewust', 'Voel elk deel van het bewegingsbereik', 'Geen pijn — mobiliteit'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Pijn negeren'],
    primaireSpieren: ['Rotatorenmanchet', 'Schouders'],
    secundaireSpieren: ['Trapezius', 'Bovenrug'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-thoracic-rotation',
    naam: 'Thoracale Rotatie met Kettlebell',
    categorie: 'mobiliteit',
    lichaamsdelen: ['rug'],
    doelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    herhalingen: '8 per kant',
    uitleg: 'Lig op je zij. Houd een lichte kettlebell. Roteer je bovenlichaam terwijl je de kettlebell volgt. Borstwervelkolom mobiliteit.',
    beschrijving: 'Lig op je zij met knieën gestapeld in 90 graden. Houd een lichte kettlebell met beide handen voor je. Roteer je bovenlichaam — volg de kettlebell met je blik. Laat de kettlebell de beweging leiden. Knieën blijven op de grond.',
    tips: ['Knieën blijven op de grond', 'Volg de kettlebell met je blik', 'Beweeg langzaam', 'Gebruik een heel lichte kettlebell'],
    fouten: ['Knieën optillen', 'Te snel', 'Te zwaar gewicht'],
    primaireSpieren: ['Thoracale wervelkolom', 'Rugspieren'],
    secundaireSpieren: ['Obliques', 'Schouders'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-controlled-deadlift',
    naam: 'Controlled Deadlift',
    categorie: 'mobiliteit',
    lichaamsdelen: ['benen', 'rug'],
    doelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    herhalingen: '8-10',
    uitleg: 'Deadlift met een langzaam tempo. Focus op mobiliteit en bewegingskwaliteit. Herstel oefening.',
    beschrijving: 'Kettlebell deadlift met een langzaam tempo — 4-5 seconden omlaag. Focus volledig op de kwaliteit van de hinge beweging. Gebruik als mobiliteitswerk of herstel.',
    tips: ['4-5 seconden omlaag', 'Focus op de hinge kwaliteit', 'Gebruik een lichte kettlebell', 'Voel elke spier werken'],
    fouten: ['Te zwaar gewicht', 'Te snel', 'Techniek negeren'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core'],
    herstel: true,
    mobiliteit: true,
  },
  {
    id: 'kb-tempo-carry',
    naam: 'Tempo Carry',
    categorie: 'mobiliteit',
    lichaamsdelen: ['core'],
    doelen: ['mobiliteit', 'herstel'],
    niveau: 'beginner',
    herhalingen: '20 meter',
    uitleg: 'Farmer carry op een zeer langzaam, bewust tempo. Focus op houding, ademhaling en het voelen van elke stap.',
    beschrijving: 'Pak een lichte kettlebell. Loop extreem langzaam — focus op elke stap. Bewust schouders omlaag. Adem diep en regelmatig. Voel de core werken bij elke stap.',
    tips: ['Extreem langzame stappen', 'Bewuste ademhaling', 'Voel de core bij elke stap', 'Gebruik een licht gewicht'],
    fouten: ['Te snel lopen', 'Ademhaling vergeten', 'Te zwaar gewicht'],
    primaireSpieren: ['Core', 'Onderarmen'],
    secundaireSpieren: ['Trapezius', 'Schouders'],
    herstel: true,
    mobiliteit: true,
  },

  // ── CONDITIONING (9) ──────────────────────────────────────────────────────

  {
    id: 'kb-swing-intervals',
    naam: 'Swing Intervallen',
    categorie: 'conditie',
    lichaamsdelen: ['billen', 'fullbody'],
    doelen: ['conditie'],
    niveau: 'beginner',
    duur: 600,
    uitleg: 'Afwisselend periodes van swings en rust. Bijv. 30 sec swings, 30 sec rust. 10 ronden. Conditionele training.',
    beschrijving: 'Voer swings uit gedurende 30 seconden. Rust 30 seconden. Herhaal 10 ronden. Pas de werk/rust verhouding aan op basis van conditieniveau.',
    tips: ['Houd de swing techniek op peil ook bij vermoeidheid', 'Adem bewust in de rustpauze', 'Pas het tempo aan op basis van conditie', 'Tel de herhalingen niet — focus op kwaliteit'],
    fouten: ['Techniek laten verslechteren', 'Te hard van start gaan', 'Geen ademhalingsritme'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Cardiovasculair systeem'],
    secundaireSpieren: ['Core', 'Rugspieren'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-emom-swings',
    naam: 'EMOM Swings',
    categorie: 'conditie',
    lichaamsdelen: ['billen', 'fullbody'],
    doelen: ['conditie', 'kracht'],
    niveau: 'beginner',
    duur: 600,
    uitleg: 'Elke minuut een vaste set swings uitvoeren. De resterende tijd is rust. Gestructureerde training.',
    beschrijving: 'Aan het begin van elke minuut doe je een vaste set swings — bijv. 15 swings. De resterende tijd in die minuut is rust. Herhaal 10-20 minuten. Pas het aantal swings aan op basis van je niveau.',
    tips: ['Kies een rep aantal waarbij je nog 20-30 sec rust hebt', 'Consistente techniek elke minuut', 'Noteer de totale reps', 'Verhoog geleidelijk de reps per minuut'],
    fouten: ['Te veel reps per minuut — geen rust', 'Techniek verslechtering', 'Geen consistentie'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-clean-ladder',
    naam: 'Clean Ladder',
    categorie: 'conditie',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '1-2-3-4-5 reps (ladder)',
    uitleg: 'Oplopende reps clean: 1, 2, 3, 4, 5. Dan terug omlaag. Conditionele training met technische focus.',
    beschrijving: 'Voer 1 clean uit. Rust kort. Voer 2 cleans uit. Rust kort. Omhoog tot 5. Dan terug omlaag. Dat is één ronde. Herhaal meerdere ronden met een grotere rust tussen ronden.',
    tips: ['Consistente clean techniek door de ladder', 'Korte rust tussen sets in de ladder', 'Langere rust tussen ronden', 'Begin met lichtere gewichten'],
    fouten: ['Techniek verslechteren naarmate de reps toenemen', 'Te zwaar gewicht', 'Te weinig rust tussen ronden'],
    primaireSpieren: ['Bilspieren', 'Schouders', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-press-ladder',
    naam: 'Press Ladder',
    categorie: 'conditie',
    lichaamsdelen: ['schouders', 'armen'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '1-2-3-4-5 per arm',
    uitleg: 'Oplopende reps press: 1, 2, 3, 4, 5 per arm. Klassieke kettlebell krachtprotocol van Pavel Tsatsouline.',
    beschrijving: 'Press met rechterarm: 1 rep. Wissel naar links: 1 rep. Dan 2-2, 3-3 etc. tot 5-5. Dan terug omlaag. Dat is één ronde. Rust en herhaal. Gebruikt in het klassieke \'Enter the Kettlebell\' programma.',
    tips: ['Consistente press techniek', 'Wissel soepel van arm', 'Gebruik een gewicht waarbij je 5 reps comfortabel kunt', 'Langere rust tussen ronden'],
    fouten: ['Te zwaar gewicht voor de hogere reps', 'Geen consistentie in techniek', 'Te weinig rust tussen ronden'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-swing-ladder',
    naam: 'Swing Ladder',
    categorie: 'conditie',
    lichaamsdelen: ['billen', 'fullbody'],
    doelen: ['conditie'],
    niveau: 'beginner',
    herhalingen: '10-20-30-40-50 swings',
    uitleg: 'Oplopende reps swings met rust. 10, 20, 30, 40, 50 swings. Verhoogt het volume geleidelijk.',
    beschrijving: 'Voer 10 swings uit. Rust 30-60 seconden. Voer 20 swings uit. Rust etc. Omhoog tot 50 swings. Dat is 150 swings totaal. Conditionele challenge.',
    tips: ['Houd swing techniek op peil door de ladder', 'Gebruik de rust volledig', 'Pas de rustperiode aan op conditie', 'Noteer totale tijd'],
    fouten: ['Te weinig rust', 'Techniek verslechteren bij hogere reps', 'Te zwaar gewicht'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-snatch-intervals',
    naam: 'Snatch Intervallen',
    categorie: 'conditie',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie', 'ballistisch'],
    niveau: 'gevorderd',
    duur: 600,
    uitleg: 'Intervallen van snatches. Bijv. 8 snatches per arm per minuut gedurende 10 minuten. Extreme uitdaging.',
    beschrijving: 'Voer een vaste set snatches per arm uit. Rust de rest van de minuut. Herhaal 10 minuten. Vereist perfecte snatchtechniek en een goede conditiebasis.',
    tips: ['Perfecte snatchtechniek vereist', 'Begin met minder reps per minuut', 'Adem bewust in de rust', 'Pacing is cruciaal'],
    fouten: ['Slechte snatchtechniek', 'Te veel reps per minuut', 'Geen pacing'],
    primaireSpieren: ['Bilspieren', 'Schouders', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-carry-circuit',
    naam: 'Carry Circuit',
    categorie: 'conditie',
    lichaamsdelen: ['core', 'fullbody'],
    doelen: ['conditie', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '3-4 ronden',
    uitleg: 'Circuit van verschillende carry varianten. Farmer → Rack → Overhead → Suitcase. Elke variant 20 meter.',
    beschrijving: 'Voer achtereenvolgens uit: 20 meter farmer carry, 20 meter rack carry (per arm), 20 meter overhead carry (per arm), 20 meter suitcase carry (per arm). Rust 90 sec tussen ronden.',
    tips: ['Houd goede positie in alle carry varianten', 'Plan de route van tevoren', 'Rust 90 sec tussen ronden', 'Gebruik matig gewicht'],
    fouten: ['Te zwaar gewicht', 'Positie verliezen', 'Te weinig rust'],
    primaireSpieren: ['Core', 'Onderarmen', 'Schouders'],
    secundaireSpieren: ['Trapezius', 'Benen', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-conditioning-circuit',
    naam: 'Conditioning Circuit',
    categorie: 'conditie',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie'],
    niveau: 'gemiddeld',
    herhalingen: '3-4 ronden',
    uitleg: 'Circuit van 5 oefeningen: swing, clean, press, squat, row. 10 reps per oefening zonder rust. Volledig lichaam conditioning.',
    beschrijving: 'Voer achtereenvolgens uit: 10 swings, 5 cleans per arm, 5 presses per arm, 10 goblet squats, 10 rows. Minimale rust tussen oefeningen. Rust 2-3 min tussen ronden.',
    tips: ['Kies een gewicht waarbij alle oefeningen technisch correct zijn', 'Minimale rust tussen oefeningen', '2-3 min rust tussen ronden', 'Pas het gewicht aan'],
    fouten: ['Te zwaar gewicht', 'Techniek verslechteren', 'Te weinig rust tussen ronden'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Cardiovasculair systeem', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-kettlebell-complexes',
    naam: 'Kettlebell Complex',
    categorie: 'conditie',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie', 'kracht'],
    niveau: 'gemiddeld',
    herhalingen: '4-5 ronden',
    uitleg: 'Meerdere oefeningen achter elkaar met dezelfde kettlebell zonder neer te zetten. Swing + Clean + Press + Squat. Kracht en conditie tegelijk.',
    beschrijving: 'Met één kettlebell: 5 swings, 5 cleans (zelfde arm), 5 presses (zelfde arm), 5 front squats. Wissel arm. Dat is één ronde. Rust 2 min. Herhaal. De kettlebell wordt niet neer gezet.',
    tips: ['Kettlebell niet neerleggen', 'Gebruik een gewicht waarbij je alle oefeningen kunt', 'Rust 2 min tussen ronden', 'Begin met een licht gewicht'],
    fouten: ['Te zwaar gewicht', 'Kettlebell neerleggen', 'Techniek verslechteren'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },

  // ── COMPLEXES & FLOWS (9) ─────────────────────────────────────────────────

  {
    id: 'kb-armor-building',
    naam: 'Armor Building Complex',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gevorderd',
    herhalingen: '6 ronden',
    uitleg: '2 cleans + 1 press + 3 front squats. Herhaal 6 ronden per arm. Klassiek Dan John complex voor kracht opbouw.',
    beschrijving: 'Met één kettlebell per arm: 2 cleans, 1 press, 3 front squats. Dat is één ronde. Doe 6 ronden per arm. Rust 90 sec per arm. Verhoog het gewicht als de 6 ronden goed voelen.',
    tips: ['Leer elke oefening apart eerst', 'Consistente techniek door alle ronden', 'Rust 90 sec per arm', 'Verhoog gewicht geleidelijk'],
    fouten: ['Te zwaar voor de front squats', 'Techniek verslechteren bij vermoeidheid', 'Te weinig rust'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-clean-squat-press',
    naam: 'Clean + Front Squat + Press',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '5 per arm',
    uitleg: 'Clean, front squat, press als één flow. Drie fundamentele kettlebell bewegingen gecombineerd.',
    beschrijving: 'Clean naar rack. Front squat omlaag en omhoog. Press overhead. Laat zakken naar rack. Dat is één herhaling. Doe 5 per arm. Rust. Vloeiende overgang tussen de drie bewegingen.',
    tips: ['Vloeiende overgang tussen de bewegingen', 'Rack positie is de verbindende schakel', 'Consistent tempo', 'Begin licht'],
    fouten: ['Slechte rack positie', 'Te snel wisselen', 'Te zwaar gewicht'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-clean-press-lunge',
    naam: 'Clean + Press + Reverse Lunge',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'conditie'],
    niveau: 'gemiddeld',
    herhalingen: '5 per kant',
    uitleg: 'Clean, press, reverse lunge. Drie bewegingen in één flow. Full body kracht en conditie.',
    beschrijving: 'Clean naar rack. Press overhead. Laat zakken naar rack. Reverse lunge achterwaarts. Kom omhoog. Dat is één herhaling. Doe 5 per kant.',
    tips: ['Vloeiende bewegingen', 'Houd de press overhead tijdens de lunge', 'Of doe de lunge na het zakken van de press', 'Houd romp recht tijdens de lunge'],
    fouten: ['Romp naar voren bij de lunge', 'Slechte press techniek', 'Te zwaar'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-swing-clean-press',
    naam: 'Swing + Clean + Press',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'conditie', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '5 per arm',
    uitleg: 'Swing die overgaat in een clean die overgaat in een press. Ballistische flow die kracht en conditie combineert.',
    beschrijving: 'Begin met swings. Na een swing trek je direct door naar een clean. Na de clean druk je direct door naar een press. Laat zakken en terug naar swing. Vloeiende ballistische flow.',
    tips: ['Vloeiende overgang van swing naar clean', 'Clean en press kunnen direct op elkaar volgen', 'Houd een consistent ritme', 'Begin licht voor de techniek'],
    fouten: ['Stops tussen de bewegingen', 'Slechte clean techniek', 'Te zwaar gewicht'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-double-clean-squat',
    naam: 'Double Clean + Front Squat',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht'],
    niveau: 'gevorderd',
    herhalingen: '5',
    uitleg: 'Double clean gevolgd door een double front squat. Zwaar en technisch. Voor gevorderden.',
    beschrijving: 'Twee kettlebells. Clean beide naar dubbele rack. Voer een front squat uit. Laat zakken naar rack. Herhaal of laat zakken naar de grond en opnieuw beginnen. Zware compound oefening.',
    tips: ['Perfecte double clean techniek vereist', 'Beide ellebogen hoog in de squat', 'Begin met lichtere kettlebells', 'Focus op techniek'],
    fouten: ['Slechte double clean techniek', 'Ellebogen zakken in de squat', 'Te zwaar'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-long-cycle-complex',
    naam: 'Long Cycle Complex',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '5 minuten',
    uitleg: 'Uitgebreide versie van long cycle met extra oefeningen. Clean & Jerk met squat of carry toevoegingen.',
    beschrijving: 'Clean & Jerk. Na elke 5 ronden voeg je een extra squat toe of een carry. Creëert een volledig programma in één complex.',
    tips: ['Bouw het complex geleidelijk op', 'Techniek boven alles', 'Plan de extra oefeningen van tevoren', 'Rust genoeg'],
    fouten: ['Te ingewikkeld voor het niveau', 'Techniek verslechteren', 'Te zwaar'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-snatch-complex',
    naam: 'Snatch Complex',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht', 'ballistisch', 'conditie'],
    niveau: 'gevorderd',
    herhalingen: '5 per arm',
    uitleg: 'Snatch gecombineerd met andere oefeningen. Bijv. snatch + windmill + snatch + squat. Technische flow.',
    beschrijving: 'Snatch. Windmill. Snatch terug. Squat. Dat is één complexe herhaling. Vereist goede beheersing van alle individuele oefeningen. Begin zonder gewicht.',
    tips: ['Leer alle oefeningen apart eerst', 'Begin zonder gewicht', 'Vloeiende overgangen', 'Kwaliteit boven alles'],
    fouten: ['Te snel progressie', 'Slechte individuele technieken', 'Te zwaar gewicht'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-strength-flow',
    naam: 'Strength Flow',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['kracht'],
    niveau: 'gevorderd',
    herhalingen: '5 per kant',
    uitleg: 'Deadlift + Clean + Front Squat + Press + Lunge. Vijf fundamentele bewegingen als één vloeiende flow.',
    beschrijving: 'Met één kettlebell: deadlift omhoog, clean naar rack, front squat, press overhead, laat zakken, reverse lunge. Dat is één herhaling. Vloeiende overgang tussen alle bewegingen.',
    tips: ['Elke overgang vloeiend', 'Consistente techniek door de flow', 'Begin licht', 'Focus op kwaliteit'],
    fouten: ['Te zwaar gewicht', 'Techniek verslechteren', 'Stops tussen de bewegingen'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core'],
    herstel: false,
    mobiliteit: false,
  },
  {
    id: 'kb-conditioning-flow',
    naam: 'Conditioning Flow',
    categorie: 'complex',
    lichaamsdelen: ['fullbody'],
    doelen: ['conditie', 'ballistisch'],
    niveau: 'gevorderd',
    herhalingen: '10-15 minuten',
    uitleg: 'Vrije flow van kettlebell oefeningen voor een bepaalde tijd. Swing, clean, press, squat, carry naar eigen keuze en gevoel.',
    beschrijving: 'Voer kettlebell oefeningen uit in een vrij vloeiende volgorde voor 10-15 minuten. Wissel oefeningen naar eigen gevoel en vermoeidheid. Goed voor gevorderden die hun repertoire goed kennen.',
    tips: ['Ken alle individuele oefeningen goed', 'Volg je lichaam en gevoel', 'Houd een consistent tempo', 'Kwaliteit altijd boven volume'],
    fouten: ['Slechte techniek', 'Te zwaar gewicht', 'Te lang doorgaan'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Cardiovasculair systeem', 'Core'],
    herstel: false,
    mobiliteit: false,
  },
]

// ── Hulpfuncties voor de route ─────────────────────────────────────────────

/**
 * Filtert oefeningen op kettlebellDoel.
 * Wordt gebruikt in training/today/route.ts — Optie C architectuur.
 */
export function filterKettlebell(
  doel: KettlebellDoel,
  niveau?: KettlebellNiveau
): KettlebellOefening[] {
  return KETTLEBELL_OEFENINGEN.filter(o =>
    o.doelen.includes(doel) &&
    (niveau ? o.niveau === niveau || o.niveau === 'beginner' : true)
  )
}

/**
 * Filtert op niveau — geeft alle oefeningen van dat niveau en lager.
 */
export function filterKettlebellNiveau(niveau: KettlebellNiveau): KettlebellOefening[] {
  const niveauRang = { beginner: 0, gemiddeld: 1, gevorderd: 2 }
  return KETTLEBELL_OEFENINGEN.filter(o => niveauRang[o.niveau] <= niveauRang[niveau])
}

/**
 * Geeft een korte prompt-vriendelijke lijst van oefeningen terug.
 * Wordt direct in de Trainer AI prompt geplakt.
 */
export function formateerKettlebellVoorPrompt(oefeningen: KettlebellOefening[]): string {
  return oefeningen.map(o =>
    `- ${o.naam} (${o.niveau}, ${o.categorie}, ${o.lichaamsdelen.join('/')}): ${o.uitleg}`
  ).join('\n')
}
