// ── CoachOS Strength Bibliotheek — Fase 1 ────────────────────────────────────
// 30 oefeningen: 10 dumbbell, 10 barbell, 10 both/warmup/herstel/conditie.
// Architectuur identiek aan bodyweight-exercises.ts:
// Coach bepaalt doel + equipment → route filtert → Trainer AI assembleert.
// Trainer AI mag GEEN nieuwe oefeningen verzinnen buiten de gefilterde lijst.

export type KrachtDoel =
  | 'kracht'
  | 'hypertrofie'
  | 'conditie'
  | 'herstel'
  | 'warmup'

export type Equipment =
  | 'dumbbell'
  | 'barbell'
  | 'both'

export type StrengthNiveau = 'beginner' | 'gemiddeld' | 'gevorderd'

export type StrengthLichaamsdeel =
  | 'benen'
  | 'billen'
  | 'rug'
  | 'borst'
  | 'schouders'
  | 'armen'
  | 'core'
  | 'fullbody'

export interface StrengthOefening {
  id: string
  naam: string
  beschrijving: string
  uitleg: string           // korte prompt-vriendelijke versie
  doel: KrachtDoel[]
  lichaamsdelen: StrengthLichaamsdeel[]
  niveau: StrengthNiveau
  equipment: Equipment[]
  sets?: string            // bijv. "3-4"
  herhalingen?: string     // bijv. "8-12"
  tempo?: string           // bijv. "3-1-1" (excentrisch-pauze-concentrisch)
  tips: string[]
  fouten: string[]
  primaireSpieren: string[]
  secundaireSpieren: string[]
}

export const STRENGTH_OEFENINGEN: StrengthOefening[] = [

  // ── DUMBBELL (10) ─────────────────────────────────────────────────────────

  {
    id: 'goblet-squat-db',
    naam: 'Goblet Squat',
    beschrijving: 'Houd een dumbbell verticaal voor je borst. Sta met voeten op schouderbreedte. Zak diep door de knieën terwijl je borst omhoog blijft. Drijf omhoog via de hielen. Uitstekende squat voor beginners door de counterbalance van de dumbbell.',
    uitleg: 'Dumbbell voor de borst houden, diep squatten. Goed voor beginners en mobiliteit.',
    doel: ['kracht', 'hypertrofie', 'warmup'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-15',
    tempo: '3-1-1',
    tips: ['Ellebogen drukken knieën naar buiten', 'Hiel blijft op de grond', 'Borst omhoog houden', 'Dumbbell close tegen je borst'],
    fouten: ['Borst naar voren vallen', 'Knieën naar binnen zakken', 'Onvoldoende diepte'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Bovenrug'],
  },
  {
    id: 'dumbbell-bench-press',
    naam: 'Dumbbell Bench Press',
    beschrijving: 'Lig op een bank met een dumbbell in elke hand ter hoogte van je borst. Duw beide dumbbells omhoog totdat je armen gestrekt zijn. Laat gecontroleerd zakken. De dumbbells geven een grotere bewegingsvrijheid dan een barbell.',
    uitleg: 'Liggend op een bank twee dumbbells omhoog drukken. Traint borstspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Schouderbladen samenknijpen op de bank', 'Ellebogen op 45 graden', 'Dumbbells boven borst — niet boven schouders', 'Voeten plat op de grond'],
    fouten: ['Ellebogen te wijd — 90 graden', 'Heupen optillen', 'Dumbbells niet laten zakken tot borstniveau'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Serratus anterior'],
  },
  {
    id: 'dumbbell-row',
    naam: 'Dumbbell Row',
    beschrijving: 'Knie en hand op een bank voor steun. Houd een dumbbell in de andere hand. Trek de dumbbell omhoog naar je heup — elleboog gaat recht omhoog langs je lichaam. Laat gecontroleerd zakken. Traint eenzijdig de rugspieren.',
    uitleg: 'Eénzijdige rugtraining — dumbbell optrekken naar de heup. Knie en hand op bank.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Elleboog recht langs het lichaam omhoog', 'Rug recht — niet roteren', 'Trek naar je heup — niet je schouder', 'Schouderblad samentrekken bovenin'],
    fouten: ['Romp roteren voor meer bereik', 'Elleboog te ver naar buiten', 'Momentum gebruiken'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Achterste schouder', 'Core'],
  },
  {
    id: 'dumbbell-curl',
    naam: 'Dumbbell Biceps Curl',
    beschrijving: 'Sta rechtop met een dumbbell in elke hand, armen langs je lichaam. Curl beide dumbbells omhoog naar je schouders terwijl je je ellebogen stil houdt. Laat gecontroleerd zakken. Draai je polsen tijdens de beweging.',
    uitleg: 'Staand twee dumbbells naar de schouders curlen. Bicepstraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10-15',
    tempo: '2-1-2',
    tips: ['Ellebogen stil aan je zij', 'Draai polsen bij het omhoog curlen', 'Volledig strekken onderaan', 'Beweeg gecontroleerd — geen schommelen'],
    fouten: ['Ellebogen naar voren bewegen', 'Romp schommelen voor momentum', 'Niet volledig strekken'],
    primaireSpieren: ['Biceps brachii'],
    secundaireSpieren: ['Brachialis', 'Onderarmen'],
  },
  {
    id: 'dumbbell-lunge',
    naam: 'Dumbbell Lunge',
    beschrijving: 'Houd een dumbbell in elke hand langs je lichaam. Stap naar voren in een lunge. Laat je achterste knie zakken naar de grond. Drijf omhoog via je voorste been. Stap terug of ga door naar de volgende stap.',
    uitleg: 'Lunge met dumbbells in de handen. Traint benen en bilspieren eenzijdig.',
    doel: ['kracht', 'hypertrofie', 'conditie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10 per been',
    tempo: '2-1-1',
    tips: ['Romp rechtop houden', 'Voorste knie boven de enkel', 'Stap breed genoeg', 'Bilspieren aanspannen bij het omhoog komen'],
    fouten: ['Romp naar voren leunen', 'Voorste knie over de teen', 'Te kleine stap'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
  },
  {
    id: 'dumbbell-shoulder-press',
    naam: 'Dumbbell Shoulder Press',
    beschrijving: 'Zit of sta met een dumbbell in elke hand ter hoogte van je schouders. Duw beide dumbbells recht omhoog totdat je armen gestrekt zijn. Laat gecontroleerd zakken. Traint de schouders.',
    uitleg: 'Dumbbells vanaf schouderhoogte omhoog drukken. Schoudertraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['schouders'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Core actief houden — niet hol trekken', 'Druk recht omhoog — niet naar voren', 'Ellebogen naar voren — niet naar de zijkant', 'Volledig strekken bovenin'],
    fouten: ['Rug hol trekken', 'Dumbbells naar voren drukken', 'Onvoldoende strekken'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Trapezius', 'Core'],
  },
  {
    id: 'romanian-deadlift-db',
    naam: 'Romanian Deadlift Dumbbell',
    beschrijving: 'Houd een dumbbell in elke hand voor je dijen. Buig naar voren vanuit je heupen terwijl je rug recht blijft. Laat de dumbbells langs je benen zakken. Kom omhoog via je bilspieren. Voel de stretch in je hamstrings.',
    uitleg: 'Dumbbell RDL — buigen vanuit de heupen met rechte rug. Hamstrings en bilspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Buig vanuit de heupen — niet de rug', 'Rug recht houden — lichte natuurlijke curve', 'Dumbbells dicht langs de benen', 'Bilspieren aanspannen bij het omhoog komen'],
    fouten: ['Rug afronden', 'Knieën te veel buigen — dit is geen squat', 'Dumbbells te ver van het lichaam'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core'],
  },
  {
    id: 'dumbbell-incline-press',
    naam: 'Incline Dumbbell Press',
    beschrijving: 'Lig op een schuine bank (30-45 graden). Houd een dumbbell in elke hand ter hoogte van je borst. Duw omhoog. Traint de bovenkant van de borstspieren meer dan een vlakke bank.',
    uitleg: 'Dumbbell press op een schuine bank. Bovenkant borst en schouders.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Bank niet te steil — 30-45 graden is optimaal', 'Schouderbladen samenknijpen', 'Ellebogen op 45-60 graden', 'Dumbbells boven het bovenste deel van de borst'],
    fouten: ['Bank te steil — wordt een schouderpress', 'Ellebogen te wijd', 'Heupen optillen'],
    primaireSpieren: ['Bovenkant borstspieren', 'Schouders'],
    secundaireSpieren: ['Triceps', 'Serratus anterior'],
  },
  {
    id: 'lateral-raise-db',
    naam: 'Lateral Raise',
    beschrijving: 'Sta rechtop met een dumbbell in elke hand langs je lichaam. Hef beide armen tegelijk zijwaarts op tot schouderhoogte. Laat gecontroleerd zakken. Traint de zijkant van de schouders.',
    uitleg: 'Dumbbells zijwaarts opheffen tot schouderhoogte. Zijkant schouder.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['schouders'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '2-1-2',
    tips: ['Kleine pinky iets omhoog — als water uitschenken', 'Licht gebogen elleboog', 'Niet hoger dan schouderhoogte', 'Beweeg langzaam omlaag'],
    fouten: ['Momentum gebruiken — schommelen', 'Te zwaar gewicht', 'Armen te hoog heffen', 'Schouders optrekken'],
    primaireSpieren: ['Zijkant schouder', 'Mediale deltoid'],
    secundaireSpieren: ['Trapezius', 'Supraspinatus'],
  },
  {
    id: 'triceps-extension-db',
    naam: 'Dumbbell Triceps Extension',
    beschrijving: 'Zit of sta met één of twee dumbbells boven je hoofd. Laat de dumbbell(s) zakken achter je hoofd door je ellebogen te buigen. Strek omhoog. Traint de triceps.',
    uitleg: 'Dumbbell boven het hoofd zakken achter de nek. Tricepstraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '12-15',
    tempo: '2-1-2',
    tips: ['Ellebogen dicht bij het hoofd houden', 'Bovenarmem stil — alleen onderarmen bewegen', 'Volledig strekken bovenin', 'Gebruik beide handen bij één zware dumbbell'],
    fouten: ['Ellebogen naar buiten bewegen', 'Bovenarmem meebewegen', 'Te zwaar gewicht'],
    primaireSpieren: ['Triceps brachii'],
    secundaireSpieren: ['Schouders'],
  },

  // ── BARBELL (10) ──────────────────────────────────────────────────────────

  {
    id: 'barbell-back-squat',
    naam: 'Back Squat',
    beschrijving: 'Barbell op de bovenrug. Voeten op schouderbreedte. Zak diep door de knieën terwijl je borst omhoog blijft en je rug recht. Drijf omhoog via de hielen. De koning van de krachtoefeningen voor de benen.',
    uitleg: 'Barbell op de rug, diep squatten. Meest effectieve beentraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '5-8',
    tempo: '3-1-1',
    tips: ['Barbell op de trapezius — niet op de nek', 'Borst omhoog, rug recht', 'Knieën volgen de richting van de tenen', 'Drijf via de hielen omhoog'],
    fouten: ['Borst naar voren vallen in de bodem', 'Knieën naar binnen zakken', 'Hielen optillen', 'Barbell te hoog op de nek'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Bovenrug'],
  },
  {
    id: 'barbell-deadlift',
    naam: 'Deadlift',
    beschrijving: 'Barbell op de grond voor je voeten. Handen op schouderbreedte op de stang. Rug recht, bilspieren aanspannen, trek de stang omhoog langs je benen door te strekken vanuit heupen en knieën tegelijk. Zet neer via dezelfde weg.',
    uitleg: 'Barbell van de grond optillen. Traint de volledige achterkant van het lichaam.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '3-6',
    tempo: '2-1-1',
    tips: ['Stang dicht langs de benen — schraapt bijna', 'Rug recht gedurende de hele beweging', 'Trek de spanning op voor je trekt', 'Bilspieren aanspannen bovenin'],
    fouten: ['Rug afronden', 'Stang te ver van het lichaam', 'Knieën eerst strekken voor de heupen'],
    primaireSpieren: ['Hamstrings', 'Bilspieren', 'Rugspieren'],
    secundaireSpieren: ['Quadriceps', 'Core', 'Trapezius'],
  },
  {
    id: 'barbell-bench-press',
    naam: 'Bench Press',
    beschrijving: 'Lig op een vlakke bank. Barbell iets breder dan schouderbreedte. Laat de stang zakken naar je borst — raak licht aan. Duw explosief omhoog. Voeten plat op de grond, schouderbladen samengeknepen.',
    uitleg: 'Barbell op een bank drukken. Klassieke borsttraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '5-10',
    tempo: '3-1-1',
    tips: ['Schouderbladen samenknijpen en in de bank drukken', 'Ellebogen op 45-75 graden', 'Stang raakt de borst — niet stuitert', 'Voeten plat op de grond'],
    fouten: ['Ellebogen te wijd — 90 graden', 'Heupen optillen van de bank', 'Stangen laten stuiteren op de borst', 'Polsen buigen'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Serratus anterior'],
  },
  {
    id: 'barbell-overhead-press',
    naam: 'Overhead Press',
    beschrijving: 'Sta rechtop met barbell op de voorkant van de schouders. Duw de stang recht omhoog. Beweeg je gezicht licht naar achteren bij het passeren van de stang. Strek volledig boven. Laat langzaam zakken.',
    uitleg: 'Barbell van de schouders recht omhoog drukken. Schouder- en tricepstraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['schouders', 'armen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-5',
    herhalingen: '5-8',
    tempo: '2-1-2',
    tips: ['Core strak — niet hol trekken', 'Beweeg gezicht naar achteren als stang passeert', 'Druk recht omhoog — niet naar voren', 'Bilspieren en core aanspannen voor stabiliteit'],
    fouten: ['Rug hol trekken', 'Stang naar voren drukken', 'Knieën buigen voor momentum'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Trapezius', 'Core', 'Bovenrug'],
  },
  {
    id: 'barbell-row',
    naam: 'Barbell Row',
    beschrijving: 'Leun voorover met rechte rug — romp bijna parallel aan de grond. Houd de barbell met overhand greep. Trek de stang naar je onderbuik. Laat gecontroleerd zakken. Traint de dikke rugspieren.',
    uitleg: 'Voorovergebogen barbell optrekken naar de buik. Rugtraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4',
    herhalingen: '6-10',
    tempo: '2-1-2',
    tips: ['Rug recht — lichte natuurlijke curve', 'Trek naar de onderbuik — niet de borst', 'Ellebogen dicht langs het lichaam', 'Schouderbladen samentrekken bovenin'],
    fouten: ['Rug afronden', 'Romp omhoog bewegen voor meer bereik', 'Trek naar de borst in plaats van de buik'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids', 'Trapezius'],
    secundaireSpieren: ['Biceps', 'Achterste schouder', 'Core'],
  },
  {
    id: 'romanian-deadlift-bb',
    naam: 'Romanian Deadlift Barbell',
    beschrijving: 'Houd de barbell met overhand greep voor je dijen. Buig naar voren vanuit de heupen — rug recht. Laat de stang langs je benen zakken. Voel de stretch in de hamstrings. Kom omhoog via de bilspieren.',
    uitleg: 'Barbell RDL — hinge beweging voor hamstrings en bilspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Stang dicht langs de benen', 'Rug recht — geen afronden', 'Knieën licht gebogen maar stabiel', 'Stop als de rug wil afronden'],
    fouten: ['Rug afronden onderaan', 'Knieën te veel buigen — geen squat', 'Stang te ver van het lichaam'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core', 'Kuiten'],
  },
  {
    id: 'barbell-hip-thrust',
    naam: 'Barbell Hip Thrust',
    beschrijving: 'Leun met schouders op een bank. Barbell op je heupen — gebruik een mat of pad. Voeten op de grond. Duw heupen omhoog terwijl je bilspieren maximaal aanspant. Houd 1-2 seconden vast. Laat zakken.',
    uitleg: 'Barbell op de heupen. Heupen omhoog duwen. Beste bilspier oefening.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-15',
    tempo: '2-2-1',
    tips: ['Kin naar borst — hoofd niet achterover', 'Bilspieren maximaal aanspannen bovenin', 'Voeten plat en heupbreedte', 'Gebruik altijd een pad op de heupen'],
    fouten: ['Hoofd achterover hangen', 'Rug hol trekken bovenin', 'Knieën naar binnen zakken'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Quadriceps'],
  },
  {
    id: 'front-squat',
    naam: 'Front Squat',
    beschrijving: 'Barbell op de voorkant van de schouders — armen gekruist of clean grip. Ellebogen hoog. Zak diep door de knieën. Meer nadruk op quadriceps dan back squat. Vereist goede mobiliteit.',
    uitleg: 'Barbell aan de voorkant op de schouders. Quad-gerichte squat.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4',
    herhalingen: '5-8',
    tempo: '3-1-1',
    tips: ['Ellebogen zo hoog mogelijk', 'Borst omhoog — niet laten zakken', 'Knieën ver naar voren — over de teen', 'Goede enkelmobiliteit vereist'],
    fouten: ['Ellebogen zakken — stang rolt eraf', 'Borst naar voren vallen', 'Onvoldoende enkelmobiliteit'],
    primaireSpieren: ['Quadriceps'],
    secundaireSpieren: ['Bilspieren', 'Core', 'Bovenrug'],
  },
  {
    id: 'pendlay-row',
    naam: 'Pendlay Row',
    beschrijving: 'Barbell op de grond. Sta met voeten op heupbreedte. Rug parallel aan de grond. Trek de stang explosief naar je borst. Laat terug op de grond zakken. Elke herhaling start vanuit stilstand.',
    uitleg: 'Explosive barbell row vanuit de grond. Krachtige rugtraining.',
    doel: ['kracht'],
    lichaamsdelen: ['rug'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '5-6',
    tempo: '1-1-2',
    tips: ['Rug parallel aan de grond', 'Explosief omhoog trekken', 'Stang terug op de grond laten zakken', 'Trek naar de borst — niet de buik'],
    fouten: ['Romp omhoog bewegen', 'Niet terug op de grond zetten', 'Rug niet parallel'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids', 'Trapezius'],
    secundaireSpieren: ['Biceps', 'Core', 'Achterste schouder'],
  },
  {
    id: 'barbell-good-morning',
    naam: 'Good Morning Barbell',
    beschrijving: 'Barbell op de bovenrug zoals bij een squat. Buig naar voren vanuit de heupen terwijl je rug recht blijft. Ga totdat je romp bijna parallel is aan de grond. Kom omhoog via de bilspieren en hamstrings.',
    uitleg: 'Barbell op de rug, voorover buigen vanuit heupen. Hamstrings en rugspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Rug recht gedurende de hele beweging', 'Buig vanuit de heupen — niet de rug', 'Knieën licht gebogen', 'Begin licht — goed voor mobiliteit'],
    fouten: ['Rug afronden', 'Te snel bewegen', 'Te zwaar beginnen'],
    primaireSpieren: ['Hamstrings', 'Rugspieren'],
    secundaireSpieren: ['Bilspieren', 'Core'],
  },

  // ── BOTH / WARMUP / HERSTEL / CONDITIE (10) ───────────────────────────────

  {
    id: 'empty-bar-squat',
    naam: 'Lege Stang Squat',
    beschrijving: 'Squat met alleen de lege barbell als opwarmoefening. Focus op techniek, mobiliteit en bewegingspatroon. Perfecte warming-up voor zware squat sessies.',
    uitleg: 'Squat met lege stang. Techniek oefenen en opwarmen voor de sessie.',
    doel: ['warmup'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['barbell'],
    sets: '2-3',
    herhalingen: '10-15',
    tempo: '3-1-1',
    tips: ['Focus op techniek — niet op gewicht', 'Voel elke fase van de squat', 'Houd een langzaam tempo', 'Gebruik dit om mobiliteit te checken'],
    fouten: ['Te snel bewegen', 'Techniek negeren', 'Direct naar zwaar gewicht'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core'],
  },
  {
    id: 'goblet-squat-tempo',
    naam: 'Goblet Squat Tempo',
    beschrijving: 'Goblet squat met een langzaam gecontroleerd tempo — 5 seconden omlaag, 2 seconden vasthouden in de bodem, 1 seconde omhoog. Traint mobiliteit en lichaamsbewustzijn.',
    uitleg: 'Langzame goblet squat voor mobiliteit en techniekwerk. 5-2-1 tempo.',
    doel: ['warmup', 'herstel'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '6-8',
    tempo: '5-2-1',
    tips: ['Neem de volle 5 seconden omlaag', 'Voel de stretch in de bodem', 'Gebruik een licht gewicht', 'Focus op positie en balans'],
    fouten: ['Te snel bewegen', 'Te zwaar gewicht', 'Borst naar voren vallen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Enkels'],
  },
  {
    id: 'hinge-drill',
    naam: 'Hinge Drill',
    beschrijving: 'Sta met de rug langs een muur. Strek een barbell of stok achter je rug — contact op hoofd, bovenrug en billen. Oefen de hinge beweging door je heupen naar achteren te duwen terwijl je drie contactpunten behoudt.',
    uitleg: 'Stok of lege stang achter de rug. Oefent de hinge beweging voor deadlifts.',
    doel: ['warmup'],
    lichaamsdelen: ['rug', 'benen'],
    niveau: 'beginner',
    equipment: ['barbell', 'both'],
    sets: '3',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Drie contactpunten: hoofd, bovenrug, billen', 'Duw heupen naar achteren — niet naar beneden', 'Rug recht houden', 'Gebruik dit dagelijks als mobiliteitsroutine'],
    fouten: ['Contactpunten verliezen', 'Knieën te veel buigen', 'Rug afronden'],
    primaireSpieren: ['Hamstrings', 'Rugspieren'],
    secundaireSpieren: ['Bilspieren', 'Core'],
  },
  {
    id: 'light-rdl-mobility',
    naam: 'Lichte RDL Mobiliteit',
    beschrijving: 'Romanian deadlift met een zeer licht gewicht — focus volledig op mobiliteit en het voelen van de hamstrings. Ideaal als herstel of mobiliteitswerk op lichte dagen.',
    uitleg: 'Zeer lichte RDL als mobiliteits- en herstelloefening. Voelen niet laden.',
    doel: ['herstel', 'warmup'],
    lichaamsdelen: ['benen', 'rug'],
    niveau: 'beginner',
    equipment: ['dumbbell', 'barbell'],
    sets: '2-3',
    herhalingen: '12-15',
    tempo: '4-2-1',
    tips: ['Gebruik een heel licht gewicht', 'Focus op het voelen van de hamstrings', 'Langzaam en gecontroleerd', 'Ideaal voor hersteldag'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Rug afronden'],
    primaireSpieren: ['Hamstrings'],
    secundaireSpieren: ['Bilspieren', 'Rugspieren'],
  },
  {
    id: 'farmer-carry-db',
    naam: 'Farmer Carry',
    beschrijving: 'Pak een zware dumbbell in elke hand. Loop een bepaalde afstand of tijd terwijl je de dumbbells langs je lichaam houdt. Houd je schouders naar achteren en je kern strak. Traint grip, core en conditie.',
    uitleg: 'Lopen met zware dumbbells in beide handen. Grip, core en conditie.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['core', 'fullbody'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '30-40 meter of 30 sec',
    tempo: 'continu',
    tips: ['Schouders naar achteren en omlaag', 'Borst omhoog', 'Kleine, snelle stappen', 'Houd de dumbbells stil — niet slingeren'],
    fouten: ['Schouders optrekken', 'Naar één kant leunen', 'Te langzame stappen'],
    primaireSpieren: ['Onderarmen', 'Core', 'Trapezius'],
    secundaireSpieren: ['Schouders', 'Benen', 'Rugspieren'],
  },
  {
    id: 'dumbbell-complex',
    naam: 'Dumbbell Complex',
    beschrijving: 'Een serie van 5-6 oefeningen met dumbbells achter elkaar zonder neer te zetten: Romanian deadlift → power clean → front squat → overhead press → reverse lunge. Traint conditie en kracht tegelijk.',
    uitleg: 'Meerdere dumbbell oefeningen achter elkaar zonder neer te zetten. Conditie + kracht.',
    doel: ['conditie', 'kracht'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '5-6 ronden',
    tempo: 'continu',
    tips: ['Gebruik een licht gewicht — form first', 'Geen neerleggen tussen oefeningen', 'Adem bewust', 'Verhoog gewicht geleidelijk'],
    fouten: ['Te zwaar gewicht', 'Techniek laten verslechteren', 'Neerleggen tussen oefeningen'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
  {
    id: 'barbell-complex-light',
    naam: 'Barbell Complex Licht',
    beschrijving: 'Een serie met de lege stang of licht gewicht: deadlift → power clean → front squat → overhead press → back squat. Alles vloeiend in één beweging. Uitstekende conditie en techniek training.',
    uitleg: 'Lichte barbell complex. Techniek en conditie. Lege stang of weinig gewicht.',
    doel: ['conditie', 'warmup'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3',
    herhalingen: '5-6 ronden',
    tempo: 'continu',
    tips: ['Begin met lege stang', 'Elke oefening technisch correct', 'Vloeiende overgangen', 'Focus op bewegingskwaliteit'],
    fouten: ['Te zwaar gewicht', 'Overhaaste overgangen', 'Techniek verwaarlozen'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
  {
    id: 'controlled-rdl-tempo',
    naam: 'Controlled RDL Tempo',
    beschrijving: 'Romanian deadlift met een extreem gecontroleerd tempo — 5 seconden excentrisch. Doel is activatie en mobiliteit, niet belasting. Ideaal na een zware trainingsdag.',
    uitleg: 'Zeer langzame RDL (5 sec omlaag). Activatie en herstel na zware training.',
    doel: ['herstel'],
    lichaamsdelen: ['benen', 'rug'],
    niveau: 'beginner',
    equipment: ['dumbbell', 'barbell'],
    sets: '2',
    herhalingen: '8-10',
    tempo: '5-2-1',
    tips: ['Gebruik een minimaal gewicht', 'Voel elke spier activeren', 'Adem bewust', 'Herstel — geen prestatie'],
    fouten: ['Te zwaar gewicht', 'Te snel', 'Rug afronden'],
    primaireSpieren: ['Hamstrings'],
    secundaireSpieren: ['Bilspieren', 'Rugspieren'],
  },
  {
    id: 'rack-carry',
    naam: 'Rack Carry',
    beschrijving: 'Houd een dumbbell in rack positie — gebogen elleboog, dumbbell op schouderhoogte. Loop een afstand terwijl je de positie behoudt. Traint core stabiliteit, schouder en grip.',
    uitleg: 'Lopen met dumbbell in rack positie (schouder). Core en schouderstabiliteit.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['core', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '20-30 meter per kant',
    tempo: 'continu',
    tips: ['Elleboog dicht bij het lichaam', 'Dumbbell op schouderhoogte', 'Houd je romp recht — niet naar de zijkant leunen', 'Kleine stappen'],
    fouten: ['Naar de zijkant leunen', 'Elleboog weggaan van het lichaam', 'Te snel lopen'],
    primaireSpieren: ['Core', 'Schouders', 'Onderarmen'],
    secundaireSpieren: ['Trapezius', 'Benen'],
  },
  {
    id: 'activation-circuit',
    naam: 'Full Body Activatiecircuit',
    beschrijving: 'Licht circuit van 4-5 oefeningen met lichte dumbbells: lateral raise, goblet squat, dumbbell row, shoulder press, Romanian deadlift. 10 herhalingen per oefening. Als warming-up of active recovery.',
    uitleg: 'Licht dumbbell circuit als opwarming of herstel. Activeert het hele lichaam.',
    doel: ['warmup', 'herstel'],
    lichaamsdelen: ['fullbody'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '2-3',
    herhalingen: '10 per oefening',
    tempo: '2-1-2',
    tips: ['Gebruik lichte gewichten', 'Houd een rustig tempo', 'Voel elke spiergroep activeren', 'Geen rust tussen oefeningen'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Techniek negeren'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
]

// ── Hulpfuncties voor de route ─────────────────────────────────────────────

/**
 * Filtert oefeningen op krachtDoel en beschikbaar equipment.
 * Wordt gebruikt in training/today/route.ts — Optie C architectuur.
 */
export function filterStrength(
  doel: KrachtDoel,
  beschikbaarEquipment: Equipment[]
): StrengthOefening[] {
  return STRENGTH_OEFENINGEN.filter(ex =>
    ex.doel.includes(doel) &&
    ex.equipment.some(eq =>
      eq === 'both' || beschikbaarEquipment.includes(eq)
    )
  )
}

/**
 * Geeft een korte prompt-vriendelijke lijst van oefeningen terug.
 * Wordt direct in de Trainer AI prompt geplakt.
 */
export function formateerStrengthVoorPrompt(oefeningen: StrengthOefening[]): string {
  return oefeningen.map(o =>
    `- ${o.naam} (${o.niveau}, ${o.equipment.join('/')}, ${o.lichaamsdelen.join('/')}): ${o.uitleg}`
  ).join('\n')
}
