// ── CoachOS Strength Bibliotheek — Fase 1 ────────────────────────────────────
// 30 oefeningen: 10 dumbbell, 10 barbell, 10 both/warmup/herstel/conditie.
// Architectuur identiek aan bodyweight-exercises.ts:
// Coach bepaalt doel + equipment → route filtert → Trainer AI assembleert.
// Trainer AI mag GEEN nieuwe oefeningen verzinnen buiten de gefilterde lijst.

export type KrachtDoel =
  | 'kracht'
  | 'hypertrofie'
  | 'conditie'
  | 'herstel'
  | 'warmup'

export type Equipment =
  | 'dumbbell'
  | 'barbell'
  | 'both'

export type StrengthNiveau = 'beginner' | 'gemiddeld' | 'gevorderd'

export type StrengthLichaamsdeel =
  | 'benen'
  | 'billen'
  | 'rug'
  | 'borst'
  | 'schouders'
  | 'armen'
  | 'core'
  | 'fullbody'

export interface StrengthOefening {
  id: string
  naam: string
  beschrijving: string
  uitleg: string           // korte prompt-vriendelijke versie
  doel: KrachtDoel[]
  lichaamsdelen: StrengthLichaamsdeel[]
  niveau: StrengthNiveau
  equipment: Equipment[]
  sets?: string            // bijv. "3-4"
  herhalingen?: string     // bijv. "8-12"
  tempo?: string           // bijv. "3-1-1" (excentrisch-pauze-concentrisch)
  tips: string[]
  fouten: string[]
  primaireSpieren: string[]
  secundaireSpieren: string[]
}

export const STRENGTH_OEFENINGEN: StrengthOefening[] = [

  // ── DUMBBELL (10) ─────────────────────────────────────────────────────────

  {
    id: 'goblet-squat-db',
    naam: 'Goblet Squat',
    beschrijving: 'Houd een dumbbell verticaal voor je borst. Sta met voeten op schouderbreedte. Zak diep door de knieën terwijl je borst omhoog blijft. Drijf omhoog via de hielen. Uitstekende squat voor beginners door de counterbalance van de dumbbell.',
    uitleg: 'Dumbbell voor de borst houden, diep squatten. Goed voor beginners en mobiliteit.',
    doel: ['kracht', 'hypertrofie', 'warmup'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-15',
    tempo: '3-1-1',
    tips: ['Ellebogen drukken knieën naar buiten', 'Hiel blijft op de grond', 'Borst omhoog houden', 'Dumbbell close tegen je borst'],
    fouten: ['Borst naar voren vallen', 'Knieën naar binnen zakken', 'Onvoldoende diepte'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Bovenrug'],
  },
  {
    id: 'dumbbell-bench-press',
    naam: 'Dumbbell Bench Press',
    beschrijving: 'Lig op een bank met een dumbbell in elke hand ter hoogte van je borst. Duw beide dumbbells omhoog totdat je armen gestrekt zijn. Laat gecontroleerd zakken. De dumbbells geven een grotere bewegingsvrijheid dan een barbell.',
    uitleg: 'Liggend op een bank twee dumbbells omhoog drukken. Traint borstspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Schouderbladen samenknijpen op de bank', 'Ellebogen op 45 graden', 'Dumbbells boven borst — niet boven schouders', 'Voeten plat op de grond'],
    fouten: ['Ellebogen te wijd — 90 graden', 'Heupen optillen', 'Dumbbells niet laten zakken tot borstniveau'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Serratus anterior'],
  },
  {
    id: 'dumbbell-row',
    naam: 'Dumbbell Row',
    beschrijving: 'Knie en hand op een bank voor steun. Houd een dumbbell in de andere hand. Trek de dumbbell omhoog naar je heup — elleboog gaat recht omhoog langs je lichaam. Laat gecontroleerd zakken. Traint eenzijdig de rugspieren.',
    uitleg: 'Eénzijdige rugtraining — dumbbell optrekken naar de heup. Knie en hand op bank.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Elleboog recht langs het lichaam omhoog', 'Rug recht — niet roteren', 'Trek naar je heup — niet je schouder', 'Schouderblad samentrekken bovenin'],
    fouten: ['Romp roteren voor meer bereik', 'Elleboog te ver naar buiten', 'Momentum gebruiken'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Achterste schouder', 'Core'],
  },
  {
    id: 'dumbbell-curl',
    naam: 'Dumbbell Biceps Curl',
    beschrijving: 'Sta rechtop met een dumbbell in elke hand, armen langs je lichaam. Curl beide dumbbells omhoog naar je schouders terwijl je je ellebogen stil houdt. Laat gecontroleerd zakken. Draai je polsen tijdens de beweging.',
    uitleg: 'Staand twee dumbbells naar de schouders curlen. Bicepstraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10-15',
    tempo: '2-1-2',
    tips: ['Ellebogen stil aan je zij', 'Draai polsen bij het omhoog curlen', 'Volledig strekken onderaan', 'Beweeg gecontroleerd — geen schommelen'],
    fouten: ['Ellebogen naar voren bewegen', 'Romp schommelen voor momentum', 'Niet volledig strekken'],
    primaireSpieren: ['Biceps brachii'],
    secundaireSpieren: ['Brachialis', 'Onderarmen'],
  },
  {
    id: 'dumbbell-lunge',
    naam: 'Dumbbell Lunge',
    beschrijving: 'Houd een dumbbell in elke hand langs je lichaam. Stap naar voren in een lunge. Laat je achterste knie zakken naar de grond. Drijf omhoog via je voorste been. Stap terug of ga door naar de volgende stap.',
    uitleg: 'Lunge met dumbbells in de handen. Traint benen en bilspieren eenzijdig.',
    doel: ['kracht', 'hypertrofie', 'conditie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10 per been',
    tempo: '2-1-1',
    tips: ['Romp rechtop houden', 'Voorste knie boven de enkel', 'Stap breed genoeg', 'Bilspieren aanspannen bij het omhoog komen'],
    fouten: ['Romp naar voren leunen', 'Voorste knie over de teen', 'Te kleine stap'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
  },
  {
    id: 'dumbbell-shoulder-press',
    naam: 'Dumbbell Shoulder Press',
    beschrijving: 'Zit of sta met een dumbbell in elke hand ter hoogte van je schouders. Duw beide dumbbells recht omhoog totdat je armen gestrekt zijn. Laat gecontroleerd zakken. Traint de schouders.',
    uitleg: 'Dumbbells vanaf schouderhoogte omhoog drukken. Schoudertraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['schouders'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Core actief houden — niet hol trekken', 'Druk recht omhoog — niet naar voren', 'Ellebogen naar voren — niet naar de zijkant', 'Volledig strekken bovenin'],
    fouten: ['Rug hol trekken', 'Dumbbells naar voren drukken', 'Onvoldoende strekken'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Trapezius', 'Core'],
  },
  {
    id: 'romanian-deadlift-db',
    naam: 'Romanian Deadlift Dumbbell',
    beschrijving: 'Houd een dumbbell in elke hand voor je dijen. Buig naar voren vanuit je heupen terwijl je rug recht blijft. Laat de dumbbells langs je benen zakken. Kom omhoog via je bilspieren. Voel de stretch in je hamstrings.',
    uitleg: 'Dumbbell RDL — buigen vanuit de heupen met rechte rug. Hamstrings en bilspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Buig vanuit de heupen — niet de rug', 'Rug recht houden — lichte natuurlijke curve', 'Dumbbells dicht langs de benen', 'Bilspieren aanspannen bij het omhoog komen'],
    fouten: ['Rug afronden', 'Knieën te veel buigen — dit is geen squat', 'Dumbbells te ver van het lichaam'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core'],
  },
  {
    id: 'dumbbell-incline-press',
    naam: 'Incline Dumbbell Press',
    beschrijving: 'Lig op een schuine bank (30-45 graden). Houd een dumbbell in elke hand ter hoogte van je borst. Duw omhoog. Traint de bovenkant van de borstspieren meer dan een vlakke bank.',
    uitleg: 'Dumbbell press op een schuine bank. Bovenkant borst en schouders.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Bank niet te steil — 30-45 graden is optimaal', 'Schouderbladen samenknijpen', 'Ellebogen op 45-60 graden', 'Dumbbells boven het bovenste deel van de borst'],
    fouten: ['Bank te steil — wordt een schouderpress', 'Ellebogen te wijd', 'Heupen optillen'],
    primaireSpieren: ['Bovenkant borstspieren', 'Schouders'],
    secundaireSpieren: ['Triceps', 'Serratus anterior'],
  },
  {
    id: 'lateral-raise-db',
    naam: 'Lateral Raise',
    beschrijving: 'Sta rechtop met een dumbbell in elke hand langs je lichaam. Hef beide armen tegelijk zijwaarts op tot schouderhoogte. Laat gecontroleerd zakken. Traint de zijkant van de schouders.',
    uitleg: 'Dumbbells zijwaarts opheffen tot schouderhoogte. Zijkant schouder.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['schouders'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '2-1-2',
    tips: ['Kleine pinky iets omhoog — als water uitschenken', 'Licht gebogen elleboog', 'Niet hoger dan schouderhoogte', 'Beweeg langzaam omlaag'],
    fouten: ['Momentum gebruiken — schommelen', 'Te zwaar gewicht', 'Armen te hoog heffen', 'Schouders optrekken'],
    primaireSpieren: ['Zijkant schouder', 'Mediale deltoid'],
    secundaireSpieren: ['Trapezius', 'Supraspinatus'],
  },
  {
    id: 'triceps-extension-db',
    naam: 'Dumbbell Triceps Extension',
    beschrijving: 'Zit of sta met één of twee dumbbells boven je hoofd. Laat de dumbbell(s) zakken achter je hoofd door je ellebogen te buigen. Strek omhoog. Traint de triceps.',
    uitleg: 'Dumbbell boven het hoofd zakken achter de nek. Tricepstraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '12-15',
    tempo: '2-1-2',
    tips: ['Ellebogen dicht bij het hoofd houden', 'Bovenarmem stil — alleen onderarmen bewegen', 'Volledig strekken bovenin', 'Gebruik beide handen bij één zware dumbbell'],
    fouten: ['Ellebogen naar buiten bewegen', 'Bovenarmem meebewegen', 'Te zwaar gewicht'],
    primaireSpieren: ['Triceps brachii'],
    secundaireSpieren: ['Schouders'],
  },

  // ── BARBELL (10) ──────────────────────────────────────────────────────────

  {
    id: 'barbell-back-squat',
    naam: 'Back Squat',
    beschrijving: 'Barbell op de bovenrug. Voeten op schouderbreedte. Zak diep door de knieën terwijl je borst omhoog blijft en je rug recht. Drijf omhoog via de hielen. De koning van de krachtoefeningen voor de benen.',
    uitleg: 'Barbell op de rug, diep squatten. Meest effectieve beentraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '5-8',
    tempo: '3-1-1',
    tips: ['Barbell op de trapezius — niet op de nek', 'Borst omhoog, rug recht', 'Knieën volgen de richting van de tenen', 'Drijf via de hielen omhoog'],
    fouten: ['Borst naar voren vallen in de bodem', 'Knieën naar binnen zakken', 'Hielen optillen', 'Barbell te hoog op de nek'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Bovenrug'],
  },
  {
    id: 'barbell-deadlift',
    naam: 'Deadlift',
    beschrijving: 'Barbell op de grond voor je voeten. Handen op schouderbreedte op de stang. Rug recht, bilspieren aanspannen, trek de stang omhoog langs je benen door te strekken vanuit heupen en knieën tegelijk. Zet neer via dezelfde weg.',
    uitleg: 'Barbell van de grond optillen. Traint de volledige achterkant van het lichaam.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '3-6',
    tempo: '2-1-1',
    tips: ['Stang dicht langs de benen — schraapt bijna', 'Rug recht gedurende de hele beweging', 'Trek de spanning op voor je trekt', 'Bilspieren aanspannen bovenin'],
    fouten: ['Rug afronden', 'Stang te ver van het lichaam', 'Knieën eerst strekken voor de heupen'],
    primaireSpieren: ['Hamstrings', 'Bilspieren', 'Rugspieren'],
    secundaireSpieren: ['Quadriceps', 'Core', 'Trapezius'],
  },
  {
    id: 'barbell-bench-press',
    naam: 'Bench Press',
    beschrijving: 'Lig op een vlakke bank. Barbell iets breder dan schouderbreedte. Laat de stang zakken naar je borst — raak licht aan. Duw explosief omhoog. Voeten plat op de grond, schouderbladen samengeknepen.',
    uitleg: 'Barbell op een bank drukken. Klassieke borsttraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '5-10',
    tempo: '3-1-1',
    tips: ['Schouderbladen samenknijpen en in de bank drukken', 'Ellebogen op 45-75 graden', 'Stang raakt de borst — niet stuitert', 'Voeten plat op de grond'],
    fouten: ['Ellebogen te wijd — 90 graden', 'Heupen optillen van de bank', 'Stangen laten stuiteren op de borst', 'Polsen buigen'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Serratus anterior'],
  },
  {
    id: 'barbell-overhead-press',
    naam: 'Overhead Press',
    beschrijving: 'Sta rechtop met barbell op de voorkant van de schouders. Duw de stang recht omhoog. Beweeg je gezicht licht naar achteren bij het passeren van de stang. Strek volledig boven. Laat langzaam zakken.',
    uitleg: 'Barbell van de schouders recht omhoog drukken. Schouder- en tricepstraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['schouders', 'armen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-5',
    herhalingen: '5-8',
    tempo: '2-1-2',
    tips: ['Core strak — niet hol trekken', 'Beweeg gezicht naar achteren als stang passeert', 'Druk recht omhoog — niet naar voren', 'Bilspieren en core aanspannen voor stabiliteit'],
    fouten: ['Rug hol trekken', 'Stang naar voren drukken', 'Knieën buigen voor momentum'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Trapezius', 'Core', 'Bovenrug'],
  },
  {
    id: 'barbell-row',
    naam: 'Barbell Row',
    beschrijving: 'Leun voorover met rechte rug — romp bijna parallel aan de grond. Houd de barbell met overhand greep. Trek de stang naar je onderbuik. Laat gecontroleerd zakken. Traint de dikke rugspieren.',
    uitleg: 'Voorovergebogen barbell optrekken naar de buik. Rugtraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4',
    herhalingen: '6-10',
    tempo: '2-1-2',
    tips: ['Rug recht — lichte natuurlijke curve', 'Trek naar de onderbuik — niet de borst', 'Ellebogen dicht langs het lichaam', 'Schouderbladen samentrekken bovenin'],
    fouten: ['Rug afronden', 'Romp omhoog bewegen voor meer bereik', 'Trek naar de borst in plaats van de buik'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids', 'Trapezius'],
    secundaireSpieren: ['Biceps', 'Achterste schouder', 'Core'],
  },
  {
    id: 'romanian-deadlift-bb',
    naam: 'Romanian Deadlift Barbell',
    beschrijving: 'Houd de barbell met overhand greep voor je dijen. Buig naar voren vanuit de heupen — rug recht. Laat de stang langs je benen zakken. Voel de stretch in de hamstrings. Kom omhoog via de bilspieren.',
    uitleg: 'Barbell RDL — hinge beweging voor hamstrings en bilspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Stang dicht langs de benen', 'Rug recht — geen afronden', 'Knieën licht gebogen maar stabiel', 'Stop als de rug wil afronden'],
    fouten: ['Rug afronden onderaan', 'Knieën te veel buigen — geen squat', 'Stang te ver van het lichaam'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Rugspieren', 'Core', 'Kuiten'],
  },
  {
    id: 'barbell-hip-thrust',
    naam: 'Barbell Hip Thrust',
    beschrijving: 'Leun met schouders op een bank. Barbell op je heupen — gebruik een mat of pad. Voeten op de grond. Duw heupen omhoog terwijl je bilspieren maximaal aanspant. Houd 1-2 seconden vast. Laat zakken.',
    uitleg: 'Barbell op de heupen. Heupen omhoog duwen. Beste bilspier oefening.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-15',
    tempo: '2-2-1',
    tips: ['Kin naar borst — hoofd niet achterover', 'Bilspieren maximaal aanspannen bovenin', 'Voeten plat en heupbreedte', 'Gebruik altijd een pad op de heupen'],
    fouten: ['Hoofd achterover hangen', 'Rug hol trekken bovenin', 'Knieën naar binnen zakken'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Quadriceps'],
  },
  {
    id: 'front-squat',
    naam: 'Front Squat',
    beschrijving: 'Barbell op de voorkant van de schouders — armen gekruist of clean grip. Ellebogen hoog. Zak diep door de knieën. Meer nadruk op quadriceps dan back squat. Vereist goede mobiliteit.',
    uitleg: 'Barbell aan de voorkant op de schouders. Quad-gerichte squat.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4',
    herhalingen: '5-8',
    tempo: '3-1-1',
    tips: ['Ellebogen zo hoog mogelijk', 'Borst omhoog — niet laten zakken', 'Knieën ver naar voren — over de teen', 'Goede enkelmobiliteit vereist'],
    fouten: ['Ellebogen zakken — stang rolt eraf', 'Borst naar voren vallen', 'Onvoldoende enkelmobiliteit'],
    primaireSpieren: ['Quadriceps'],
    secundaireSpieren: ['Bilspieren', 'Core', 'Bovenrug'],
  },
  {
    id: 'pendlay-row',
    naam: 'Pendlay Row',
    beschrijving: 'Barbell op de grond. Sta met voeten op heupbreedte. Rug parallel aan de grond. Trek de stang explosief naar je borst. Laat terug op de grond zakken. Elke herhaling start vanuit stilstand.',
    uitleg: 'Explosive barbell row vanuit de grond. Krachtige rugtraining.',
    doel: ['kracht'],
    lichaamsdelen: ['rug'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '5-6',
    tempo: '1-1-2',
    tips: ['Rug parallel aan de grond', 'Explosief omhoog trekken', 'Stang terug op de grond laten zakken', 'Trek naar de borst — niet de buik'],
    fouten: ['Romp omhoog bewegen', 'Niet terug op de grond zetten', 'Rug niet parallel'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids', 'Trapezius'],
    secundaireSpieren: ['Biceps', 'Core', 'Achterste schouder'],
  },
  {
    id: 'barbell-good-morning',
    naam: 'Good Morning Barbell',
    beschrijving: 'Barbell op de bovenrug zoals bij een squat. Buig naar voren vanuit de heupen terwijl je rug recht blijft. Ga totdat je romp bijna parallel is aan de grond. Kom omhoog via de bilspieren en hamstrings.',
    uitleg: 'Barbell op de rug, voorover buigen vanuit heupen. Hamstrings en rugspieren.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Rug recht gedurende de hele beweging', 'Buig vanuit de heupen — niet de rug', 'Knieën licht gebogen', 'Begin licht — goed voor mobiliteit'],
    fouten: ['Rug afronden', 'Te snel bewegen', 'Te zwaar beginnen'],
    primaireSpieren: ['Hamstrings', 'Rugspieren'],
    secundaireSpieren: ['Bilspieren', 'Core'],
  },

  // ── BOTH / WARMUP / HERSTEL / CONDITIE (10) ───────────────────────────────

  {
    id: 'empty-bar-squat',
    naam: 'Lege Stang Squat',
    beschrijving: 'Squat met alleen de lege barbell als opwarmoefening. Focus op techniek, mobiliteit en bewegingspatroon. Perfecte warming-up voor zware squat sessies.',
    uitleg: 'Squat met lege stang. Techniek oefenen en opwarmen voor de sessie.',
    doel: ['warmup'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['barbell'],
    sets: '2-3',
    herhalingen: '10-15',
    tempo: '3-1-1',
    tips: ['Focus op techniek — niet op gewicht', 'Voel elke fase van de squat', 'Houd een langzaam tempo', 'Gebruik dit om mobiliteit te checken'],
    fouten: ['Te snel bewegen', 'Techniek negeren', 'Direct naar zwaar gewicht'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core'],
  },
  {
    id: 'goblet-squat-tempo',
    naam: 'Goblet Squat Tempo',
    beschrijving: 'Goblet squat met een langzaam gecontroleerd tempo — 5 seconden omlaag, 2 seconden vasthouden in de bodem, 1 seconde omhoog. Traint mobiliteit en lichaamsbewustzijn.',
    uitleg: 'Langzame goblet squat voor mobiliteit en techniekwerk. 5-2-1 tempo.',
    doel: ['warmup', 'herstel'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '6-8',
    tempo: '5-2-1',
    tips: ['Neem de volle 5 seconden omlaag', 'Voel de stretch in de bodem', 'Gebruik een licht gewicht', 'Focus op positie en balans'],
    fouten: ['Te snel bewegen', 'Te zwaar gewicht', 'Borst naar voren vallen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Enkels'],
  },
  {
    id: 'hinge-drill',
    naam: 'Hinge Drill',
    beschrijving: 'Sta met de rug langs een muur. Strek een barbell of stok achter je rug — contact op hoofd, bovenrug en billen. Oefen de hinge beweging door je heupen naar achteren te duwen terwijl je drie contactpunten behoudt.',
    uitleg: 'Stok of lege stang achter de rug. Oefent de hinge beweging voor deadlifts.',
    doel: ['warmup'],
    lichaamsdelen: ['rug', 'benen'],
    niveau: 'beginner',
    equipment: ['barbell', 'both'],
    sets: '3',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Drie contactpunten: hoofd, bovenrug, billen', 'Duw heupen naar achteren — niet naar beneden', 'Rug recht houden', 'Gebruik dit dagelijks als mobiliteitsroutine'],
    fouten: ['Contactpunten verliezen', 'Knieën te veel buigen', 'Rug afronden'],
    primaireSpieren: ['Hamstrings', 'Rugspieren'],
    secundaireSpieren: ['Bilspieren', 'Core'],
  },
  {
    id: 'light-rdl-mobility',
    naam: 'Lichte RDL Mobiliteit',
    beschrijving: 'Romanian deadlift met een zeer licht gewicht — focus volledig op mobiliteit en het voelen van de hamstrings. Ideaal als herstel of mobiliteitswerk op lichte dagen.',
    uitleg: 'Zeer lichte RDL als mobiliteits- en herstelloefening. Voelen niet laden.',
    doel: ['herstel', 'warmup'],
    lichaamsdelen: ['benen', 'rug'],
    niveau: 'beginner',
    equipment: ['dumbbell', 'barbell'],
    sets: '2-3',
    herhalingen: '12-15',
    tempo: '4-2-1',
    tips: ['Gebruik een heel licht gewicht', 'Focus op het voelen van de hamstrings', 'Langzaam en gecontroleerd', 'Ideaal voor hersteldag'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Rug afronden'],
    primaireSpieren: ['Hamstrings'],
    secundaireSpieren: ['Bilspieren', 'Rugspieren'],
  },
  {
    id: 'farmer-carry-db',
    naam: 'Farmer Carry',
    beschrijving: 'Pak een zware dumbbell in elke hand. Loop een bepaalde afstand of tijd terwijl je de dumbbells langs je lichaam houdt. Houd je schouders naar achteren en je kern strak. Traint grip, core en conditie.',
    uitleg: 'Lopen met zware dumbbells in beide handen. Grip, core en conditie.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['core', 'fullbody'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '30-40 meter of 30 sec',
    tempo: 'continu',
    tips: ['Schouders naar achteren en omlaag', 'Borst omhoog', 'Kleine, snelle stappen', 'Houd de dumbbells stil — niet slingeren'],
    fouten: ['Schouders optrekken', 'Naar één kant leunen', 'Te langzame stappen'],
    primaireSpieren: ['Onderarmen', 'Core', 'Trapezius'],
    secundaireSpieren: ['Schouders', 'Benen', 'Rugspieren'],
  },
  {
    id: 'dumbbell-complex',
    naam: 'Dumbbell Complex',
    beschrijving: 'Een serie van 5-6 oefeningen met dumbbells achter elkaar zonder neer te zetten: Romanian deadlift → power clean → front squat → overhead press → reverse lunge. Traint conditie en kracht tegelijk.',
    uitleg: 'Meerdere dumbbell oefeningen achter elkaar zonder neer te zetten. Conditie + kracht.',
    doel: ['conditie', 'kracht'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '5-6 ronden',
    tempo: 'continu',
    tips: ['Gebruik een licht gewicht — form first', 'Geen neerleggen tussen oefeningen', 'Adem bewust', 'Verhoog gewicht geleidelijk'],
    fouten: ['Te zwaar gewicht', 'Techniek laten verslechteren', 'Neerleggen tussen oefeningen'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
  {
    id: 'barbell-complex-light',
    naam: 'Barbell Complex Licht',
    beschrijving: 'Een serie met de lege stang of licht gewicht: deadlift → power clean → front squat → overhead press → back squat. Alles vloeiend in één beweging. Uitstekende conditie en techniek training.',
    uitleg: 'Lichte barbell complex. Techniek en conditie. Lege stang of weinig gewicht.',
    doel: ['conditie', 'warmup'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3',
    herhalingen: '5-6 ronden',
    tempo: 'continu',
    tips: ['Begin met lege stang', 'Elke oefening technisch correct', 'Vloeiende overgangen', 'Focus op bewegingskwaliteit'],
    fouten: ['Te zwaar gewicht', 'Overhaaste overgangen', 'Techniek verwaarlozen'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
  {
    id: 'controlled-rdl-tempo',
    naam: 'Controlled RDL Tempo',
    beschrijving: 'Romanian deadlift met een extreem gecontroleerd tempo — 5 seconden excentrisch. Doel is activatie en mobiliteit, niet belasting. Ideaal na een zware trainingsdag.',
    uitleg: 'Zeer langzame RDL (5 sec omlaag). Activatie en herstel na zware training.',
    doel: ['herstel'],
    lichaamsdelen: ['benen', 'rug'],
    niveau: 'beginner',
    equipment: ['dumbbell', 'barbell'],
    sets: '2',
    herhalingen: '8-10',
    tempo: '5-2-1',
    tips: ['Gebruik een minimaal gewicht', 'Voel elke spier activeren', 'Adem bewust', 'Herstel — geen prestatie'],
    fouten: ['Te zwaar gewicht', 'Te snel', 'Rug afronden'],
    primaireSpieren: ['Hamstrings'],
    secundaireSpieren: ['Bilspieren', 'Rugspieren'],
  },
  {
    id: 'rack-carry',
    naam: 'Rack Carry',
    beschrijving: 'Houd een dumbbell in rack positie — gebogen elleboog, dumbbell op schouderhoogte. Loop een afstand terwijl je de positie behoudt. Traint core stabiliteit, schouder en grip.',
    uitleg: 'Lopen met dumbbell in rack positie (schouder). Core en schouderstabiliteit.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['core', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '20-30 meter per kant',
    tempo: 'continu',
    tips: ['Elleboog dicht bij het lichaam', 'Dumbbell op schouderhoogte', 'Houd je romp recht — niet naar de zijkant leunen', 'Kleine stappen'],
    fouten: ['Naar de zijkant leunen', 'Elleboog weggaan van het lichaam', 'Te snel lopen'],
    primaireSpieren: ['Core', 'Schouders', 'Onderarmen'],
    secundaireSpieren: ['Trapezius', 'Benen'],
  },
  {
    id: 'activation-circuit',
    naam: 'Full Body Activatiecircuit',
    beschrijving: 'Licht circuit van 4-5 oefeningen met lichte dumbbells: lateral raise, goblet squat, dumbbell row, shoulder press, Romanian deadlift. 10 herhalingen per oefening. Als warming-up of active recovery.',
    uitleg: 'Licht dumbbell circuit als opwarming of herstel. Activeert het hele lichaam.',
    doel: ['warmup', 'herstel'],
    lichaamsdelen: ['fullbody'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '2-3',
    herhalingen: '10 per oefening',
    tempo: '2-1-2',
    tips: ['Gebruik lichte gewichten', 'Houd een rustig tempo', 'Voel elke spiergroep activeren', 'Geen rust tussen oefeningen'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Techniek negeren'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
]

// ── Hulpfuncties voor de route ─────────────────────────────────────────────

/**
 * Filtert oefeningen op krachtDoel en beschikbaar equipment.
 * Wordt gebruikt in training/today/route.ts — Optie C architectuur.
 */
export function filterStrength(
  doel: KrachtDoel,
  beschikbaarEquipment: Equipment[]
): StrengthOefening[] {
  return STRENGTH_OEFENINGEN.filter(ex =>
    ex.doel.includes(doel) &&
    ex.equipment.some(eq =>
      eq === 'both' || beschikbaarEquipment.includes(eq)
    )
  )
}

/**
 * Geeft een korte prompt-vriendelijke lijst van oefeningen terug.
 * Wordt direct in de Trainer AI prompt geplakt.
 */
export function formateerStrengthVoorPrompt(oefeningen: StrengthOefening[]): string {
  return oefeningen.map(o =>
    `- ${o.naam} (${o.niveau}, ${o.equipment.join('/')}, ${o.lichaamsdelen.join('/')}): ${o.uitleg}`
  ).join('\n')
}

// ── FASE 2 — Extra oefeningen (richting 60-70 totaal) ─────────────────────

const fase2StrengthOefeningen: StrengthOefening[] = [

  // ── DUMBBELL UITBREIDING ──────────────────────────────────────────────────

  {
    id: 'dumbbell-sumo-deadlift',
    naam: 'Dumbbell Sumo Deadlift',
    beschrijving: 'Sta met voeten wijd en tenen naar buiten. Houd een dumbbell met beide handen tussen je benen. Zak omlaag met rechte rug. Trek omhoog via je bilspieren en benen. Combineert sumo stance met deadlift beweging.',
    uitleg: 'Brede stance deadlift met één dumbbell. Bilspieren en binnenkant dij.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Knieën volgen de richting van de tenen', 'Rug recht houden', 'Bilspieren aanspannen bovenin', 'Dumbbell dicht bij het lichaam'],
    fouten: ['Rug afronden', 'Knieën naar binnen zakken', 'Dumbbell te ver naar voren'],
    primaireSpieren: ['Bilspieren', 'Binnenkant dij', 'Hamstrings'],
    secundaireSpieren: ['Quadriceps', 'Core'],
  },
  {
    id: 'single-arm-db-press',
    naam: 'Single Arm Dumbbell Press',
    beschrijving: 'Lig op een bank met één dumbbell. Druk de dumbbell omhoog met één arm. De andere arm ligt langs je lichaam of op je buik. Traint eenzijdig en vraagt meer core stabiliteit.',
    uitleg: 'Eénarmige dumbbell press. Meer core activatie dan beide armen tegelijk.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'schouders', 'core'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12 per arm',
    tempo: '3-1-1',
    tips: ['Houd je heupen level — niet roteren', 'Core actief aanspannen', 'Schouderblad in de bank drukken', 'Andere hand op buik voor bewustzijn'],
    fouten: ['Heupen roteren voor meer bereik', 'Core laten zakken', 'Schouder optrekken'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders', 'Core', 'Obliques'],
  },
  {
    id: 'dumbbell-pullover',
    naam: 'Dumbbell Pullover',
    beschrijving: 'Lig dwars op een bank met je bovenrug. Houd een dumbbell met beide handen boven je borst. Laat de dumbbell zakken achter je hoofd in een boog. Trek terug. Traint de lat en borst.',
    uitleg: 'Dumbbell in boog achter het hoofd laten zakken. Lat en borst.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['rug', 'borst'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '12-15',
    tempo: '3-1-2',
    tips: ['Ellebogen licht gebogen — niet volledig strekken', 'Laat de dumbbell echt zakken achter het hoofd', 'Voel de stretch in de lat', 'Beweging vanuit de schouder — niet de elleboog'],
    fouten: ['Ellebogen te veel buigen', 'Niet ver genoeg laten zakken', 'Te zwaar gewicht'],
    primaireSpieren: ['Latissimus dorsi', 'Borstspieren'],
    secundaireSpieren: ['Triceps', 'Schouders', 'Core'],
  },
  {
    id: 'hammer-curl',
    naam: 'Hammer Curl',
    beschrijving: 'Houd dumbbells met neutrale grip — duimen omhoog. Curl omhoog zonder de pols te draaien. Traint de brachialis en onderarm naast de biceps.',
    uitleg: 'Curl met neutrale grip (duimen omhoog). Brachialis en onderarm.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '12-15',
    tempo: '2-1-2',
    tips: ['Duimen omhoog gedurende de hele beweging', 'Ellebogen stil aan de zij', 'Volledig strekken onderaan', 'Alternerende of gelijktijdige uitvoering'],
    fouten: ['Pols draaien bij het omhoog gaan', 'Ellebogen naar voren bewegen', 'Schommelen'],
    primaireSpieren: ['Brachialis', 'Biceps brachii'],
    secundaireSpieren: ['Brachioradialis', 'Onderarmen'],
  },
  {
    id: 'db-skull-crusher',
    naam: 'Dumbbell Skull Crusher',
    beschrijving: 'Lig op een bank. Houd dumbbells recht boven je borst. Laat ze zakken naar je slapen door alleen je ellebogen te buigen. Strek omhoog. Traint intensief de triceps.',
    uitleg: 'Dumbbell zakken naar de slapen liggend. Triceps isolatieoefening.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['armen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Bovenarmem stil houden', 'Laat dumbbells naast de slapen zakken — niet erop', 'Volledig strekken bovenin', 'Gebruik lichte dumbbells — intensieve oefening'],
    fouten: ['Bovenarmem meebewegen', 'Te zwaar gewicht', 'Ellebogen naar buiten bewegen'],
    primaireSpieren: ['Triceps brachii'],
    secundaireSpieren: ['Schouders'],
  },
  {
    id: 'db-chest-fly',
    naam: 'Dumbbell Chest Fly',
    beschrijving: 'Lig op een bank met dumbbells boven je borst, licht gebogen ellebogen. Open je armen wijd in een boog totdat je een stretch voelt in de borst. Sluit terug in een knuffelboog. Isoleert de borstspieren.',
    uitleg: 'Dumbbells in een boog openen en sluiten. Borst isolatieoefening.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['borst'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '3-1-2',
    tips: ['Licht gebogen ellebogen gedurende de hele beweging', 'Voel de stretch in de borst onderaan', 'Beweeg in een boog — niet recht naar buiten', 'Gebruik lichte gewichten'],
    fouten: ['Ellebogen te veel buigen — wordt een press', 'Te zwaar gewicht', 'Armen recht naar buiten in plaats van boog'],
    primaireSpieren: ['Borstspieren'],
    secundaireSpieren: ['Schouders', 'Biceps'],
  },
  {
    id: 'db-reverse-fly',
    naam: 'Dumbbell Reverse Fly',
    beschrijving: 'Leun voorover met rechte rug. Houd dumbbells naar beneden hangend. Hef beide armen zijwaarts omhoog met licht gebogen ellebogen. Traint de achterste schouder en bovenrug.',
    uitleg: 'Voorovergebogen dumbbells zijwaarts opheffen. Achterste schouder en bovenrug.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['schouders', 'rug'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '2-1-2',
    tips: ['Licht gebogen ellebogen', 'Beweeg tot schouderhoogte', 'Knijp schouderbladen samen bovenin', 'Gebruik lichte gewichten'],
    fouten: ['Te zwaar gewicht — gaat dan fout', 'Romp omhoog bewegen voor meer bereik', 'Ellebogen te veel buigen'],
    primaireSpieren: ['Achterste schouder', 'Rhomboids'],
    secundaireSpieren: ['Trapezius', 'Rotatorenmanchet'],
  },
  {
    id: 'db-split-squat',
    naam: 'Dumbbell Split Squat',
    beschrijving: 'Houd een dumbbell in elke hand. Sta in een gesplitste positie. Zak recht omlaag en omhoog. Zwaardere versie van de bodyweight split squat.',
    uitleg: 'Split squat met dumbbells. Eenzijdige beentraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10 per been',
    tempo: '3-1-1',
    tips: ['Houd romp rechtop', 'Voorste knie boven de enkel', 'Bilspieren aanspannen bij omhoog komen', 'Stap breed genoeg'],
    fouten: ['Romp naar voren leunen', 'Voorste knie over de teen', 'Te kleine stap'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
  },
  {
    id: 'db-step-up',
    naam: 'Dumbbell Step-Up',
    beschrijving: 'Houd een dumbbell in elke hand. Stap met één voet op een bank. Duw jezelf omhoog. Extra weerstand ten opzichte van bodyweight step-up.',
    uitleg: 'Step-up met dumbbells voor extra weerstand. Benen en bilspieren.',
    doel: ['kracht', 'hypertrofie', 'conditie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10 per been',
    tempo: '2-1-2',
    tips: ['Duw via het voorste been — niet afzetten', 'Romp rechtop houden', 'Stap volledig op de bank', 'Gecontroleerd terug stappen'],
    fouten: ['Afzetten met het achterste been', 'Romp naar voren', 'Knie naar binnen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
  },
  {
    id: 'db-calf-raise',
    naam: 'Dumbbell Kuitverheffen',
    beschrijving: 'Houd een dumbbell in elke hand. Kom op de ballen van je voeten omhoog. Voor extra uitdaging stap je op een traprand zodat je hielen ook naar beneden kunnen gaan.',
    uitleg: 'Kuitverheffen met dumbbells voor extra weerstand.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '4',
    herhalingen: '15-20',
    tempo: '2-2-1',
    tips: ['Ga zo hoog mogelijk op de ballen', 'Houd 2 seconden vast bovenin', 'Laat langzaam zakken', 'Voor meer bereik staan op een verhoging'],
    fouten: ['Te snel bewegen', 'Niet hoog genoeg', 'Gewicht ongelijk verdelen'],
    primaireSpieren: ['Gastrocnemius', 'Soleus'],
    secundaireSpieren: ['Achillespees', 'Enkels'],
  },

  // ── BARBELL UITBREIDING ───────────────────────────────────────────────────

  {
    id: 'barbell-lunge',
    naam: 'Barbell Lunge',
    beschrijving: 'Barbell op de bovenrug. Stap naar voren in een lunge. Laat je achterste knie zakken naar de grond. Drijf omhoog. Zwaardere variant van de bodyweight lunge.',
    uitleg: 'Lunge met barbell op de rug. Zwaardere beentraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '8-10 per been',
    tempo: '2-1-1',
    tips: ['Romp rechtop — niet naar voren leunen', 'Voorste knie boven de enkel', 'Barbell stabiel houden', 'Bilspieren aanspannen bij omhoog'],
    fouten: ['Romp naar voren leunen', 'Barbell heen en weer bewegen', 'Knie naar binnen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
  },
  {
    id: 'barbell-sumo-deadlift',
    naam: 'Sumo Deadlift',
    beschrijving: 'Barbell op de grond. Brede stance met tenen naar buiten. Handen binnen de knieën op de stang. Trek omhoog via bilspieren en benen. Minder rugbelasting dan conventional deadlift.',
    uitleg: 'Deadlift met brede stance. Minder rugbelasting, meer bilspieren.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '4-6',
    tempo: '2-1-1',
    tips: ['Knieën volgen de richting van de tenen', 'Trek de vloer uit elkaar met je voeten', 'Borst omhoog', 'Heupen en schouders stijgen gelijktijdig'],
    fouten: ['Knieën naar binnen bij het optrekken', 'Rug afronden', 'Heupen te laag starten'],
    primaireSpieren: ['Bilspieren', 'Hamstrings', 'Binnenkant dij'],
    secundaireSpieren: ['Quadriceps', 'Rugspieren', 'Core'],
  },
  {
    id: 'barbell-curl',
    naam: 'Barbell Biceps Curl',
    beschrijving: 'Houd een barbell met underhand greep op schouderbreedte. Curl de stang omhoog naar je schouders terwijl je ellebogen stil blijven. Laat langzaam zakken.',
    uitleg: 'Biceps curl met barbell. Meer gewicht mogelijk dan dumbbell curl.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Ellebogen stil aan de zij', 'Volledig strekken onderaan', 'Geen schommelen', 'Gebruik een EZ-bar voor minder polsbelasting'],
    fouten: ['Ellebogen naar voren', 'Romp schommelen', 'Niet volledig strekken'],
    primaireSpieren: ['Biceps brachii'],
    secundaireSpieren: ['Brachialis', 'Onderarmen'],
  },
  {
    id: 'barbell-close-grip-press',
    naam: 'Close Grip Bench Press',
    beschrijving: 'Bench press met smalle greep — handen op schouderbreedte. Meer nadruk op triceps dan borstspieren. Ellebogen gaan recht naar achteren.',
    uitleg: 'Smal gegrepen bench press. Traint primair de triceps.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['armen', 'borst'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '8-12',
    tempo: '3-1-1',
    tips: ['Ellebogen gaan recht naar achteren — niet naar buiten', 'Handen op schouderbreedte — niet smal', 'Schouderbladen in de bank', 'Volledig strekken bovenin'],
    fouten: ['Handen te smal', 'Ellebogen naar buiten', 'Polsen buigen'],
    primaireSpieren: ['Triceps brachii', 'Borstspieren'],
    secundaireSpieren: ['Schouders'],
  },
  {
    id: 'power-clean',
    naam: 'Power Clean',
    beschrijving: 'Explosieve beweging waarbij de barbell van de grond naar de schouders wordt getrokken. Vereist techniek. Traint de volledige posterior chain en explosiviteit.',
    uitleg: 'Explosief barbell van grond naar schouders. Kracht en snelheid.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '3-5',
    tempo: 'explosief',
    tips: ['Leer eerst de techniek met lege stang', 'Gebruik je heupen voor het explosieve gedeelte', 'Ellebogen snel naar voren in de catch', 'Kwaliteit boven gewicht'],
    fouten: ['Te zwaar gewicht voor het niveau', 'Armen te vroeg buigen', 'Geen hip drive'],
    primaireSpieren: ['Volledig lichaam', 'Bilspieren', 'Trapezius'],
    secundaireSpieren: ['Quadriceps', 'Hamstrings', 'Schouders'],
  },
  {
    id: 'barbell-upright-row',
    naam: 'Barbell Upright Row',
    beschrijving: 'Houd een barbell voor je met overhand greep, handen smal. Trek de stang omhoog langs je lichaam tot kin hoogte — ellebogen gaan hoger dan de stang. Traint schouders en trapezius.',
    uitleg: 'Barbell omhoog trekken langs het lichaam. Schouders en trapezius.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['schouders'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Ellebogen hoger dan de pols', 'Stang dicht langs het lichaam', 'Stop bij kin hoogte', 'Gebruik geen te smal of breed handgreep'],
    fouten: ['Stang te ver van het lichaam', 'Te smal handgreep — schouderprobleem', 'Momentum gebruiken'],
    primaireSpieren: ['Zijkant schouder', 'Trapezius'],
    secundaireSpieren: ['Biceps', 'Voorste schouder'],
  },
  {
    id: 'barbell-shrug',
    naam: 'Barbell Shrug',
    beschrijving: 'Houd een zware barbell voor je. Haal je schouders op — zo hoog mogelijk. Houd 1-2 seconden vast. Laat zakken. Traint de trapezius.',
    uitleg: 'Schouders ophalen met zware barbell. Trapezius training.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['schouders'],
    niveau: 'beginner',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '1-2-1',
    tips: ['Haal je schouders recht omhoog — niet ronddraaien', 'Houd 2 seconden vast bovenin', 'Gebruik een stevige grip of straps', 'Houd je armen recht'],
    fouten: ['Schouders ronddraaien', 'Ellebogen buigen', 'Te snel bewegen'],
    primaireSpieren: ['Trapezius'],
    secundaireSpieren: ['Rhomboids', 'Nekspieren'],
  },
  {
    id: 'zercher-squat',
    naam: 'Zercher Squat',
    beschrijving: 'Barbell in de binnenkant van de ellebogen. Armen gekruist voor de borst. Squat omlaag met hoge ellebogen. Unieke variant die core en bovenrug intensief betrekt.',
    uitleg: 'Squat met barbell in de ellebogen. Traint core en bovenrug extra.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen', 'core'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '6-8',
    tempo: '3-1-1',
    tips: ['Gebruik padding op de barbell', 'Ellebogen hoog houden', 'Borst omhoog', 'Begin licht — oncomfortabel gewicht'],
    fouten: ['Ellebogen zakken', 'Borst naar voren vallen', 'Te zwaar voor het niveau'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Core'],
    secundaireSpieren: ['Bovenrug', 'Biceps', 'Hamstrings'],
  },

  // ── BOTH UITBREIDING ──────────────────────────────────────────────────────

  {
    id: 'superset-push-pull',
    naam: 'Push-Pull Superset',
    beschrijving: 'Combineer een push oefening (bench press of dumbbell press) direct met een pull oefening (barbell row of dumbbell row) zonder rust. Dan 60-90 seconden rust. Efficiënt en antagonistisch gebalanceerd.',
    uitleg: 'Press gevolgd door row zonder rust. Efficiënte push-pull combinatie.',
    doel: ['kracht', 'hypertrofie', 'conditie'],
    lichaamsdelen: ['borst', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell', 'barbell'],
    sets: '4',
    herhalingen: '8-10 per oefening',
    tempo: '2-1-2',
    tips: ['Geen rust tussen push en pull', 'Wel 60-90 sec rust na elk superset', 'Houd techniek op peil in vermoeidheid', 'Begin iets lichter dan normaal'],
    fouten: ['Te zwaar gewicht', 'Techniek laten verslechteren', 'Te weinig rust tussen supersets'],
    primaireSpieren: ['Borstspieren', 'Latissimus dorsi'],
    secundaireSpieren: ['Triceps', 'Biceps', 'Schouders'],
  },
  {
    id: 'drop-set-curl',
    naam: 'Drop Set Curl',
    beschrijving: 'Begin met een zwaar gewicht voor 6-8 herhalingen. Zet de dumbbells neer. Pak direct een lichter gewicht en doe nog 8-10 herhalingen. Nog een keer lichter voor 10-12 herhalingen. Intensieve bicepsfinisher.',
    uitleg: 'Drie gewichten achter elkaar afdalend. Biceps intensiteit techniek.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '1 drop set = 3 gewichten',
    herhalingen: '6-8 / 8-10 / 10-12',
    tempo: '2-1-2',
    tips: ['Gewichten klaar leggen voor je begint', 'Minimale tijd tussen gewichten', 'Houd techniek op peil', 'Gebruik als finisher — niet als eerste oefening'],
    fouten: ['Te grote gewichtsverschillen', 'Slechte techniek door vermoeidheid', 'Te veel drop sets per sessie'],
    primaireSpieren: ['Biceps brachii'],
    secundaireSpieren: ['Brachialis', 'Onderarmen'],
  },
  {
    id: 'pause-squat',
    naam: 'Pause Squat',
    beschrijving: 'Back squat of goblet squat waarbij je 2-3 seconden vasthoudt in de bodem. Elimineert het stretch-reflex voordeel. Bouwt meer kracht en controle in de moeilijkste positie.',
    uitleg: 'Squat met pauze in de bodem. Bouwt kracht en controle in de bodem.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell', 'dumbbell'],
    sets: '4',
    herhalingen: '4-6',
    tempo: '3-3-1',
    tips: ['Houd spanning in de bodem', 'Adem niet uit in de bodem', 'Gebruik minder gewicht dan een normale squat', 'Blijf actief — niet slap zakken'],
    fouten: ['Ontspannen in de bodem', 'Te zwaar gewicht', 'Niet lang genoeg pauzeren'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core'],
  },
  {
    id: 'tempo-deadlift',
    naam: 'Tempo Deadlift',
    beschrijving: 'Deadlift met een gecontroleerd tempo — 4-5 seconden excentrisch (zakken). Bouwt kracht in de zwakste punten van de beweging en verbetert techniek.',
    uitleg: 'Langzame deadlift (4-5 sec omlaag). Techniek en kracht in zwakke punten.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gemiddeld',
    equipment: ['barbell', 'dumbbell'],
    sets: '3-4',
    herhalingen: '4-6',
    tempo: '4-1-1',
    tips: ['Gebruik minder gewicht dan normaal', 'Houd spanning in het hele lichaam', 'Rug blijft recht', 'Focus op de moeilijkste positie'],
    fouten: ['Te zwaar gewicht voor het tempo', 'Rug laten zakken bij vermoeidheid', 'Te snel'],
    primaireSpieren: ['Hamstrings', 'Bilspieren', 'Rugspieren'],
    secundaireSpieren: ['Quadriceps', 'Core', 'Trapezius'],
  },
  {
    id: 'db-bulgarian-split-squat',
    naam: 'Dumbbell Bulgaarse Split Squat',
    beschrijving: 'Houd een dumbbell in elke hand. Achterste voet op een bank. Zak door het voorste been. De zwaardere versie met dumbbells verhoogt de belasting significant.',
    uitleg: 'Bulgaarse split squat met dumbbells. Intensieve eenzijdige beentraining.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-10 per been',
    tempo: '3-1-1',
    tips: ['Voorste voet ver genoeg naar voren', 'Romp rechtop', 'Controleer de afdaling', 'Begin zonder gewicht om de positie te vinden'],
    fouten: ['Voorste knie over de teen', 'Romp naar voren leunen', 'Te snel zakken'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core', 'Kuitspieren'],
  },
]

STRENGTH_OEFENINGEN.push(...fase2StrengthOefeningen)

// ── FASE 3 — Richting 80-100 oefeningen ──────────────────────────────────

const fase3StrengthOefeningen: StrengthOefening[] = [

  // ── DUMBBELL FASE 3 ───────────────────────────────────────────────────────

  {
    id: 'db-hip-thrust',
    naam: 'Dumbbell Hip Thrust',
    beschrijving: 'Leun met schouders op een bank. Houd een dumbbell op je heupen. Duw heupen omhoog terwijl je bilspieren maximaal aanspant. Lichtere variant van de barbell hip thrust.',
    uitleg: 'Hip thrust met dumbbell op de heupen. Bilspiertraining zonder barbell.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '2-2-1',
    tips: ['Kin naar borst', 'Bilspieren maximaal aanspannen bovenin', 'Gebruik een pad voor comfort', 'Voeten plat en heupbreedte'],
    fouten: ['Hoofd achterover', 'Rug hol trekken', 'Knieën naar binnen'],
    primaireSpieren: ['Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Quadriceps'],
  },
  {
    id: 'db-arnold-press',
    naam: 'Arnold Press',
    beschrijving: 'Begin met dumbbells voor je gezicht, handpalmen naar je toe. Roteer je polsen terwijl je omhoog drukt — eindig met handpalmen naar voren. Noemt naar Arnold Schwarzenegger. Traint alle koppen van de schouder.',
    uitleg: 'Schouderpress met rotatie. Traint alle drie koppen van de deltoid.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['schouders'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Roteer vloeiend tijdens de beweging', 'Houd core actief', 'Volledig strekken bovenin', 'Controleer de neerwaartse beweging'],
    fouten: ['Te snel bewegen', 'Rug hol trekken', 'Rotatie vergeten'],
    primaireSpieren: ['Schouders', 'Triceps'],
    secundaireSpieren: ['Trapezius', 'Core'],
  },
  {
    id: 'db-concentration-curl',
    naam: 'Concentration Curl',
    beschrijving: 'Zit op een bank. Leun voorover. Ondersteun je elleboog op je binnenkant dij. Curl de dumbbell omhoog. Maximale isolatie van de biceps door volledige stabilisatie.',
    uitleg: 'Biceps curl met elleboog op de dij. Maximale isolatie.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '12-15 per arm',
    tempo: '2-1-3',
    tips: ['Elleboog blijft op de dij', 'Volledig strekken onderaan', 'Langzaam omlaag — 3 seconden', 'Knijp bovenin'],
    fouten: ['Elleboog van de dij bewegen', 'Te snel zakken', 'Schouder mee laten draaien'],
    primaireSpieren: ['Biceps brachii'],
    secundaireSpieren: ['Brachialis'],
  },
  {
    id: 'db-single-leg-rdl',
    naam: 'Single Leg Romanian Deadlift',
    beschrijving: 'Sta op één been met een dumbbell in de tegenovergestelde hand. Buig naar voren vanuit de heup terwijl je vrije been achterwaarts omhoog gaat. Traint hamstrings en balans tegelijk.',
    uitleg: 'Eénbeen RDL met dumbbell. Hamstrings, bilspieren en balans.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10 per been',
    tempo: '3-1-1',
    tips: ['Houd heupen level — niet roteren', 'Vrije been gaat recht achterwaarts', 'Rug recht houden', 'Gebruik een muur voor balans als nodig'],
    fouten: ['Heupen roteren', 'Rug afronden', 'Standbeen te sterk buigen'],
    primaireSpieren: ['Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Core', 'Rugspieren', 'Enkels'],
  },
  {
    id: 'db-bent-over-row',
    naam: 'Dumbbell Bent Over Row',
    beschrijving: 'Sta met beide dumbbells. Leun voorover met rechte rug. Trek beide dumbbells tegelijk naar je buik. Bilaterale variant van de dumbbell row.',
    uitleg: 'Voorovergebogen beide dumbbells optrekken. Rugtraining bilateraal.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Rug recht — lichte curve', 'Trek naar de buik', 'Schouderbladen samentrekken', 'Ellebogen dicht langs het lichaam'],
    fouten: ['Rug afronden', 'Romp omhoog bewegen', 'Trek naar de borst'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Achterste schouder', 'Core'],
  },
  {
    id: 'db-floor-press',
    naam: 'Dumbbell Floor Press',
    beschrijving: 'Lig op de grond met dumbbells. Druk omhoog vanuit de grond. Beperkte range of motion door de grond elimineert de onderste fase. Minder schouderbelasting dan een bench press.',
    uitleg: 'Dumbbell press op de grond. Minder schouderbelasting, meer triceps.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-2',
    tips: ['Ellebogen raken licht de grond', 'Schouderbladen ingetrokken', 'Voeten plat op de grond', 'Goed alternatief zonder bank'],
    fouten: ['Ellebogen hard op de grond slaan', 'Schouders optrekken', 'Heupen optillen'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders'],
  },

  // ── BARBELL FASE 3 ────────────────────────────────────────────────────────

  {
    id: 'barbell-hip-thrust-pause',
    naam: 'Barbell Hip Thrust met Pauze',
    beschrijving: 'Hip thrust waarbij je 2-3 seconden vasthoudt in de bovenste positie. Maximale bilspier activatie door de gepauzeerde contractie. Effectiever dan een reguliere hip thrust.',
    uitleg: 'Hip thrust met 2-3 sec pauze bovenin. Maximale bilspier activatie.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-3-1',
    tips: ['Knijp bilspieren maximaal in de pauze', 'Kin naar borst blijven', 'Tel de pauze bewust', 'Gebruik minder gewicht dan zonder pauze'],
    fouten: ['Pauze te kort', 'Ontspannen in de pauze', 'Rug hol trekken'],
    primaireSpieren: ['Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Core'],
  },
  {
    id: 'barbell-deficit-deadlift',
    naam: 'Deficit Deadlift',
    beschrijving: 'Deadlift waarbij je op een verhoging staat van 5-10 cm. Vergroot de range of motion. Traint de zwakke startpositie van de deadlift.',
    uitleg: 'Deadlift staand op een verhoging. Grotere range of motion.',
    doel: ['kracht'],
    lichaamsdelen: ['benen', 'billen', 'rug'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4',
    herhalingen: '3-5',
    tempo: '2-1-1',
    tips: ['Gebruik minder gewicht dan normale deadlift', 'Vereist goede heupmobiliteit', 'Rug recht houden', 'Verhoging van max 10 cm'],
    fouten: ['Te hoge verhoging', 'Rug afronden door de extra range', 'Te zwaar gewicht'],
    primaireSpieren: ['Hamstrings', 'Bilspieren', 'Rugspieren'],
    secundaireSpieren: ['Quadriceps', 'Core'],
  },
  {
    id: 'barbell-pause-bench',
    naam: 'Pause Bench Press',
    beschrijving: 'Bench press waarbij je 2-3 seconden vasthoudt op de borst. Elimineert het stuiteren en bounce. Bouwt kracht in de bodem van de beweging.',
    uitleg: 'Bench press met pauze op de borst. Bouwt kracht in de zwakste positie.',
    doel: ['kracht'],
    lichaamsdelen: ['borst'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '3-5',
    tempo: '2-3-1',
    tips: ['Stang echt op de borst — niet zweefpauze', 'Behoud spanning in de pauze', 'Gebruik minder gewicht', 'Schouderbladen ingetrokken blijven'],
    fouten: ['Stuiteren na de pauze', 'Spanning verliezen in de pauze', 'Te zwaar'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders'],
  },
  {
    id: 'barbell-rack-pull',
    naam: 'Rack Pull',
    beschrijving: 'Deadlift vanuit een hogere startpositie — stang in het rack op kniehoogte. Traint de lock-out fase van de deadlift en laat meer gewicht toe.',
    uitleg: 'Deadlift vanuit kniehoogte. Traint lock-out en laat meer gewicht toe.',
    doel: ['kracht'],
    lichaamsdelen: ['rug', 'benen'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '3-5',
    tempo: '1-1-2',
    tips: ['Bilspieren aanspannen bij lock-out', 'Rug recht', 'Stang dicht langs de benen', 'Gebruik straps voor grip'],
    fouten: ['Rug afronden', 'Knieën achteruitzetten bij de start', 'Niet volledig locken'],
    primaireSpieren: ['Rugspieren', 'Hamstrings', 'Bilspieren'],
    secundaireSpieren: ['Trapezius', 'Core', 'Onderarmen'],
  },
  {
    id: 'barbell-rdl-row',
    naam: 'RDL naar Row Combinatie',
    beschrijving: 'Combineer een Romanian deadlift met een barbell row in één beweging. Zak naar de RDL positie, doe een row, kom terug. Efficiënte posterior chain oefening.',
    uitleg: 'RDL gecombineerd met row. Rug en hamstrings in één beweging.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['rug', 'benen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3',
    herhalingen: '8-10',
    tempo: '3-1-2',
    tips: ['Houd de RDL positie stabiel voor de row', 'Rug recht gedurende de hele beweging', 'Trek naar de buik', 'Lichtere gewicht dan separate oefeningen'],
    fouten: ['Rug afronden bij de row', 'Te snel bewegen', 'Te zwaar'],
    primaireSpieren: ['Hamstrings', 'Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Bilspieren', 'Biceps', 'Core'],
  },

  // ── BOTH FASE 3 ───────────────────────────────────────────────────────────

  {
    id: 'giant-set-legs',
    naam: 'Giant Set Benen',
    beschrijving: 'Vier beenoefeningingen achter elkaar zonder rust: squat → RDL → lunge → kuitverheffen. Dan 2-3 minuten rust. Intensieve beensessie in korte tijd.',
    uitleg: 'Vier beensoefeningen achter elkaar. Intensief, tijdefficiënt.',
    doel: ['hypertrofie', 'conditie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gevorderd',
    equipment: ['barbell', 'dumbbell'],
    sets: '3-4',
    herhalingen: '10-12 per oefening',
    tempo: 'continu',
    tips: ['Lichtere gewichten dan normale sets', 'Bereid alles voor van tevoren', 'Adem bewust', 'Rust 2-3 min tussen giant sets'],
    fouten: ['Te zwaar gewicht', 'Techniek laten verslechteren', 'Te weinig rust'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Kuitspieren'],
  },
  {
    id: 'giant-set-upper',
    naam: 'Giant Set Bovenlichaam',
    beschrijving: 'Vier bovenlichaam oefeningen achter elkaar: bench press → row → overhead press → curl. Dan 2-3 minuten rust. Volledige bovenlichaam sessie.',
    uitleg: 'Vier bovenlichaam oefeningen achter elkaar. Push-pull-press-curl.',
    doel: ['hypertrofie', 'conditie'],
    lichaamsdelen: ['borst', 'rug', 'schouders', 'armen'],
    niveau: 'gevorderd',
    equipment: ['barbell', 'dumbbell'],
    sets: '3',
    herhalingen: '10 per oefening',
    tempo: 'continu',
    tips: ['Plan de oefeningen logistiek', 'Lichtere gewichten', 'Rust 2-3 min tussen sets', 'Houd techniek op peil'],
    fouten: ['Te zwaar', 'Geen plan gemaakt', 'Te weinig rust'],
    primaireSpieren: ['Volledig bovenlichaam'],
    secundaireSpieren: ['Core'],
  },
  {
    id: 'wave-loading',
    naam: 'Wave Loading',
    beschrijving: 'Drie sets met oplopend gewicht (85-90-95%), dan opnieuw beginnen met iets hoger gewicht dan de eerste golf. Neurologische aanpassingsprotocol voor kracht.',
    uitleg: 'Oplopende gewichten in golven. Neurologisch krachtprotocol.',
    doel: ['kracht'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '6 (2 golven van 3)',
    herhalingen: '3-3-3 / 2-2-2',
    tempo: '2-1-1',
    tips: ['Eerste golf conservatief', 'Tweede golf 2-5% zwaarder', 'Langere rust tussen sets (3-5 min)', 'Goed voor ervaren krachtsporters'],
    fouten: ['Eerste golf te zwaar', 'Te weinig rust', 'Geen progressie in de tweede golf'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Neuraal systeem'],
  },
  {
    id: 'cluster-set',
    naam: 'Cluster Set',
    beschrijving: 'Doe 2-3 herhalingen, rust 15-20 seconden, doe nog 2-3 herhalingen — totaal 6-9 herhalingen per cluster. Meer totaal volume met zwaarder gewicht dan normale sets.',
    uitleg: 'Sets met korte pauzes tussendoor. Meer volume met zwaarder gewicht.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gevorderd',
    equipment: ['barbell', 'dumbbell'],
    sets: '3-4 clusters',
    herhalingen: '2-3 + 15sec + 2-3 + 15sec + 2-3',
    tempo: '2-1-1',
    tips: ['Gebruik zwaarder gewicht dan normale sets', 'Houd de 15-20 sec pauze strikt', 'Goed voor plateau doorbreken', 'Rust 3-4 min tussen clusters'],
    fouten: ['Te lange pauzes — geen cluster meer', 'Te zwaar gewicht', 'Te weinig rust tussen clusters'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Core'],
  },
  {
    id: 'pre-exhaust',
    naam: 'Pre-Exhaust Superset',
    beschrijving: 'Doe eerst een isolatie oefening om de doelspier te vermoeiden, direct gevolgd door een compound oefening. Bijv. lateral raise → overhead press, of chest fly → bench press.',
    uitleg: 'Isolatie direct gevolgd door compound. Voorvermoeit de doelspier.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['schouders', 'borst'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell', 'barbell'],
    sets: '3-4',
    herhalingen: '12-15 isolatie + 8-10 compound',
    tempo: '2-1-2',
    tips: ['Geen rust tussen de twee oefeningen', 'Compound iets lichter dan normaal', 'Voel de doelspier werken', 'Gebruik voor plateaus'],
    fouten: ['Te zwaar voor de compound na de isolatie', 'Rust tussen de oefeningen nemen', 'Techniek laten verslechteren'],
    primaireSpieren: ['Afhankelijk van de keuze'],
    secundaireSpieren: ['Synergisten'],
  },
  {
    id: 'mechanical-drop-set',
    naam: 'Mechanische Drop Set',
    beschrijving: 'Doe een oefening tot bijna falen, wissel dan naar een makkelijkere variant van dezelfde beweging zonder rust. Bijv. decline push-up → normale push-up → incline push-up.',
    uitleg: 'Moeilijkere naar makkelijkere variant zonder rust. Meer volume.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['borst', 'schouders'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell', 'barbell'],
    sets: '3',
    herhalingen: 'tot bijna falen per variant',
    tempo: '2-1-2',
    tips: ['Kies drie varianten van moeilijk naar makkelijk', 'Geen rust tussen varianten', 'Stop net voor falen voor veiligheid', 'Goed voor bodyweight en dumbbell oefeningen'],
    fouten: ['Echte technische fout doorzetten', 'Rust nemen tussen varianten', 'Geen goede progressie van varianten'],
    primaireSpieren: ['Afhankelijk van de keuze'],
    secundaireSpieren: ['Synergisten'],
  },
]

STRENGTH_OEFENINGEN.push(...fase3StrengthOefeningen)

// ── FASE 4 — Richting 100 oefeningen ─────────────────────────────────────

const fase4StrengthOefeningen: StrengthOefening[] = [

  // ── DUMBBELL FASE 4 ───────────────────────────────────────────────────────

  {
    id: 'db-goblet-squat-lateral',
    naam: 'Goblet Squat met Zijstap',
    beschrijving: 'Goblet squat gecombineerd met een zijwaartse stap. Stap opzij, squat, kom omhoog, breng voeten terug. Traint bilspieren en binnenkant dij extra.',
    uitleg: 'Goblet squat met zijstap. Bilspieren en binnenkant dij extra actief.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10 per kant',
    tempo: '2-1-1',
    tips: ['Stap breed genoeg', 'Squat in de zijstaande positie', 'Knieën volgen de tenen', 'Houd dumbbell stabiel'],
    fouten: ['Te kleine stap', 'Geen echte squat diepte', 'Knieën naar binnen'],
    primaireSpieren: ['Bilspieren', 'Quadriceps', 'Heupabductoren'],
    secundaireSpieren: ['Binnenkant dij', 'Core'],
  },
  {
    id: 'db-incline-curl',
    naam: 'Incline Dumbbell Curl',
    beschrijving: 'Lig op een schuine bank (45-60 graden). Laat de dumbbells hangen. Curl omhoog. De schuine positie vergroot de stretch op de biceps en isoleert de lange kop.',
    uitleg: 'Biceps curl op schuine bank. Maximale biceps stretch en isolatie.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-3',
    tips: ['Laat de armen volledig hangen onderaan', 'Beweeg alleen de onderarmen', 'Langzaam omlaag — 3 seconden', 'Bank op 45-60 graden'],
    fouten: ['Schouders naar voren bewegen', 'Te snel zakken', 'Ellebogen naar voren'],
    primaireSpieren: ['Biceps brachii lange kop'],
    secundaireSpieren: ['Brachialis', 'Brachioradialis'],
  },
  {
    id: 'db-overhead-triceps',
    naam: 'Dumbbell Overhead Triceps',
    beschrijving: 'Sta of zit. Houd één zware dumbbell met beide handen boven je hoofd. Laat zakken achter je hoofd. Strek omhoog. Traint de lange kop van de triceps in gestrekte positie.',
    uitleg: 'Één dumbbell met beide handen boven het hoofd. Lange kop triceps.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15',
    tempo: '3-1-1',
    tips: ['Ellebogen dicht bij het hoofd', 'Volledige range — zo ver mogelijk naar beneden', 'Core actief voor rugbescherming', 'Gebruik één zwaardere dumbbell'],
    fouten: ['Ellebogen naar buiten', 'Onvoldoende diepte', 'Rug hol trekken'],
    primaireSpieren: ['Triceps lange kop'],
    secundaireSpieren: ['Schouders'],
  },
  {
    id: 'db-lateral-lunge-curl',
    naam: 'Zijwaartse Lunge met Curl',
    beschrijving: 'Combineer een zijwaartse lunge met een biceps curl in de diepte van de lunge. Stap opzij, zak in de lunge, curl de dumbbells, kom omhoog. Functionele combinatieoefening.',
    uitleg: 'Zijlunge gecombineerd met curl. Benen en armen tegelijk.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['benen', 'armen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '10 per kant',
    tempo: '2-1-1',
    tips: ['Curl in de diepte van de lunge', 'Houd borst omhoog', 'Gebruik lichte dumbbells', 'Beweeg vloeiend'],
    fouten: ['Curl niet in de lunge positie', 'Te zwaar voor de combinatie', 'Evenwicht verliezen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Biceps'],
    secundaireSpieren: ['Binnenkant dij', 'Core'],
  },
  {
    id: 'db-renegade-row',
    naam: 'Renegade Row',
    beschrijving: 'Begin in een plankpositie met handen op dumbbells. Trek één dumbbell omhoog naar je heup terwijl je het andere arm steunt. Wissel. Combineert plankhoud met row.',
    uitleg: 'Plank op dumbbells, één arm optrekken. Core en rug tegelijk.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['rug', 'core'],
    niveau: 'gevorderd',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-10 per arm',
    tempo: '2-1-2',
    tips: ['Heupen zo stabiel mogelijk', 'Gebruik hexagonale dumbbells voor stabiliteit', 'Core maximaal aanspannen', 'Voeten iets breder voor stabiliteit'],
    fouten: ['Heupen roteren bij het trekken', 'Core laten zakken', 'Te zwaar gewicht'],
    primaireSpieren: ['Latissimus dorsi', 'Core', 'Obliques'],
    secundaireSpieren: ['Schouders', 'Biceps', 'Borst'],
  },
  {
    id: 'db-thruster',
    naam: 'Dumbbell Thruster',
    beschrijving: 'Combineer een front squat met een overhead press in één vloeiende beweging. Zak in de squat, drijf omhoog en gebruik de energie om de dumbbells overhead te drukken. Conditioneel en functioneel.',
    uitleg: 'Squat direct gevolgd door overhead press. Conditionele full body oefening.',
    doel: ['conditie', 'kracht'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: 'explosief',
    tips: ['Gebruik de squat energie voor de press', 'Dumbbells op schouderhoogte in de squat', 'Houd een vloeiend ritme', 'Gebruik lichte gewichten'],
    fouten: ['Squat en press als aparte bewegingen', 'Te zwaar gewicht', 'Core laten zakken'],
    primaireSpieren: ['Quadriceps', 'Bilspieren', 'Schouders', 'Triceps'],
    secundaireSpieren: ['Core', 'Hamstrings'],
  },

  // ── BARBELL FASE 4 ────────────────────────────────────────────────────────

  {
    id: 'barbell-snatch-grip-dl',
    naam: 'Snatch Grip Deadlift',
    beschrijving: 'Deadlift met een brede greep — handen wijd uiteen. Vergroot de range of motion en betrekt de bovenrug meer. Goed voor atleten en gevorderden.',
    uitleg: 'Deadlift met brede greep. Meer bovenrug en grotere range of motion.',
    doel: ['kracht'],
    lichaamsdelen: ['rug', 'benen'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4',
    herhalingen: '4-5',
    tempo: '2-1-2',
    tips: ['Gebruik minder gewicht door de langere hefboom', 'Rug recht houden', 'Heupen lager dan bij conventional', 'Straps nuttig voor grip'],
    fouten: ['Te zwaar gewicht', 'Rug afronden', 'Greep te smal'],
    primaireSpieren: ['Rugspieren', 'Hamstrings', 'Trapezius'],
    secundaireSpieren: ['Bilspieren', 'Core', 'Onderarmen'],
  },
  {
    id: 'barbell-floor-press',
    naam: 'Barbell Floor Press',
    beschrijving: 'Bench press op de grond. Ellebogen raken de grond bij elke herhaling. Beperkte range elimineert de bodemfase. Minder schouderbelasting en meer tricepsfocus.',
    uitleg: 'Barbell press op de grond. Minder schouderbelasting, meer triceps.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['borst', 'armen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '6-10',
    tempo: '2-1-2',
    tips: ['Ellebogen raken de grond bij elke herhaling', 'Schouderbladen ingetrokken', 'Voeten plat of gestrekt', 'Goed alternatief zonder bank'],
    fouten: ['Ellebogen hard op de grond slaan', 'Geen volledige stop onderaan', 'Schouders optrekken'],
    primaireSpieren: ['Borstspieren', 'Triceps'],
    secundaireSpieren: ['Schouders'],
  },
  {
    id: 'barbell-high-pull',
    naam: 'Barbell High Pull',
    beschrijving: 'Trek de barbell explosief omhoog van de dijen tot kin hoogte terwijl je op je tenen komt. Combinatie van kracht en explosiviteit. Voorloper van de power clean.',
    uitleg: 'Explosief barbell omhoog trekken tot kin. Kracht en snelheid.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['fullbody', 'schouders'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '4-5',
    herhalingen: '4-6',
    tempo: 'explosief',
    tips: ['Begin met heupen in een hinge positie', 'Explosieve hip drive', 'Ellebogen hoog — hoger dan de stang', 'Gebruik minder gewicht dan een deadlift'],
    fouten: ['Geen hip drive', 'Armen te vroeg buigen', 'Te zwaar gewicht'],
    primaireSpieren: ['Trapezius', 'Schouders', 'Bilspieren'],
    secundaireSpieren: ['Hamstrings', 'Kuiten', 'Biceps'],
  },
  {
    id: 'barbell-landmine-press',
    naam: 'Landmine Press',
    beschrijving: 'Zet één kant van de barbell in een hoek (of gebruik een landmine attachment). Houd het andere uiteinde vast en druk schuin omhoog. Schoudervriendelijke pressvariant.',
    uitleg: 'Barbell in de hoek duwen schuin omhoog. Schoudervriendelijke press.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['schouders', 'borst'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-12 per arm',
    tempo: '2-1-2',
    tips: ['Druk schuin omhoog — niet recht', 'Core actief houden', 'Goed voor mensen met schouderklachten', 'Kan ook bilateraal uitgevoerd worden'],
    fouten: ['Te recht omhoog drukken', 'Core laten zakken', 'Te zwaar gewicht'],
    primaireSpieren: ['Schouders', 'Borst'],
    secundaireSpieren: ['Triceps', 'Core'],
  },

  // ── BOTH FASE 4 ───────────────────────────────────────────────────────────

  {
    id: 'periodization-block-strength',
    naam: 'Krachtblok (3-5 rep range)',
    beschrijving: 'Gestructureerde krachtsessie: compound oefeningen in 3-5 rep range met 85-90% van maximum. Lange rust tussen sets (3-5 min). Neuromusculaire krachtontwikkeling.',
    uitleg: 'Zware compound oefeningen 3-5 reps. Neuromusculaire krachtontwikkeling.',
    doel: ['kracht'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gevorderd',
    equipment: ['barbell', 'dumbbell'],
    sets: '5',
    herhalingen: '3-5',
    tempo: '2-1-1',
    tips: ['85-90% van je maximum', 'Rust 3-5 min tussen sets', 'Focus op techniek onder zware belasting', 'Progressieve overload van week tot week'],
    fouten: ['Te weinig rust', 'Te snel progressie', 'Techniek verwaarlozen'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Neuraal systeem', 'Core'],
  },
  {
    id: 'periodization-block-hypertrophy',
    naam: 'Hypertrofieblok (8-12 rep range)',
    beschrijving: 'Gestructureerde hypertrofiesessie: oefeningen in 8-12 rep range met 70-80% van maximum. Matige rust (60-90 sec). Maximale spierstimulatie voor groei.',
    uitleg: 'Matig gewicht 8-12 reps. Optimale rep range voor spiergroei.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['barbell', 'dumbbell'],
    sets: '4',
    herhalingen: '8-12',
    tempo: '3-1-2',
    tips: ['70-80% van je maximum', 'Rust 60-90 sec', 'Laatste 2-3 reps moeten uitdagend zijn', 'Focus op de squeeze in de top positie'],
    fouten: ['Te zwaar — rep range klopt niet', 'Te veel rust', 'Geen progressie over weken'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Core'],
  },
  {
    id: 'active-recovery-lifting',
    naam: 'Actief Herstel met Gewichten',
    beschrijving: 'Lichte sessie op hersteldag: 40-50% van maximum, hoge reps, vloeiende bewegingen. Verhoogt doorbloeding en vermindert spierpijn zonder extra vermoeidheid te creëren.',
    uitleg: 'Lichte gewichten op hersteldag. Doorbloeding verhogen, spierpijn verminderen.',
    doel: ['herstel'],
    lichaamsdelen: ['fullbody'],
    niveau: 'beginner',
    equipment: ['dumbbell', 'barbell'],
    sets: '2-3',
    herhalingen: '15-20',
    tempo: '2-1-2',
    tips: ['Maximum 40-50% van je normale gewicht', 'Vloeiende, gecontroleerde bewegingen', 'Geen poging tot falen', 'Focus op bewegingskwaliteit'],
    fouten: ['Te zwaar gewicht', 'Toch intensief trainen', 'Uitgeput raken'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Cardiovasculair systeem'],
  },
  {
    id: 'strength-circuit',
    naam: 'Krachtcircuit',
    beschrijving: 'Circuit van 5-6 krachtoefeningen met matig gewicht. Elke oefening 45 seconden, 15 seconden rust, dan door naar de volgende. Na de ronde 2 minuten rust. Combineert kracht en conditie.',
    uitleg: 'Krachtoefeningen in circuitvorm. Combinatie van kracht en conditie.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell', 'barbell'],
    sets: '3-4 ronden',
    herhalingen: '45 sec per oefening',
    tempo: 'continu',
    tips: ['Matig gewicht — techniek moet kloppen', 'Maximaal 15 sec rust tussen oefeningen', '2 min rust tussen ronden', 'Kies oefeningen die niet dezelfde spieren treffen'],
    fouten: ['Te zwaar gewicht', 'Te lange rust', 'Techniek laten verslechteren door vermoeidheid'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Cardiovasculair systeem', 'Core'],
  },
  {
    id: 'emom-strength',
    naam: 'EMOM Kracht',
    beschrijving: 'Every Minute On the Minute: aan het begin van elke minuut voer je een vaste set uit. De resterende tijd is rust. Bijv. 5 deadlifts elke minuut gedurende 10 minuten.',
    uitleg: 'Elke minuut een set uitvoeren. Gestructureerde kracht en conditie.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['barbell', 'dumbbell'],
    sets: '10-20 minuten',
    herhalingen: '3-6 per minuut',
    tempo: 'gecontroleerd',
    tips: ['Kies een gewicht waarbij je 20-30 sec hebt na de set', 'Consistente techniek elke minuut', 'Begin conservatief', 'Gebruik een timer'],
    fouten: ['Te zwaar — geen rust meer', 'Techniek verslechtert naarmate vermoeidheid oploopt', 'Geen timer gebruiken'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Cardiovasculair systeem'],
  },
]

STRENGTH_OEFENINGEN.push(...fase4StrengthOefeningen)

// ── FASE 5 — Voltooiing naar 100 oefeningen ───────────────────────────────

const fase5StrengthOefeningen: StrengthOefening[] = [
  {
    id: 'db-seal-row',
    naam: 'Seal Row',
    beschrijving: 'Lig op je buik op een verhoogde bank. Laat dumbbells hangen. Trek omhoog naar je borst. Volledig geïsoleerde rugtraining — geen romp compensatie mogelijk.',
    uitleg: 'Liggend op een bank dumbbells optrekken. Volledig geïsoleerde rugtraining.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['rug'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '2-1-3',
    tips: ['Bank hoog genoeg zodat dumbbells hangen', 'Trek naar de borst', 'Schouderbladen samentrekken bovenin', 'Langzaam omlaag'],
    fouten: ['Bank te laag', 'Momentum gebruiken', 'Niet volledig laten hangen onderaan'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Achterste schouder'],
  },
  {
    id: 'db-meadows-row',
    naam: 'Meadows Row',
    beschrijving: 'Sta naast een dumbbell. Stap met één been achteruit. Pak de dumbbell met de ipsilaterale hand. Trek schuin omhoog en naar buiten. Extreme lat activatie door de hoek.',
    uitleg: 'Eénarmige row met unieke hoek voor maximale lat activatie.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '10-12 per arm',
    tempo: '2-1-2',
    tips: ['Trek schuin naar buiten — niet recht omhoog', 'Houd romp stabiel', 'Voel de lat werken', 'Gebruik een zwaarder gewicht dan normale row'],
    fouten: ['Te recht omhoog trekken', 'Romp roteren', 'Te licht gewicht'],
    primaireSpieren: ['Latissimus dorsi'],
    secundaireSpieren: ['Teres major', 'Biceps', 'Core'],
  },
  {
    id: 'db-spider-curl',
    naam: 'Spider Curl',
    beschrijving: 'Lig op je buik op een schuine bank. Laat dumbbells hangen. Curl omhoog terwijl je bovenarm verticaal blijft. Maximaliseert de korte kop van de biceps.',
    uitleg: 'Biceps curl liggend op schuine bank. Korte kop biceps focus.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '12-15',
    tempo: '2-1-3',
    tips: ['Bovenarm blijft verticaal', 'Volledig strekken onderaan', 'Langzaam omlaag', 'Gebruik lichte dumbbells'],
    fouten: ['Bovenarm naar voren bewegen', 'Te snel zakken', 'Te zwaar gewicht'],
    primaireSpieren: ['Biceps korte kop'],
    secundaireSpieren: ['Brachialis'],
  },
  {
    id: 'db-kickback',
    naam: 'Dumbbell Kickback',
    beschrijving: 'Leun voorover. Houd de bovenarm parallel aan de grond. Strek de onderarm naar achteren. Houd 1 seconde vast. Traint de triceps in gecontracteerde positie.',
    uitleg: 'Triceps strekken naar achteren. Maximale contractie van de triceps.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['armen'],
    niveau: 'beginner',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '12-15 per arm',
    tempo: '2-1-2',
    tips: ['Bovenarm parallel aan de grond houden', 'Houd 1 sec vast bij volledige strekking', 'Gebruik een licht gewicht', 'Leun voorover voor juiste hoek'],
    fouten: ['Bovenarm niet parallel', 'Zwaaien voor momentum', 'Te zwaar gewicht'],
    primaireSpieren: ['Triceps brachii'],
    secundaireSpieren: ['Achterste schouder'],
  },
  {
    id: 'barbell-jefferson-curl',
    naam: 'Jefferson Curl',
    beschrijving: 'Sta op een verhoging. Rol je ruggengraat langzaam omlaag — wervel voor wervel. Laat de barbell hangen en zak zo laag mogelijk. Mobiliteit en kracht in de ruggengraat.',
    uitleg: 'Gecontroleerd afronden van de wervelkolom. Rugmobiliteit en kracht.',
    doel: ['herstel', 'kracht'],
    lichaamsdelen: ['rug', 'benen'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '3',
    herhalingen: '5-8',
    tempo: '4-2-4',
    tips: ['Gebruik een zeer licht gewicht', 'Rol wervel voor wervel omlaag', 'Volledig ontspannen omlaag', 'Heb geduld — mobiliteitswerk'],
    fouten: ['Te zwaar gewicht', 'Te snel bewegen', 'Knieën buigen'],
    primaireSpieren: ['Rugspieren', 'Hamstrings'],
    secundaireSpieren: ['Core', 'Nekspieren'],
  },
  {
    id: 'barbell-landmine-squat',
    naam: 'Landmine Squat',
    beschrijving: 'Houd het uiteinde van een barbell voor je borst. Squat terwijl je de barbell vasthoud. De hoek van de barbell helpt met rechtop blijven. Schoudervriendelijk en makkelijker dan back squat.',
    uitleg: 'Squat met barbell uitende voor de borst. Makkelijker om rechtop te blijven.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'beginner',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '10-12',
    tempo: '3-1-1',
    tips: ['Houd het uiteinde dicht bij de borst', 'Knieën ver naar voren mogelijk', 'Goed voor mensen met rugproblemen', 'Kan ook eenarmig uitgevoerd worden'],
    fouten: ['Barbell te ver van het lichaam', 'Borst naar voren vallen', 'Knieën naar binnen'],
    primaireSpieren: ['Quadriceps', 'Bilspieren'],
    secundaireSpieren: ['Core', 'Schouders'],
  },
  {
    id: 'barbell-yates-row',
    naam: 'Yates Row',
    beschrijving: 'Barbell row met een meer rechtopstaande torso dan een conventional row. Underhand greep. Traint de dikke rugspieren met meer bicepsactivatie. Vernoemd naar Dorian Yates.',
    uitleg: 'Meer rechtopstaande barbell row met underhand greep. Rug en biceps.',
    doel: ['hypertrofie', 'kracht'],
    lichaamsdelen: ['rug', 'armen'],
    niveau: 'gemiddeld',
    equipment: ['barbell'],
    sets: '3-4',
    herhalingen: '8-10',
    tempo: '2-1-2',
    tips: ['Torso op 70-80 graden — niet parallel', 'Underhand greep', 'Trek naar de buik', 'Meer gewicht mogelijk dan parallel row'],
    fouten: ['Te rechtop staan — wordt een curl', 'Overhand greep gebruiken', 'Momentum gebruiken'],
    primaireSpieren: ['Latissimus dorsi', 'Biceps'],
    secundaireSpieren: ['Rhomboids', 'Trapezius'],
  },
  {
    id: 'conjugate-method-set',
    naam: 'Conjugate Methode Set',
    beschrijving: 'Afwisseling van maximale krachtsets (1-3 reps, 90%+) en dynamische sets (8-10 reps, 50-60% explosief). Westside Barbell gebaseerde aanpak voor gelijktijdige kracht en snelheidsontwikkeling.',
    uitleg: 'Combinatie van zware en explosieve sets. Kracht en snelheid tegelijk.',
    doel: ['kracht'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gevorderd',
    equipment: ['barbell'],
    sets: '10 (5 zwaar + 5 explosief)',
    herhalingen: '1-3 zwaar / 8-10 explosief',
    tempo: 'variabel',
    tips: ['Zwaar: 90%+ van max', 'Explosief: 50-60% zo snel mogelijk', 'Rust 3-5 min tussen zware sets', 'Gevorderde techniek vereist'],
    fouten: ['Explosief gedeelte te zwaar', 'Niet explosief genoeg bij lichte sets', 'Te weinig rust'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Neuraal systeem'],
  },
  {
    id: 'amrap-strength',
    naam: 'AMRAP Set',
    beschrijving: 'As Many Reps As Possible: voer zoveel herhalingen uit als mogelijk met een vastgesteld gewicht in een set. Meet je voortgang door het aantal reps bij te houden over weken.',
    uitleg: 'Zoveel mogelijk herhalingen met een vastgesteld gewicht. Progressiemeting.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['barbell', 'dumbbell'],
    sets: '1-2 AMRAP sets',
    herhalingen: 'maximaal',
    tempo: 'gecontroleerd',
    tips: ['Gebruik 70-80% van je max', 'Stop 1-2 reps voor technisch falen', 'Noteer het aantal reps', 'Gebruik als laatste set van een oefening'],
    fouten: ['Te zwaar gewicht', 'Techniek laten verslechteren', 'Niet bijhouden voor progressie'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Core'],
  },
  {
    id: 'rest-pause-set',
    naam: 'Rest-Pause Set',
    beschrijving: 'Doe een set tot bijna falen. Rust 15-20 seconden. Doe nog zoveel mogelijk herhalingen. Rust opnieuw 15-20 seconden. Nog een mini-set. Verhoogt het volume significant.',
    uitleg: 'Set met korte pauzes tot bijna falen. Verhoogt volume aanzienlijk.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell', 'barbell'],
    sets: '2-3 rest-pause sets',
    herhalingen: 'tot bijna falen + 15sec + max + 15sec + max',
    tempo: '2-1-2',
    tips: ['Stop net voor technisch falen', 'Houd de 15-20 sec strikt', 'Gebruik als finisher', 'Rust 3-4 min tussen rest-pause sets'],
    fouten: ['Te lang rusten — wordt geen rest-pause meer', 'Technisch falen doorzetten', 'Te zwaar gewicht'],
    primaireSpieren: ['Afhankelijk van de oefening'],
    secundaireSpieren: ['Core'],
  },
  {
    id: 'db-seal-row-pause',
    naam: 'Paused Dumbbell Row',
    beschrijving: 'Dumbbell row waarbij je 2-3 seconden vasthoudt in de gecontracteerde positie — elleboog omhoog, schouderblad ingetrokken. Maximale spieractivatie door de pauze.',
    uitleg: 'Dumbbell row met pauze bovenin. Maximale rugspier activatie.',
    doel: ['hypertrofie'],
    lichaamsdelen: ['rug'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3-4',
    herhalingen: '8-10 per arm',
    tempo: '2-3-2',
    tips: ['Knijp het schouderblad samen in de pauze', 'Tel de pauze bewust', 'Gebruik minder gewicht dan zonder pauze', 'Voel de lat en rhomboids werken'],
    fouten: ['Pauze te kort', 'Schouderblad niet samentrekken', 'Te zwaar gewicht'],
    primaireSpieren: ['Latissimus dorsi', 'Rhomboids'],
    secundaireSpieren: ['Biceps', 'Achterste schouder'],
  },
  {
    id: 'barbell-romanian-pause',
    naam: 'Paused Romanian Deadlift',
    beschrijving: 'Romanian deadlift waarbij je 2-3 seconden vasthoudt op het punt van maximale hamstring stretch. Elimineert momentum en maximaliseert de excentrische fase.',
    uitleg: 'RDL met pauze op maximale stretch. Hamstring activatie maximaal.',
    doel: ['kracht', 'hypertrofie'],
    lichaamsdelen: ['benen', 'billen'],
    niveau: 'gemiddeld',
    equipment: ['barbell', 'dumbbell'],
    sets: '3-4',
    herhalingen: '8-10',
    tempo: '3-3-1',
    tips: ['Houd spanning in de hamstrings in de pauze', 'Rug recht tijdens de pauze', 'Gebruik minder gewicht', 'Voel de stretch maximaal'],
    fouten: ['Rug afronden in de pauze', 'Te kort pauzeren', 'Te zwaar gewicht'],
    primaireSpieren: ['Hamstrings'],
    secundaireSpieren: ['Bilspieren', 'Rugspieren'],
  },
  {
    id: 'loaded-carry-complex',
    naam: 'Loaded Carry Complex',
    beschrijving: 'Combinatie van drie carry varianten achter elkaar: farmer carry (beide handen) → suitcase carry (één hand) → overhead carry (één arm omhoog). Traint grip, core en stabiliteit.',
    uitleg: 'Drie carry varianten achter elkaar. Grip, core en stabiliteit.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['core', 'fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '3',
    herhalingen: '20 meter per variant',
    tempo: 'continu',
    tips: ['Bereid de route voor', 'Schouders naar achteren in alle varianten', 'Houd een rechte romp', 'Licht tot matig gewicht'],
    fouten: ['Te zwaar gewicht', 'Romp naar de zijkant leunen', 'Schouders optrekken'],
    primaireSpieren: ['Core', 'Trapezius', 'Onderarmen'],
    secundaireSpieren: ['Schouders', 'Benen', 'Rugspieren'],
  },
  {
    id: 'strength-deload',
    naam: 'Deload Week Training',
    beschrijving: 'Gereduceerde volume en intensiteit sessie: 50-60% van normaal gewicht, 50% van normaal volume. Laat het lichaam herstellen terwijl je bewegingen actief houdt.',
    uitleg: 'Lichte sessie voor herstel. 50-60% gewicht en volume. Actief herstel.',
    doel: ['herstel'],
    lichaamsdelen: ['fullbody'],
    niveau: 'beginner',
    equipment: ['barbell', 'dumbbell'],
    sets: '2',
    herhalingen: '8-10',
    tempo: '2-1-2',
    tips: ['Weersta de verleiding om te zwaar te trainen', 'Focus op techniek en mobiliteit', 'Voel je fris na de sessie', 'Plan elke 4-6 weken'],
    fouten: ['Toch zwaar trainen', 'Deload overslaan', 'Te lang deloaden'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Neuraal systeem'],
  },
  {
    id: 'db-complex-strength',
    naam: 'Dumbbell Krachtcomplex',
    beschrijving: 'Zes oefeningen met dezelfde dumbbells zonder neer te zetten: RDL → power clean → front squat → press → lunge → row. Vijf herhalingen per oefening. Bouwt kracht en conditie tegelijk.',
    uitleg: 'Zes krachtoefeningen achter elkaar. Kracht en conditie in één complex.',
    doel: ['kracht', 'conditie'],
    lichaamsdelen: ['fullbody'],
    niveau: 'gemiddeld',
    equipment: ['dumbbell'],
    sets: '4-5',
    herhalingen: '5 per oefening',
    tempo: 'gecontroleerd',
    tips: ['Gebruik een gewicht waarbij de press de beperkende factor is', 'Geen neerleggen tussen oefeningen', 'Rust 2-3 min tussen complexen', 'Begin licht — pas gewicht aan'],
    fouten: ['Te zwaar gewicht', 'Neerleggen tussen oefeningen', 'Techniek verwaarlozen'],
    primaireSpieren: ['Volledig lichaam'],
    secundaireSpieren: ['Core', 'Cardiovasculair systeem'],
  },
]

STRENGTH_OEFENINGEN.push(...fase5StrengthOefeningen)
